// *** WARNING: this file was generated by pulumi-java-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.descope.pulumi.descope.outputs;

import com.pulumi.core.annotations.CustomType;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import java.lang.String;
import java.util.Objects;

@CustomType
public final class ProjectConnectorsGenericEmailGatewayAuthenticationApiKey {
    /**
     * @return The API key.
     * 
     */
    private String key;
    /**
     * @return The API secret.
     * 
     */
    private String token;

    private ProjectConnectorsGenericEmailGatewayAuthenticationApiKey() {}
    /**
     * @return The API key.
     * 
     */
    public String key() {
        return this.key;
    }
    /**
     * @return The API secret.
     * 
     */
    public String token() {
        return this.token;
    }

    public static Builder builder() {
        return new Builder();
    }

    public static Builder builder(ProjectConnectorsGenericEmailGatewayAuthenticationApiKey defaults) {
        return new Builder(defaults);
    }
    @CustomType.Builder
    public static final class Builder {
        private String key;
        private String token;
        public Builder() {}
        public Builder(ProjectConnectorsGenericEmailGatewayAuthenticationApiKey defaults) {
    	      Objects.requireNonNull(defaults);
    	      this.key = defaults.key;
    	      this.token = defaults.token;
        }

        @CustomType.Setter
        public Builder key(String key) {
            if (key == null) {
              throw new MissingRequiredPropertyException("ProjectConnectorsGenericEmailGatewayAuthenticationApiKey", "key");
            }
            this.key = key;
            return this;
        }
        @CustomType.Setter
        public Builder token(String token) {
            if (token == null) {
              throw new MissingRequiredPropertyException("ProjectConnectorsGenericEmailGatewayAuthenticationApiKey", "token");
            }
            this.token = token;
            return this;
        }
        public ProjectConnectorsGenericEmailGatewayAuthenticationApiKey build() {
            final var _resultValue = new ProjectConnectorsGenericEmailGatewayAuthenticationApiKey();
            _resultValue.key = key;
            _resultValue.token = token;
            return _resultValue;
        }
    }
}
