// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.descope.pulumi.descope.outputs;

import com.descope.pulumi.descope.outputs.ProjectConnectorsSnowflakeAuditFilter;
import com.pulumi.core.annotations.CustomType;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import java.lang.Boolean;
import java.lang.Double;
import java.lang.String;
import java.util.List;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;

@CustomType
public final class ProjectConnectorsSnowflake {
    /**
     * @return A Snowflake Programmatic Access Token (PAT). The token&#39;s user must have CREATE DATABASE privileges.
     * 
     */
    private String apiKey;
    /**
     * @return Whether to enable streaming of audit events.
     * 
     */
    private @Nullable Boolean auditEnabled;
    /**
     * @return Specify which events will be sent to the external audit service (including tenant selection).
     * 
     */
    private @Nullable List<ProjectConnectorsSnowflakeAuditFilter> auditFilters;
    /**
     * @return The table to write audit events to. Defaults to `DESCOPE_AUDIT_LOGS`.
     * 
     */
    private @Nullable String auditTable;
    /**
     * @return The Snowflake database to use. Defaults to `DESCOPE_EXPORT_DB`.
     * 
     */
    private @Nullable String database;
    /**
     * @return A description of what your connector is used for.
     * 
     */
    private @Nullable String description;
    private @Nullable String id;
    /**
     * @return Whether to mask personally identifiable information in the logs.
     * 
     */
    private @Nullable Boolean maskPii;
    /**
     * @return The minimum time between writes to Snowflake, in minutes. When set, events are accumulated and written in a single batch at most once per interval, which lets the warehouse auto-suspend between writes and reduces cost. Set to 0 (or leave empty) to write events according to the default Descope cycle.
     * 
     */
    private @Nullable Double minFlushIntervalMinutes;
    /**
     * @return A custom name for your connector.
     * 
     */
    private String name;
    /**
     * @return The schema within the database. Defaults to `PUBLIC`.
     * 
     */
    private @Nullable String schema;
    /**
     * @return Your Snowflake account URL, e.g. `https://&lt;org&gt;-&lt;account&gt;.snowflakecomputing.com`.
     * 
     */
    private String site;
    /**
     * @return Whether to send troubleshooting events.
     * 
     */
    private @Nullable Boolean troubleshootLogEnabled;
    /**
     * @return The Snowflake warehouse to use. Defaults to `COMPUTE_WH`.
     * 
     */
    private @Nullable String warehouse;

    private ProjectConnectorsSnowflake() {}
    /**
     * @return A Snowflake Programmatic Access Token (PAT). The token&#39;s user must have CREATE DATABASE privileges.
     * 
     */
    public String apiKey() {
        return this.apiKey;
    }
    /**
     * @return Whether to enable streaming of audit events.
     * 
     */
    public Optional<Boolean> auditEnabled() {
        return Optional.ofNullable(this.auditEnabled);
    }
    /**
     * @return Specify which events will be sent to the external audit service (including tenant selection).
     * 
     */
    public List<ProjectConnectorsSnowflakeAuditFilter> auditFilters() {
        return this.auditFilters == null ? List.of() : this.auditFilters;
    }
    /**
     * @return The table to write audit events to. Defaults to `DESCOPE_AUDIT_LOGS`.
     * 
     */
    public Optional<String> auditTable() {
        return Optional.ofNullable(this.auditTable);
    }
    /**
     * @return The Snowflake database to use. Defaults to `DESCOPE_EXPORT_DB`.
     * 
     */
    public Optional<String> database() {
        return Optional.ofNullable(this.database);
    }
    /**
     * @return A description of what your connector is used for.
     * 
     */
    public Optional<String> description() {
        return Optional.ofNullable(this.description);
    }
    public Optional<String> id() {
        return Optional.ofNullable(this.id);
    }
    /**
     * @return Whether to mask personally identifiable information in the logs.
     * 
     */
    public Optional<Boolean> maskPii() {
        return Optional.ofNullable(this.maskPii);
    }
    /**
     * @return The minimum time between writes to Snowflake, in minutes. When set, events are accumulated and written in a single batch at most once per interval, which lets the warehouse auto-suspend between writes and reduces cost. Set to 0 (or leave empty) to write events according to the default Descope cycle.
     * 
     */
    public Optional<Double> minFlushIntervalMinutes() {
        return Optional.ofNullable(this.minFlushIntervalMinutes);
    }
    /**
     * @return A custom name for your connector.
     * 
     */
    public String name() {
        return this.name;
    }
    /**
     * @return The schema within the database. Defaults to `PUBLIC`.
     * 
     */
    public Optional<String> schema() {
        return Optional.ofNullable(this.schema);
    }
    /**
     * @return Your Snowflake account URL, e.g. `https://&lt;org&gt;-&lt;account&gt;.snowflakecomputing.com`.
     * 
     */
    public String site() {
        return this.site;
    }
    /**
     * @return Whether to send troubleshooting events.
     * 
     */
    public Optional<Boolean> troubleshootLogEnabled() {
        return Optional.ofNullable(this.troubleshootLogEnabled);
    }
    /**
     * @return The Snowflake warehouse to use. Defaults to `COMPUTE_WH`.
     * 
     */
    public Optional<String> warehouse() {
        return Optional.ofNullable(this.warehouse);
    }

    public static Builder builder() {
        return new Builder();
    }

    public static Builder builder(ProjectConnectorsSnowflake defaults) {
        return new Builder(defaults);
    }
    @CustomType.Builder
    public static final class Builder {
        private String apiKey;
        private @Nullable Boolean auditEnabled;
        private @Nullable List<ProjectConnectorsSnowflakeAuditFilter> auditFilters;
        private @Nullable String auditTable;
        private @Nullable String database;
        private @Nullable String description;
        private @Nullable String id;
        private @Nullable Boolean maskPii;
        private @Nullable Double minFlushIntervalMinutes;
        private String name;
        private @Nullable String schema;
        private String site;
        private @Nullable Boolean troubleshootLogEnabled;
        private @Nullable String warehouse;
        public Builder() {}
        public Builder(ProjectConnectorsSnowflake defaults) {
    	      Objects.requireNonNull(defaults);
    	      this.apiKey = defaults.apiKey;
    	      this.auditEnabled = defaults.auditEnabled;
    	      this.auditFilters = defaults.auditFilters;
    	      this.auditTable = defaults.auditTable;
    	      this.database = defaults.database;
    	      this.description = defaults.description;
    	      this.id = defaults.id;
    	      this.maskPii = defaults.maskPii;
    	      this.minFlushIntervalMinutes = defaults.minFlushIntervalMinutes;
    	      this.name = defaults.name;
    	      this.schema = defaults.schema;
    	      this.site = defaults.site;
    	      this.troubleshootLogEnabled = defaults.troubleshootLogEnabled;
    	      this.warehouse = defaults.warehouse;
        }

        @CustomType.Setter
        public Builder apiKey(String apiKey) {
            if (apiKey == null) {
              throw new MissingRequiredPropertyException("ProjectConnectorsSnowflake", "apiKey");
            }
            this.apiKey = apiKey;
            return this;
        }
        @CustomType.Setter
        public Builder auditEnabled(@Nullable Boolean auditEnabled) {

            this.auditEnabled = auditEnabled;
            return this;
        }
        @CustomType.Setter
        public Builder auditFilters(@Nullable List<ProjectConnectorsSnowflakeAuditFilter> auditFilters) {

            this.auditFilters = auditFilters;
            return this;
        }
        public Builder auditFilters(ProjectConnectorsSnowflakeAuditFilter... auditFilters) {
            return auditFilters(List.of(auditFilters));
        }
        @CustomType.Setter
        public Builder auditTable(@Nullable String auditTable) {

            this.auditTable = auditTable;
            return this;
        }
        @CustomType.Setter
        public Builder database(@Nullable String database) {

            this.database = database;
            return this;
        }
        @CustomType.Setter
        public Builder description(@Nullable String description) {

            this.description = description;
            return this;
        }
        @CustomType.Setter
        public Builder id(@Nullable String id) {

            this.id = id;
            return this;
        }
        @CustomType.Setter
        public Builder maskPii(@Nullable Boolean maskPii) {

            this.maskPii = maskPii;
            return this;
        }
        @CustomType.Setter
        public Builder minFlushIntervalMinutes(@Nullable Double minFlushIntervalMinutes) {

            this.minFlushIntervalMinutes = minFlushIntervalMinutes;
            return this;
        }
        @CustomType.Setter
        public Builder name(String name) {
            if (name == null) {
              throw new MissingRequiredPropertyException("ProjectConnectorsSnowflake", "name");
            }
            this.name = name;
            return this;
        }
        @CustomType.Setter
        public Builder schema(@Nullable String schema) {

            this.schema = schema;
            return this;
        }
        @CustomType.Setter
        public Builder site(String site) {
            if (site == null) {
              throw new MissingRequiredPropertyException("ProjectConnectorsSnowflake", "site");
            }
            this.site = site;
            return this;
        }
        @CustomType.Setter
        public Builder troubleshootLogEnabled(@Nullable Boolean troubleshootLogEnabled) {

            this.troubleshootLogEnabled = troubleshootLogEnabled;
            return this;
        }
        @CustomType.Setter
        public Builder warehouse(@Nullable String warehouse) {

            this.warehouse = warehouse;
            return this;
        }
        public ProjectConnectorsSnowflake build() {
            final var _resultValue = new ProjectConnectorsSnowflake();
            _resultValue.apiKey = apiKey;
            _resultValue.auditEnabled = auditEnabled;
            _resultValue.auditFilters = auditFilters;
            _resultValue.auditTable = auditTable;
            _resultValue.database = database;
            _resultValue.description = description;
            _resultValue.id = id;
            _resultValue.maskPii = maskPii;
            _resultValue.minFlushIntervalMinutes = minFlushIntervalMinutes;
            _resultValue.name = name;
            _resultValue.schema = schema;
            _resultValue.site = site;
            _resultValue.troubleshootLogEnabled = troubleshootLogEnabled;
            _resultValue.warehouse = warehouse;
            return _resultValue;
        }
    }
}
