// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.descope.pulumi.descope.outputs;

import com.descope.pulumi.descope.outputs.WsfedAppGroupsMappingRole;
import com.pulumi.core.annotations.CustomType;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import java.lang.String;
import java.util.List;
import java.util.Objects;
import javax.annotation.Nullable;

@CustomType
public final class WsfedAppGroupsMapping {
    /**
     * @return The filter type for the groups mapping.
     * 
     */
    private String filterType;
    /**
     * @return The name of the groups mapping.
     * 
     */
    private String name;
    /**
     * @return The Descope roles that are included in the groups mapping.
     * 
     */
    private @Nullable List<WsfedAppGroupsMappingRole> roles;
    /**
     * @return The type of the groups mapping.
     * 
     */
    private String type;
    /**
     * @return The value of the groups mapping.
     * 
     */
    private String value;

    private WsfedAppGroupsMapping() {}
    /**
     * @return The filter type for the groups mapping.
     * 
     */
    public String filterType() {
        return this.filterType;
    }
    /**
     * @return The name of the groups mapping.
     * 
     */
    public String name() {
        return this.name;
    }
    /**
     * @return The Descope roles that are included in the groups mapping.
     * 
     */
    public List<WsfedAppGroupsMappingRole> roles() {
        return this.roles == null ? List.of() : this.roles;
    }
    /**
     * @return The type of the groups mapping.
     * 
     */
    public String type() {
        return this.type;
    }
    /**
     * @return The value of the groups mapping.
     * 
     */
    public String value() {
        return this.value;
    }

    public static Builder builder() {
        return new Builder();
    }

    public static Builder builder(WsfedAppGroupsMapping defaults) {
        return new Builder(defaults);
    }
    @CustomType.Builder
    public static final class Builder {
        private String filterType;
        private String name;
        private @Nullable List<WsfedAppGroupsMappingRole> roles;
        private String type;
        private String value;
        public Builder() {}
        public Builder(WsfedAppGroupsMapping defaults) {
    	      Objects.requireNonNull(defaults);
    	      this.filterType = defaults.filterType;
    	      this.name = defaults.name;
    	      this.roles = defaults.roles;
    	      this.type = defaults.type;
    	      this.value = defaults.value;
        }

        @CustomType.Setter
        public Builder filterType(String filterType) {
            if (filterType == null) {
              throw new MissingRequiredPropertyException("WsfedAppGroupsMapping", "filterType");
            }
            this.filterType = filterType;
            return this;
        }
        @CustomType.Setter
        public Builder name(String name) {
            if (name == null) {
              throw new MissingRequiredPropertyException("WsfedAppGroupsMapping", "name");
            }
            this.name = name;
            return this;
        }
        @CustomType.Setter
        public Builder roles(@Nullable List<WsfedAppGroupsMappingRole> roles) {

            this.roles = roles;
            return this;
        }
        public Builder roles(WsfedAppGroupsMappingRole... roles) {
            return roles(List.of(roles));
        }
        @CustomType.Setter
        public Builder type(String type) {
            if (type == null) {
              throw new MissingRequiredPropertyException("WsfedAppGroupsMapping", "type");
            }
            this.type = type;
            return this;
        }
        @CustomType.Setter
        public Builder value(String value) {
            if (value == null) {
              throw new MissingRequiredPropertyException("WsfedAppGroupsMapping", "value");
            }
            this.value = value;
            return this;
        }
        public WsfedAppGroupsMapping build() {
            final var _resultValue = new WsfedAppGroupsMapping();
            _resultValue.filterType = filterType;
            _resultValue.name = name;
            _resultValue.roles = roles;
            _resultValue.type = type;
            _resultValue.value = value;
            return _resultValue;
        }
    }
}
