// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Descope.Pulumi.Descope.Outputs
{

    [OutputType]
    public sealed class ProjectConnectorsIncode
    {
        /// <summary>
        /// Your InCode API key.
        /// </summary>
        public readonly string ApiKey;
        /// <summary>
        /// The base URL of the Incode API
        /// </summary>
        public readonly string ApiUrl;
        /// <summary>
        /// A description of what your connector is used for.
        /// </summary>
        public readonly string? Description;
        /// <summary>
        /// Your wanted InCode's flow ID.
        /// </summary>
        public readonly string FlowId;
        public readonly string? Id;
        /// <summary>
        /// A custom name for your connector.
        /// </summary>
        public readonly string Name;

        [OutputConstructor]
        private ProjectConnectorsIncode(
            string apiKey,

            string apiUrl,

            string? description,

            string flowId,

            string? id,

            string name)
        {
            ApiKey = apiKey;
            ApiUrl = apiUrl;
            Description = description;
            FlowId = flowId;
            Id = id;
            Name = name;
        }
    }
}
