// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Descope.Pulumi.Descope.Outputs
{

    [OutputType]
    public sealed class ProjectConnectorsRekognition
    {
        public readonly string AccessKeyId;
        public readonly string CollectionId;
        public readonly string? Description;
        public readonly string? Id;
        public readonly string Name;
        public readonly string SecretAccessKey;

        [OutputConstructor]
        private ProjectConnectorsRekognition(
            string accessKeyId,

            string collectionId,

            string? description,

            string? id,

            string name,

            string secretAccessKey)
        {
            AccessKeyId = accessKeyId;
            CollectionId = collectionId;
            Description = description;
            Id = id;
            Name = name;
            SecretAccessKey = secretAccessKey;
        }
    }
}
