// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.descope.pulumi.descope.inputs;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Import;
import java.lang.Boolean;
import java.lang.String;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;


public final class DarwiniumConnectorState extends com.pulumi.resources.ResourceArgs {

    public static final DarwiniumConnectorState Empty = new DarwiniumConnectorState();

    /**
     * The default result to return if no result is available.
     * 
     */
    @Import(name="defaultResult")
    private @Nullable Output<String> defaultResult;

    /**
     * @return The default result to return if no result is available.
     * 
     */
    public Optional<Output<String>> defaultResult() {
        return Optional.ofNullable(this.defaultResult);
    }

    /**
     * A description of what your connector is used for.
     * 
     */
    @Import(name="description")
    private @Nullable Output<String> description;

    /**
     * @return A description of what your connector is used for.
     * 
     */
    public Optional<Output<String>> description() {
        return Optional.ofNullable(this.description);
    }

    /**
     * Whether the connector is disabled. This can be used to temporarily stop a connector from executing without fully deleting it.
     * 
     */
    @Import(name="disabled")
    private @Nullable Output<Boolean> disabled;

    /**
     * @return Whether the connector is disabled. This can be used to temporarily stop a connector from executing without fully deleting it.
     * 
     */
    public Optional<Output<Boolean>> disabled() {
        return Optional.ofNullable(this.disabled);
    }

    /**
     * The name of the Darwinium journey to use for profiling.
     * 
     */
    @Import(name="journeyName")
    private @Nullable Output<String> journeyName;

    /**
     * @return The name of the Darwinium journey to use for profiling.
     * 
     */
    public Optional<Output<String>> journeyName() {
        return Optional.ofNullable(this.journeyName);
    }

    /**
     * A custom name for your connector.
     * 
     */
    @Import(name="name")
    private @Nullable Output<String> name;

    /**
     * @return A custom name for your connector.
     * 
     */
    public Optional<Output<String>> name() {
        return Optional.ofNullable(this.name);
    }

    /**
     * The name of the Darwinium Native Mobile API to use.
     * 
     */
    @Import(name="nativeApiName")
    private @Nullable Output<String> nativeApiName;

    /**
     * @return The name of the Darwinium Native Mobile API to use.
     * 
     */
    public Optional<Output<String>> nativeApiName() {
        return Optional.ofNullable(this.nativeApiName);
    }

    /**
     * The key name for the native profiling blob sent via the client parameter. If not provided, the default key of &#39;nativeProfilingBlob&#39; will be used.
     * 
     */
    @Import(name="nativeBlobKeyName")
    private @Nullable Output<String> nativeBlobKeyName;

    /**
     * @return The key name for the native profiling blob sent via the client parameter. If not provided, the default key of &#39;nativeProfilingBlob&#39; will be used.
     * 
     */
    public Optional<Output<String>> nativeBlobKeyName() {
        return Optional.ofNullable(this.nativeBlobKeyName);
    }

    /**
     * The name of the Darwinium node.
     * 
     */
    @Import(name="nodeName")
    private @Nullable Output<String> nodeName;

    /**
     * @return The name of the Darwinium node.
     * 
     */
    public Optional<Output<String>> nodeName() {
        return Optional.ofNullable(this.nodeName);
    }

    /**
     * The passphrase for the PEM certificate, if applicable.
     * 
     */
    @Import(name="passphrase")
    private @Nullable Output<String> passphrase;

    /**
     * @return The passphrase for the PEM certificate, if applicable.
     * 
     */
    public Optional<Output<String>> passphrase() {
        return Optional.ofNullable(this.passphrase);
    }

    /**
     * The PEM certificate for client authentication.
     * 
     */
    @Import(name="pemCertificate")
    private @Nullable Output<String> pemCertificate;

    /**
     * @return The PEM certificate for client authentication.
     * 
     */
    public Optional<Output<String>> pemCertificate() {
        return Optional.ofNullable(this.pemCertificate);
    }

    /**
     * The private key for client authentication.
     * 
     */
    @Import(name="privateKey")
    private @Nullable Output<String> privateKey;

    /**
     * @return The private key for client authentication.
     * 
     */
    public Optional<Output<String>> privateKey() {
        return Optional.ofNullable(this.privateKey);
    }

    /**
     * The custom URL where the Darwinium Tags script is hosted. If not provided, the default Darwinium script URL will be used.
     * 
     */
    @Import(name="profilingTagsScriptUrl")
    private @Nullable Output<String> profilingTagsScriptUrl;

    /**
     * @return The custom URL where the Darwinium Tags script is hosted. If not provided, the default Darwinium script URL will be used.
     * 
     */
    public Optional<Output<String>> profilingTagsScriptUrl() {
        return Optional.ofNullable(this.profilingTagsScriptUrl);
    }

    /**
     * The ID of the Descope project that the connector belongs to. Changing this value will require the resource to be deleted and recreated.
     * 
     */
    @Import(name="projectId")
    private @Nullable Output<String> projectId;

    /**
     * @return The ID of the Descope project that the connector belongs to. Changing this value will require the resource to be deleted and recreated.
     * 
     */
    public Optional<Output<String>> projectId() {
        return Optional.ofNullable(this.projectId);
    }

    /**
     * The name of the Darwinium Web API to use.
     * 
     */
    @Import(name="webApiName")
    private @Nullable Output<String> webApiName;

    /**
     * @return The name of the Darwinium Web API to use.
     * 
     */
    public Optional<Output<String>> webApiName() {
        return Optional.ofNullable(this.webApiName);
    }

    private DarwiniumConnectorState() {}

    private DarwiniumConnectorState(DarwiniumConnectorState $) {
        this.defaultResult = $.defaultResult;
        this.description = $.description;
        this.disabled = $.disabled;
        this.journeyName = $.journeyName;
        this.name = $.name;
        this.nativeApiName = $.nativeApiName;
        this.nativeBlobKeyName = $.nativeBlobKeyName;
        this.nodeName = $.nodeName;
        this.passphrase = $.passphrase;
        this.pemCertificate = $.pemCertificate;
        this.privateKey = $.privateKey;
        this.profilingTagsScriptUrl = $.profilingTagsScriptUrl;
        this.projectId = $.projectId;
        this.webApiName = $.webApiName;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(DarwiniumConnectorState defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private DarwiniumConnectorState $;

        public Builder() {
            $ = new DarwiniumConnectorState();
        }

        public Builder(DarwiniumConnectorState defaults) {
            $ = new DarwiniumConnectorState(Objects.requireNonNull(defaults));
        }

        /**
         * @param defaultResult The default result to return if no result is available.
         * 
         * @return builder
         * 
         */
        public Builder defaultResult(@Nullable Output<String> defaultResult) {
            $.defaultResult = defaultResult;
            return this;
        }

        /**
         * @param defaultResult The default result to return if no result is available.
         * 
         * @return builder
         * 
         */
        public Builder defaultResult(String defaultResult) {
            return defaultResult(Output.of(defaultResult));
        }

        /**
         * @param description A description of what your connector is used for.
         * 
         * @return builder
         * 
         */
        public Builder description(@Nullable Output<String> description) {
            $.description = description;
            return this;
        }

        /**
         * @param description A description of what your connector is used for.
         * 
         * @return builder
         * 
         */
        public Builder description(String description) {
            return description(Output.of(description));
        }

        /**
         * @param disabled Whether the connector is disabled. This can be used to temporarily stop a connector from executing without fully deleting it.
         * 
         * @return builder
         * 
         */
        public Builder disabled(@Nullable Output<Boolean> disabled) {
            $.disabled = disabled;
            return this;
        }

        /**
         * @param disabled Whether the connector is disabled. This can be used to temporarily stop a connector from executing without fully deleting it.
         * 
         * @return builder
         * 
         */
        public Builder disabled(Boolean disabled) {
            return disabled(Output.of(disabled));
        }

        /**
         * @param journeyName The name of the Darwinium journey to use for profiling.
         * 
         * @return builder
         * 
         */
        public Builder journeyName(@Nullable Output<String> journeyName) {
            $.journeyName = journeyName;
            return this;
        }

        /**
         * @param journeyName The name of the Darwinium journey to use for profiling.
         * 
         * @return builder
         * 
         */
        public Builder journeyName(String journeyName) {
            return journeyName(Output.of(journeyName));
        }

        /**
         * @param name A custom name for your connector.
         * 
         * @return builder
         * 
         */
        public Builder name(@Nullable Output<String> name) {
            $.name = name;
            return this;
        }

        /**
         * @param name A custom name for your connector.
         * 
         * @return builder
         * 
         */
        public Builder name(String name) {
            return name(Output.of(name));
        }

        /**
         * @param nativeApiName The name of the Darwinium Native Mobile API to use.
         * 
         * @return builder
         * 
         */
        public Builder nativeApiName(@Nullable Output<String> nativeApiName) {
            $.nativeApiName = nativeApiName;
            return this;
        }

        /**
         * @param nativeApiName The name of the Darwinium Native Mobile API to use.
         * 
         * @return builder
         * 
         */
        public Builder nativeApiName(String nativeApiName) {
            return nativeApiName(Output.of(nativeApiName));
        }

        /**
         * @param nativeBlobKeyName The key name for the native profiling blob sent via the client parameter. If not provided, the default key of &#39;nativeProfilingBlob&#39; will be used.
         * 
         * @return builder
         * 
         */
        public Builder nativeBlobKeyName(@Nullable Output<String> nativeBlobKeyName) {
            $.nativeBlobKeyName = nativeBlobKeyName;
            return this;
        }

        /**
         * @param nativeBlobKeyName The key name for the native profiling blob sent via the client parameter. If not provided, the default key of &#39;nativeProfilingBlob&#39; will be used.
         * 
         * @return builder
         * 
         */
        public Builder nativeBlobKeyName(String nativeBlobKeyName) {
            return nativeBlobKeyName(Output.of(nativeBlobKeyName));
        }

        /**
         * @param nodeName The name of the Darwinium node.
         * 
         * @return builder
         * 
         */
        public Builder nodeName(@Nullable Output<String> nodeName) {
            $.nodeName = nodeName;
            return this;
        }

        /**
         * @param nodeName The name of the Darwinium node.
         * 
         * @return builder
         * 
         */
        public Builder nodeName(String nodeName) {
            return nodeName(Output.of(nodeName));
        }

        /**
         * @param passphrase The passphrase for the PEM certificate, if applicable.
         * 
         * @return builder
         * 
         */
        public Builder passphrase(@Nullable Output<String> passphrase) {
            $.passphrase = passphrase;
            return this;
        }

        /**
         * @param passphrase The passphrase for the PEM certificate, if applicable.
         * 
         * @return builder
         * 
         */
        public Builder passphrase(String passphrase) {
            return passphrase(Output.of(passphrase));
        }

        /**
         * @param pemCertificate The PEM certificate for client authentication.
         * 
         * @return builder
         * 
         */
        public Builder pemCertificate(@Nullable Output<String> pemCertificate) {
            $.pemCertificate = pemCertificate;
            return this;
        }

        /**
         * @param pemCertificate The PEM certificate for client authentication.
         * 
         * @return builder
         * 
         */
        public Builder pemCertificate(String pemCertificate) {
            return pemCertificate(Output.of(pemCertificate));
        }

        /**
         * @param privateKey The private key for client authentication.
         * 
         * @return builder
         * 
         */
        public Builder privateKey(@Nullable Output<String> privateKey) {
            $.privateKey = privateKey;
            return this;
        }

        /**
         * @param privateKey The private key for client authentication.
         * 
         * @return builder
         * 
         */
        public Builder privateKey(String privateKey) {
            return privateKey(Output.of(privateKey));
        }

        /**
         * @param profilingTagsScriptUrl The custom URL where the Darwinium Tags script is hosted. If not provided, the default Darwinium script URL will be used.
         * 
         * @return builder
         * 
         */
        public Builder profilingTagsScriptUrl(@Nullable Output<String> profilingTagsScriptUrl) {
            $.profilingTagsScriptUrl = profilingTagsScriptUrl;
            return this;
        }

        /**
         * @param profilingTagsScriptUrl The custom URL where the Darwinium Tags script is hosted. If not provided, the default Darwinium script URL will be used.
         * 
         * @return builder
         * 
         */
        public Builder profilingTagsScriptUrl(String profilingTagsScriptUrl) {
            return profilingTagsScriptUrl(Output.of(profilingTagsScriptUrl));
        }

        /**
         * @param projectId The ID of the Descope project that the connector belongs to. Changing this value will require the resource to be deleted and recreated.
         * 
         * @return builder
         * 
         */
        public Builder projectId(@Nullable Output<String> projectId) {
            $.projectId = projectId;
            return this;
        }

        /**
         * @param projectId The ID of the Descope project that the connector belongs to. Changing this value will require the resource to be deleted and recreated.
         * 
         * @return builder
         * 
         */
        public Builder projectId(String projectId) {
            return projectId(Output.of(projectId));
        }

        /**
         * @param webApiName The name of the Darwinium Web API to use.
         * 
         * @return builder
         * 
         */
        public Builder webApiName(@Nullable Output<String> webApiName) {
            $.webApiName = webApiName;
            return this;
        }

        /**
         * @param webApiName The name of the Darwinium Web API to use.
         * 
         * @return builder
         * 
         */
        public Builder webApiName(String webApiName) {
            return webApiName(Output.of(webApiName));
        }

        public DarwiniumConnectorState build() {
            return $;
        }
    }

}
