// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.descope.pulumi.descope.inputs;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Import;
import java.lang.Boolean;
import java.lang.String;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;


public final class GoogleCloudTranslationConnectorState extends com.pulumi.resources.ResourceArgs {

    public static final GoogleCloudTranslationConnectorState Empty = new GoogleCloudTranslationConnectorState();

    /**
     * The Google Cloud project ID where the Google Cloud Translation is managed.
     * 
     */
    @Import(name="configProjectId")
    private @Nullable Output<String> configProjectId;

    /**
     * @return The Google Cloud project ID where the Google Cloud Translation is managed.
     * 
     */
    public Optional<Output<String>> configProjectId() {
        return Optional.ofNullable(this.configProjectId);
    }

    /**
     * A description of what your connector is used for.
     * 
     */
    @Import(name="description")
    private @Nullable Output<String> description;

    /**
     * @return A description of what your connector is used for.
     * 
     */
    public Optional<Output<String>> description() {
        return Optional.ofNullable(this.description);
    }

    /**
     * Whether the connector is disabled. This can be used to temporarily stop a connector from executing without fully deleting it.
     * 
     */
    @Import(name="disabled")
    private @Nullable Output<Boolean> disabled;

    /**
     * @return Whether the connector is disabled. This can be used to temporarily stop a connector from executing without fully deleting it.
     * 
     */
    public Optional<Output<Boolean>> disabled() {
        return Optional.ofNullable(this.disabled);
    }

    /**
     * A custom name for your connector.
     * 
     */
    @Import(name="name")
    private @Nullable Output<String> name;

    /**
     * @return A custom name for your connector.
     * 
     */
    public Optional<Output<String>> name() {
        return Optional.ofNullable(this.name);
    }

    /**
     * The ID of the Descope project that the connector belongs to. Changing this value will require the resource to be deleted and recreated.
     * 
     */
    @Import(name="projectId")
    private @Nullable Output<String> projectId;

    /**
     * @return The ID of the Descope project that the connector belongs to. Changing this value will require the resource to be deleted and recreated.
     * 
     */
    public Optional<Output<String>> projectId() {
        return Optional.ofNullable(this.projectId);
    }

    /**
     * Service Account JSON associated with the current project.
     * 
     */
    @Import(name="serviceAccountJson")
    private @Nullable Output<String> serviceAccountJson;

    /**
     * @return Service Account JSON associated with the current project.
     * 
     */
    public Optional<Output<String>> serviceAccountJson() {
        return Optional.ofNullable(this.serviceAccountJson);
    }

    private GoogleCloudTranslationConnectorState() {}

    private GoogleCloudTranslationConnectorState(GoogleCloudTranslationConnectorState $) {
        this.configProjectId = $.configProjectId;
        this.description = $.description;
        this.disabled = $.disabled;
        this.name = $.name;
        this.projectId = $.projectId;
        this.serviceAccountJson = $.serviceAccountJson;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(GoogleCloudTranslationConnectorState defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private GoogleCloudTranslationConnectorState $;

        public Builder() {
            $ = new GoogleCloudTranslationConnectorState();
        }

        public Builder(GoogleCloudTranslationConnectorState defaults) {
            $ = new GoogleCloudTranslationConnectorState(Objects.requireNonNull(defaults));
        }

        /**
         * @param configProjectId The Google Cloud project ID where the Google Cloud Translation is managed.
         * 
         * @return builder
         * 
         */
        public Builder configProjectId(@Nullable Output<String> configProjectId) {
            $.configProjectId = configProjectId;
            return this;
        }

        /**
         * @param configProjectId The Google Cloud project ID where the Google Cloud Translation is managed.
         * 
         * @return builder
         * 
         */
        public Builder configProjectId(String configProjectId) {
            return configProjectId(Output.of(configProjectId));
        }

        /**
         * @param description A description of what your connector is used for.
         * 
         * @return builder
         * 
         */
        public Builder description(@Nullable Output<String> description) {
            $.description = description;
            return this;
        }

        /**
         * @param description A description of what your connector is used for.
         * 
         * @return builder
         * 
         */
        public Builder description(String description) {
            return description(Output.of(description));
        }

        /**
         * @param disabled Whether the connector is disabled. This can be used to temporarily stop a connector from executing without fully deleting it.
         * 
         * @return builder
         * 
         */
        public Builder disabled(@Nullable Output<Boolean> disabled) {
            $.disabled = disabled;
            return this;
        }

        /**
         * @param disabled Whether the connector is disabled. This can be used to temporarily stop a connector from executing without fully deleting it.
         * 
         * @return builder
         * 
         */
        public Builder disabled(Boolean disabled) {
            return disabled(Output.of(disabled));
        }

        /**
         * @param name A custom name for your connector.
         * 
         * @return builder
         * 
         */
        public Builder name(@Nullable Output<String> name) {
            $.name = name;
            return this;
        }

        /**
         * @param name A custom name for your connector.
         * 
         * @return builder
         * 
         */
        public Builder name(String name) {
            return name(Output.of(name));
        }

        /**
         * @param projectId The ID of the Descope project that the connector belongs to. Changing this value will require the resource to be deleted and recreated.
         * 
         * @return builder
         * 
         */
        public Builder projectId(@Nullable Output<String> projectId) {
            $.projectId = projectId;
            return this;
        }

        /**
         * @param projectId The ID of the Descope project that the connector belongs to. Changing this value will require the resource to be deleted and recreated.
         * 
         * @return builder
         * 
         */
        public Builder projectId(String projectId) {
            return projectId(Output.of(projectId));
        }

        /**
         * @param serviceAccountJson Service Account JSON associated with the current project.
         * 
         * @return builder
         * 
         */
        public Builder serviceAccountJson(@Nullable Output<String> serviceAccountJson) {
            $.serviceAccountJson = serviceAccountJson;
            return this;
        }

        /**
         * @param serviceAccountJson Service Account JSON associated with the current project.
         * 
         * @return builder
         * 
         */
        public Builder serviceAccountJson(String serviceAccountJson) {
            return serviceAccountJson(Output.of(serviceAccountJson));
        }

        public GoogleCloudTranslationConnectorState build() {
            return $;
        }
    }

}
