// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.descope.pulumi.descope.inputs;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Import;
import java.lang.Boolean;
import java.lang.Double;
import java.lang.String;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;


public final class SmtpConnectorState extends com.pulumi.resources.ResourceArgs {

    public static final SmtpConnectorState Empty = new SmtpConnectorState();

    /**
     * The authentication method to use when connecting to the SMTP server.
     * 
     */
    @Import(name="authMethod")
    private @Nullable Output<String> authMethod;

    /**
     * @return The authentication method to use when connecting to the SMTP server.
     * 
     */
    public Optional<Output<String>> authMethod() {
        return Optional.ofNullable(this.authMethod);
    }

    /**
     * A description of what your connector is used for.
     * 
     */
    @Import(name="description")
    private @Nullable Output<String> description;

    /**
     * @return A description of what your connector is used for.
     * 
     */
    public Optional<Output<String>> description() {
        return Optional.ofNullable(this.description);
    }

    /**
     * The hostname or IP address of the SMTP server.
     * 
     */
    @Import(name="host")
    private @Nullable Output<String> host;

    /**
     * @return The hostname or IP address of the SMTP server.
     * 
     */
    public Optional<Output<String>> host() {
        return Optional.ofNullable(this.host);
    }

    /**
     * A custom name for your connector.
     * 
     */
    @Import(name="name")
    private @Nullable Output<String> name;

    /**
     * @return A custom name for your connector.
     * 
     */
    public Optional<Output<String>> name() {
        return Optional.ofNullable(this.name);
    }

    /**
     * The password used to authenticate with the SMTP server.
     * 
     */
    @Import(name="password")
    private @Nullable Output<String> password;

    /**
     * @return The password used to authenticate with the SMTP server.
     * 
     */
    public Optional<Output<String>> password() {
        return Optional.ofNullable(this.password);
    }

    /**
     * The port the SMTP server listens on.
     * 
     */
    @Import(name="port")
    private @Nullable Output<Double> port;

    /**
     * @return The port the SMTP server listens on.
     * 
     */
    public Optional<Output<Double>> port() {
        return Optional.ofNullable(this.port);
    }

    /**
     * The ID of the Descope project that the connector belongs to. Changing this value will require the resource to be deleted and recreated.
     * 
     */
    @Import(name="projectId")
    private @Nullable Output<String> projectId;

    /**
     * @return The ID of the Descope project that the connector belongs to. Changing this value will require the resource to be deleted and recreated.
     * 
     */
    public Optional<Output<String>> projectId() {
        return Optional.ofNullable(this.projectId);
    }

    /**
     * The email address that emails are sent from. Make sure it is properly registered with your server.
     * 
     */
    @Import(name="senderEmail")
    private @Nullable Output<String> senderEmail;

    /**
     * @return The email address that emails are sent from. Make sure it is properly registered with your server.
     * 
     */
    public Optional<Output<String>> senderEmail() {
        return Optional.ofNullable(this.senderEmail);
    }

    /**
     * The name shown as the sender of the emails.
     * 
     */
    @Import(name="senderName")
    private @Nullable Output<String> senderName;

    /**
     * @return The name shown as the sender of the emails.
     * 
     */
    public Optional<Output<String>> senderName() {
        return Optional.ofNullable(this.senderName);
    }

    /**
     * Whether the connector should send all requests from specific static IPs.
     * 
     */
    @Import(name="useStaticIps")
    private @Nullable Output<Boolean> useStaticIps;

    /**
     * @return Whether the connector should send all requests from specific static IPs.
     * 
     */
    public Optional<Output<Boolean>> useStaticIps() {
        return Optional.ofNullable(this.useStaticIps);
    }

    /**
     * The username used to authenticate with the SMTP server.
     * 
     */
    @Import(name="username")
    private @Nullable Output<String> username;

    /**
     * @return The username used to authenticate with the SMTP server.
     * 
     */
    public Optional<Output<String>> username() {
        return Optional.ofNullable(this.username);
    }

    private SmtpConnectorState() {}

    private SmtpConnectorState(SmtpConnectorState $) {
        this.authMethod = $.authMethod;
        this.description = $.description;
        this.host = $.host;
        this.name = $.name;
        this.password = $.password;
        this.port = $.port;
        this.projectId = $.projectId;
        this.senderEmail = $.senderEmail;
        this.senderName = $.senderName;
        this.useStaticIps = $.useStaticIps;
        this.username = $.username;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(SmtpConnectorState defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private SmtpConnectorState $;

        public Builder() {
            $ = new SmtpConnectorState();
        }

        public Builder(SmtpConnectorState defaults) {
            $ = new SmtpConnectorState(Objects.requireNonNull(defaults));
        }

        /**
         * @param authMethod The authentication method to use when connecting to the SMTP server.
         * 
         * @return builder
         * 
         */
        public Builder authMethod(@Nullable Output<String> authMethod) {
            $.authMethod = authMethod;
            return this;
        }

        /**
         * @param authMethod The authentication method to use when connecting to the SMTP server.
         * 
         * @return builder
         * 
         */
        public Builder authMethod(String authMethod) {
            return authMethod(Output.of(authMethod));
        }

        /**
         * @param description A description of what your connector is used for.
         * 
         * @return builder
         * 
         */
        public Builder description(@Nullable Output<String> description) {
            $.description = description;
            return this;
        }

        /**
         * @param description A description of what your connector is used for.
         * 
         * @return builder
         * 
         */
        public Builder description(String description) {
            return description(Output.of(description));
        }

        /**
         * @param host The hostname or IP address of the SMTP server.
         * 
         * @return builder
         * 
         */
        public Builder host(@Nullable Output<String> host) {
            $.host = host;
            return this;
        }

        /**
         * @param host The hostname or IP address of the SMTP server.
         * 
         * @return builder
         * 
         */
        public Builder host(String host) {
            return host(Output.of(host));
        }

        /**
         * @param name A custom name for your connector.
         * 
         * @return builder
         * 
         */
        public Builder name(@Nullable Output<String> name) {
            $.name = name;
            return this;
        }

        /**
         * @param name A custom name for your connector.
         * 
         * @return builder
         * 
         */
        public Builder name(String name) {
            return name(Output.of(name));
        }

        /**
         * @param password The password used to authenticate with the SMTP server.
         * 
         * @return builder
         * 
         */
        public Builder password(@Nullable Output<String> password) {
            $.password = password;
            return this;
        }

        /**
         * @param password The password used to authenticate with the SMTP server.
         * 
         * @return builder
         * 
         */
        public Builder password(String password) {
            return password(Output.of(password));
        }

        /**
         * @param port The port the SMTP server listens on.
         * 
         * @return builder
         * 
         */
        public Builder port(@Nullable Output<Double> port) {
            $.port = port;
            return this;
        }

        /**
         * @param port The port the SMTP server listens on.
         * 
         * @return builder
         * 
         */
        public Builder port(Double port) {
            return port(Output.of(port));
        }

        /**
         * @param projectId The ID of the Descope project that the connector belongs to. Changing this value will require the resource to be deleted and recreated.
         * 
         * @return builder
         * 
         */
        public Builder projectId(@Nullable Output<String> projectId) {
            $.projectId = projectId;
            return this;
        }

        /**
         * @param projectId The ID of the Descope project that the connector belongs to. Changing this value will require the resource to be deleted and recreated.
         * 
         * @return builder
         * 
         */
        public Builder projectId(String projectId) {
            return projectId(Output.of(projectId));
        }

        /**
         * @param senderEmail The email address that emails are sent from. Make sure it is properly registered with your server.
         * 
         * @return builder
         * 
         */
        public Builder senderEmail(@Nullable Output<String> senderEmail) {
            $.senderEmail = senderEmail;
            return this;
        }

        /**
         * @param senderEmail The email address that emails are sent from. Make sure it is properly registered with your server.
         * 
         * @return builder
         * 
         */
        public Builder senderEmail(String senderEmail) {
            return senderEmail(Output.of(senderEmail));
        }

        /**
         * @param senderName The name shown as the sender of the emails.
         * 
         * @return builder
         * 
         */
        public Builder senderName(@Nullable Output<String> senderName) {
            $.senderName = senderName;
            return this;
        }

        /**
         * @param senderName The name shown as the sender of the emails.
         * 
         * @return builder
         * 
         */
        public Builder senderName(String senderName) {
            return senderName(Output.of(senderName));
        }

        /**
         * @param useStaticIps Whether the connector should send all requests from specific static IPs.
         * 
         * @return builder
         * 
         */
        public Builder useStaticIps(@Nullable Output<Boolean> useStaticIps) {
            $.useStaticIps = useStaticIps;
            return this;
        }

        /**
         * @param useStaticIps Whether the connector should send all requests from specific static IPs.
         * 
         * @return builder
         * 
         */
        public Builder useStaticIps(Boolean useStaticIps) {
            return useStaticIps(Output.of(useStaticIps));
        }

        /**
         * @param username The username used to authenticate with the SMTP server.
         * 
         * @return builder
         * 
         */
        public Builder username(@Nullable Output<String> username) {
            $.username = username;
            return this;
        }

        /**
         * @param username The username used to authenticate with the SMTP server.
         * 
         * @return builder
         * 
         */
        public Builder username(String username) {
            return username(Output.of(username));
        }

        public SmtpConnectorState build() {
            return $;
        }
    }

}
