// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.descope.pulumi.descope.inputs;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Import;
import java.lang.String;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;


public final class SnsConnectorState extends com.pulumi.resources.ResourceArgs {

    public static final SnsConnectorState Empty = new SnsConnectorState();

    /**
     * The AWS access key ID. Required when the authentication type is &#39;credentials&#39;.
     * 
     */
    @Import(name="accessKeyId")
    private @Nullable Output<String> accessKeyId;

    /**
     * @return The AWS access key ID. Required when the authentication type is &#39;credentials&#39;.
     * 
     */
    public Optional<Output<String>> accessKeyId() {
        return Optional.ofNullable(this.accessKeyId);
    }

    /**
     * How to authenticate with AWS: using static credentials or by assuming an IAM role.
     * 
     */
    @Import(name="authType")
    private @Nullable Output<String> authType;

    /**
     * @return How to authenticate with AWS: using static credentials or by assuming an IAM role.
     * 
     */
    public Optional<Output<String>> authType() {
        return Optional.ofNullable(this.authType);
    }

    /**
     * A description of what your connector is used for.
     * 
     */
    @Import(name="description")
    private @Nullable Output<String> description;

    /**
     * @return A description of what your connector is used for.
     * 
     */
    public Optional<Output<String>> description() {
        return Optional.ofNullable(this.description);
    }

    /**
     * A custom endpoint for the SNS API. Leave empty to use the default AWS endpoint.
     * 
     */
    @Import(name="endpoint")
    private @Nullable Output<String> endpoint;

    /**
     * @return A custom endpoint for the SNS API. Leave empty to use the default AWS endpoint.
     * 
     */
    public Optional<Output<String>> endpoint() {
        return Optional.ofNullable(this.endpoint);
    }

    /**
     * The entity ID used for regulatory registration, where required.
     * 
     */
    @Import(name="entityId")
    private @Nullable Output<String> entityId;

    /**
     * @return The entity ID used for regulatory registration, where required.
     * 
     */
    public Optional<Output<String>> entityId() {
        return Optional.ofNullable(this.entityId);
    }

    /**
     * The external ID used when assuming the IAM role. Required when the authentication type is &#39;assumeRole&#39;.
     * 
     */
    @Import(name="externalId")
    private @Nullable Output<String> externalId;

    /**
     * @return The external ID used when assuming the IAM role. Required when the authentication type is &#39;assumeRole&#39;.
     * 
     */
    public Optional<Output<String>> externalId() {
        return Optional.ofNullable(this.externalId);
    }

    /**
     * A custom name for your connector.
     * 
     */
    @Import(name="name")
    private @Nullable Output<String> name;

    /**
     * @return A custom name for your connector.
     * 
     */
    public Optional<Output<String>> name() {
        return Optional.ofNullable(this.name);
    }

    /**
     * The phone number that text messages are sent from.
     * 
     */
    @Import(name="originationNumber")
    private @Nullable Output<String> originationNumber;

    /**
     * @return The phone number that text messages are sent from.
     * 
     */
    public Optional<Output<String>> originationNumber() {
        return Optional.ofNullable(this.originationNumber);
    }

    /**
     * The ID of the Descope project that the connector belongs to. Changing this value will require the resource to be deleted and recreated.
     * 
     */
    @Import(name="projectId")
    private @Nullable Output<String> projectId;

    /**
     * @return The ID of the Descope project that the connector belongs to. Changing this value will require the resource to be deleted and recreated.
     * 
     */
    public Optional<Output<String>> projectId() {
        return Optional.ofNullable(this.projectId);
    }

    /**
     * The AWS region the SNS service is configured in.
     * 
     */
    @Import(name="region")
    private @Nullable Output<String> region;

    /**
     * @return The AWS region the SNS service is configured in.
     * 
     */
    public Optional<Output<String>> region() {
        return Optional.ofNullable(this.region);
    }

    /**
     * The ARN of the IAM role to assume. Required when the authentication type is &#39;assumeRole&#39;.
     * 
     */
    @Import(name="roleArn")
    private @Nullable Output<String> roleArn;

    /**
     * @return The ARN of the IAM role to assume. Required when the authentication type is &#39;assumeRole&#39;.
     * 
     */
    public Optional<Output<String>> roleArn() {
        return Optional.ofNullable(this.roleArn);
    }

    /**
     * The AWS secret access key. Required when the authentication type is &#39;credentials&#39;.
     * 
     */
    @Import(name="secretAccessKey")
    private @Nullable Output<String> secretAccessKey;

    /**
     * @return The AWS secret access key. Required when the authentication type is &#39;credentials&#39;.
     * 
     */
    public Optional<Output<String>> secretAccessKey() {
        return Optional.ofNullable(this.secretAccessKey);
    }

    /**
     * The sender ID shown as the origin of the text messages, where supported.
     * 
     */
    @Import(name="senderId")
    private @Nullable Output<String> senderId;

    /**
     * @return The sender ID shown as the origin of the text messages, where supported.
     * 
     */
    public Optional<Output<String>> senderId() {
        return Optional.ofNullable(this.senderId);
    }

    /**
     * The template ID used for regulatory registration, where required.
     * 
     */
    @Import(name="templateId")
    private @Nullable Output<String> templateId;

    /**
     * @return The template ID used for regulatory registration, where required.
     * 
     */
    public Optional<Output<String>> templateId() {
        return Optional.ofNullable(this.templateId);
    }

    private SnsConnectorState() {}

    private SnsConnectorState(SnsConnectorState $) {
        this.accessKeyId = $.accessKeyId;
        this.authType = $.authType;
        this.description = $.description;
        this.endpoint = $.endpoint;
        this.entityId = $.entityId;
        this.externalId = $.externalId;
        this.name = $.name;
        this.originationNumber = $.originationNumber;
        this.projectId = $.projectId;
        this.region = $.region;
        this.roleArn = $.roleArn;
        this.secretAccessKey = $.secretAccessKey;
        this.senderId = $.senderId;
        this.templateId = $.templateId;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(SnsConnectorState defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private SnsConnectorState $;

        public Builder() {
            $ = new SnsConnectorState();
        }

        public Builder(SnsConnectorState defaults) {
            $ = new SnsConnectorState(Objects.requireNonNull(defaults));
        }

        /**
         * @param accessKeyId The AWS access key ID. Required when the authentication type is &#39;credentials&#39;.
         * 
         * @return builder
         * 
         */
        public Builder accessKeyId(@Nullable Output<String> accessKeyId) {
            $.accessKeyId = accessKeyId;
            return this;
        }

        /**
         * @param accessKeyId The AWS access key ID. Required when the authentication type is &#39;credentials&#39;.
         * 
         * @return builder
         * 
         */
        public Builder accessKeyId(String accessKeyId) {
            return accessKeyId(Output.of(accessKeyId));
        }

        /**
         * @param authType How to authenticate with AWS: using static credentials or by assuming an IAM role.
         * 
         * @return builder
         * 
         */
        public Builder authType(@Nullable Output<String> authType) {
            $.authType = authType;
            return this;
        }

        /**
         * @param authType How to authenticate with AWS: using static credentials or by assuming an IAM role.
         * 
         * @return builder
         * 
         */
        public Builder authType(String authType) {
            return authType(Output.of(authType));
        }

        /**
         * @param description A description of what your connector is used for.
         * 
         * @return builder
         * 
         */
        public Builder description(@Nullable Output<String> description) {
            $.description = description;
            return this;
        }

        /**
         * @param description A description of what your connector is used for.
         * 
         * @return builder
         * 
         */
        public Builder description(String description) {
            return description(Output.of(description));
        }

        /**
         * @param endpoint A custom endpoint for the SNS API. Leave empty to use the default AWS endpoint.
         * 
         * @return builder
         * 
         */
        public Builder endpoint(@Nullable Output<String> endpoint) {
            $.endpoint = endpoint;
            return this;
        }

        /**
         * @param endpoint A custom endpoint for the SNS API. Leave empty to use the default AWS endpoint.
         * 
         * @return builder
         * 
         */
        public Builder endpoint(String endpoint) {
            return endpoint(Output.of(endpoint));
        }

        /**
         * @param entityId The entity ID used for regulatory registration, where required.
         * 
         * @return builder
         * 
         */
        public Builder entityId(@Nullable Output<String> entityId) {
            $.entityId = entityId;
            return this;
        }

        /**
         * @param entityId The entity ID used for regulatory registration, where required.
         * 
         * @return builder
         * 
         */
        public Builder entityId(String entityId) {
            return entityId(Output.of(entityId));
        }

        /**
         * @param externalId The external ID used when assuming the IAM role. Required when the authentication type is &#39;assumeRole&#39;.
         * 
         * @return builder
         * 
         */
        public Builder externalId(@Nullable Output<String> externalId) {
            $.externalId = externalId;
            return this;
        }

        /**
         * @param externalId The external ID used when assuming the IAM role. Required when the authentication type is &#39;assumeRole&#39;.
         * 
         * @return builder
         * 
         */
        public Builder externalId(String externalId) {
            return externalId(Output.of(externalId));
        }

        /**
         * @param name A custom name for your connector.
         * 
         * @return builder
         * 
         */
        public Builder name(@Nullable Output<String> name) {
            $.name = name;
            return this;
        }

        /**
         * @param name A custom name for your connector.
         * 
         * @return builder
         * 
         */
        public Builder name(String name) {
            return name(Output.of(name));
        }

        /**
         * @param originationNumber The phone number that text messages are sent from.
         * 
         * @return builder
         * 
         */
        public Builder originationNumber(@Nullable Output<String> originationNumber) {
            $.originationNumber = originationNumber;
            return this;
        }

        /**
         * @param originationNumber The phone number that text messages are sent from.
         * 
         * @return builder
         * 
         */
        public Builder originationNumber(String originationNumber) {
            return originationNumber(Output.of(originationNumber));
        }

        /**
         * @param projectId The ID of the Descope project that the connector belongs to. Changing this value will require the resource to be deleted and recreated.
         * 
         * @return builder
         * 
         */
        public Builder projectId(@Nullable Output<String> projectId) {
            $.projectId = projectId;
            return this;
        }

        /**
         * @param projectId The ID of the Descope project that the connector belongs to. Changing this value will require the resource to be deleted and recreated.
         * 
         * @return builder
         * 
         */
        public Builder projectId(String projectId) {
            return projectId(Output.of(projectId));
        }

        /**
         * @param region The AWS region the SNS service is configured in.
         * 
         * @return builder
         * 
         */
        public Builder region(@Nullable Output<String> region) {
            $.region = region;
            return this;
        }

        /**
         * @param region The AWS region the SNS service is configured in.
         * 
         * @return builder
         * 
         */
        public Builder region(String region) {
            return region(Output.of(region));
        }

        /**
         * @param roleArn The ARN of the IAM role to assume. Required when the authentication type is &#39;assumeRole&#39;.
         * 
         * @return builder
         * 
         */
        public Builder roleArn(@Nullable Output<String> roleArn) {
            $.roleArn = roleArn;
            return this;
        }

        /**
         * @param roleArn The ARN of the IAM role to assume. Required when the authentication type is &#39;assumeRole&#39;.
         * 
         * @return builder
         * 
         */
        public Builder roleArn(String roleArn) {
            return roleArn(Output.of(roleArn));
        }

        /**
         * @param secretAccessKey The AWS secret access key. Required when the authentication type is &#39;credentials&#39;.
         * 
         * @return builder
         * 
         */
        public Builder secretAccessKey(@Nullable Output<String> secretAccessKey) {
            $.secretAccessKey = secretAccessKey;
            return this;
        }

        /**
         * @param secretAccessKey The AWS secret access key. Required when the authentication type is &#39;credentials&#39;.
         * 
         * @return builder
         * 
         */
        public Builder secretAccessKey(String secretAccessKey) {
            return secretAccessKey(Output.of(secretAccessKey));
        }

        /**
         * @param senderId The sender ID shown as the origin of the text messages, where supported.
         * 
         * @return builder
         * 
         */
        public Builder senderId(@Nullable Output<String> senderId) {
            $.senderId = senderId;
            return this;
        }

        /**
         * @param senderId The sender ID shown as the origin of the text messages, where supported.
         * 
         * @return builder
         * 
         */
        public Builder senderId(String senderId) {
            return senderId(Output.of(senderId));
        }

        /**
         * @param templateId The template ID used for regulatory registration, where required.
         * 
         * @return builder
         * 
         */
        public Builder templateId(@Nullable Output<String> templateId) {
            $.templateId = templateId;
            return this;
        }

        /**
         * @param templateId The template ID used for regulatory registration, where required.
         * 
         * @return builder
         * 
         */
        public Builder templateId(String templateId) {
            return templateId(Output.of(templateId));
        }

        public SnsConnectorState build() {
            return $;
        }
    }

}
