// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Descope.Pulumi.Descope.Inputs
{

    public sealed class ProjectAuthenticationOtpEmailServiceGetArgs : global::Pulumi.ResourceArgs
    {
        [Input("connector", required: true)]
        public Input<string> Connector { get; set; } = null!;

        [Input("templates")]
        private InputList<Inputs.ProjectAuthenticationOtpEmailServiceTemplateGetArgs>? _templates;
        public InputList<Inputs.ProjectAuthenticationOtpEmailServiceTemplateGetArgs> Templates
        {
            get => _templates ?? (_templates = new InputList<Inputs.ProjectAuthenticationOtpEmailServiceTemplateGetArgs>());
            set => _templates = value;
        }

        public ProjectAuthenticationOtpEmailServiceGetArgs()
        {
        }
        public static new ProjectAuthenticationOtpEmailServiceGetArgs Empty => new ProjectAuthenticationOtpEmailServiceGetArgs();
    }
}
