// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Descope.Pulumi.Descope.Inputs
{

    public sealed class ProjectApplicationsWsfedApplicationGroupsMappingRoleGetArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// The identifier of the role.
        /// </summary>
        [Input("id", required: true)]
        public Input<string> Id { get; set; } = null!;

        /// <summary>
        /// The name of the role.
        /// </summary>
        [Input("name", required: true)]
        public Input<string> Name { get; set; } = null!;

        public ProjectApplicationsWsfedApplicationGroupsMappingRoleGetArgs()
        {
        }
        public static new ProjectApplicationsWsfedApplicationGroupsMappingRoleGetArgs Empty => new ProjectApplicationsWsfedApplicationGroupsMappingRoleGetArgs();
    }
}
