// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Descope.Pulumi.Descope.Inputs
{

    public sealed class ProjectApplicationsSamlApplicationGetArgs : global::Pulumi.ResourceArgs
    {
        [Input("acsAllowedCallbackUrls")]
        private InputList<string>? _acsAllowedCallbackUrls;

        /// <summary>
        /// A list of allowed ACS callback URLS. This configuration is used when the default ACS URL value is unreachable. Supports wildcards.
        /// </summary>
        public InputList<string> AcsAllowedCallbackUrls
        {
            get => _acsAllowedCallbackUrls ?? (_acsAllowedCallbackUrls = new InputList<string>());
            set => _acsAllowedCallbackUrls = value;
        }

        [Input("attributeMappings")]
        private InputList<Inputs.ProjectApplicationsSamlApplicationAttributeMappingGetArgs>? _attributeMappings;

        /// <summary>
        /// The `AttributeMapping` object. Read the description below.
        /// </summary>
        public InputList<Inputs.ProjectApplicationsSamlApplicationAttributeMappingGetArgs> AttributeMappings
        {
            get => _attributeMappings ?? (_attributeMappings = new InputList<Inputs.ProjectApplicationsSamlApplicationAttributeMappingGetArgs>());
            set => _attributeMappings = value;
        }

        /// <summary>
        /// The default relay state. When using IdP-initiated authentication, this value may be used as a URL to a resource in the Service Provider.
        /// </summary>
        [Input("defaultRelayState")]
        public Input<string>? DefaultRelayState { get; set; }

        /// <summary>
        /// A description for the SAML application.
        /// </summary>
        [Input("description")]
        public Input<string>? Description { get; set; }

        /// <summary>
        /// Whether the application should be enabled or disabled.
        /// </summary>
        [Input("disabled")]
        public Input<bool>? Disabled { get; set; }

        /// <summary>
        /// The `DynamicConfiguration` object. Read the description below.
        /// </summary>
        [Input("dynamicConfiguration")]
        public Input<Inputs.ProjectApplicationsSamlApplicationDynamicConfigurationGetArgs>? DynamicConfiguration { get; set; }

        /// <summary>
        /// This configuration overrides the default behavior of the SSO application and forces the user to authenticate via the Descope flow, regardless of the SP's request.
        /// </summary>
        [Input("forceAuthentication")]
        public Input<bool>? ForceAuthentication { get; set; }

        /// <summary>
        /// An optional identifier for the SAML application.
        /// </summary>
        [Input("id")]
        public Input<string>? Id { get; set; }

        /// <summary>
        /// The Flow Hosting URL. Read more about using this parameter with custom domain [here](https://docs.descope.com/sso-integrations/applications/saml-apps).
        /// </summary>
        [Input("loginPageUrl")]
        public Input<string>? LoginPageUrl { get; set; }

        /// <summary>
        /// A logo for the SAML application. Should be a hosted image URL.
        /// </summary>
        [Input("logo")]
        public Input<string>? Logo { get; set; }

        /// <summary>
        /// The `ManualConfiguration` object. Read the description below.
        /// </summary>
        [Input("manualConfiguration")]
        public Input<Inputs.ProjectApplicationsSamlApplicationManualConfigurationGetArgs>? ManualConfiguration { get; set; }

        /// <summary>
        /// A name for the SAML application.
        /// </summary>
        [Input("name", required: true)]
        public Input<string> Name { get; set; } = null!;

        /// <summary>
        /// The subject name id format. Choose one of "", "urn:oasis:names:tc:SAML:1.1:nameid-format:unspecified", "urn:oasis:names:tc:SAML:1.1:nameid-format:emailAddress", "urn:oasis:names:tc:SAML:2.0:nameid-format:persistent", "urn:oasis:names:tc:SAML:2.0:nameid-format:transient". Read more about this configuration [here](https://docs.descope.com/sso-integrations/applications/saml-apps).
        /// </summary>
        [Input("subjectNameIdFormat")]
        public Input<string>? SubjectNameIdFormat { get; set; }

        /// <summary>
        /// The subject name id type. Choose one of "", "email", "phone". Read more about this configuration [here](https://docs.descope.com/sso-integrations/applications/saml-apps).
        /// </summary>
        [Input("subjectNameIdType")]
        public Input<string>? SubjectNameIdType { get; set; }

        public ProjectApplicationsSamlApplicationGetArgs()
        {
        }
        public static new ProjectApplicationsSamlApplicationGetArgs Empty => new ProjectApplicationsSamlApplicationGetArgs();
    }
}
