template: external-bridged-provider
organization: descope
provider: descope
env:
    NODE_AUTH_TOKEN: ${{ secrets.CI_NPM_REGISTRY }}
    NPM_TOKEN: ${{ secrets.CI_NPM_REGISTRY }}
    NUGET_PUBLISH_KEY: ${{ secrets.NUGET_ORG_KEY }}
    PYPI_API_TOKEN: ${{ secrets.PYPI_TOKEN }}
    DESCOPE_MANAGEMENT_KEY: ${{ secrets.DESCOPE_MANAGEMENT_KEY }}
    DESCOPE_PROJECT_ID: ${{ secrets.DESCOPE_PROJECT_ID }}
providerDefaultBranch: main
pulumiConvert: 1
goBuildParallelism: 2
testMasterAndReleaseWorkflows: false
publish:
    cdn: false
    sdk: all,!java
generate-nightly-test-workflow: true
registryDocs: true
publishRegistry: false
plugins:
    - name: terraform
      version: "1.0.16"
      kind: converter
autoMergeProviderUpgrades: true
major-version: 1
