// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Descope.Pulumi.Descope
{
    /// <summary>
    /// Manages the project-level OAuth authentication settings. This is a singleton resource, and its id is always the project ID. Individual OAuth providers are managed with the descope.OauthProvider resource.
    /// </summary>
    [DescopeResourceType("descope:index/oauthSettings:OauthSettings")]
    public partial class OauthSettings : global::Pulumi.CustomResource
    {
        /// <summary>
        /// Setting this to `True` will disallow using OAuth authentication directly via API and SDK calls. Note that this does not affect authentication flows that are configured to use OAuth.
        /// </summary>
        [Output("disabled")]
        public Output<bool> Disabled { get; private set; } = null!;

        /// <summary>
        /// The ID of the project that these settings belong to. Changing this value will require the resource to be deleted and recreated.
        /// </summary>
        [Output("projectId")]
        public Output<string> ProjectId { get; private set; } = null!;


        /// <summary>
        /// Create a OauthSettings resource with the given unique name, arguments, and options.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resource</param>
        /// <param name="args">The arguments used to populate this resource's properties</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public OauthSettings(string name, OauthSettingsArgs args, CustomResourceOptions? options = null)
            : base("descope:index/oauthSettings:OauthSettings", name, args ?? new OauthSettingsArgs(), MakeResourceOptions(options, ""))
        {
        }

        private OauthSettings(string name, Input<string> id, OauthSettingsState? state = null, CustomResourceOptions? options = null)
            : base("descope:index/oauthSettings:OauthSettings", name, state, MakeResourceOptions(options, id))
        {
        }

        private static CustomResourceOptions MakeResourceOptions(CustomResourceOptions? options, Input<string>? id)
        {
            var defaultOptions = new CustomResourceOptions
            {
                Version = Utilities.Version,
                PluginDownloadURL = "github://api.github.com/descope",
            };
            var merged = CustomResourceOptions.Merge(defaultOptions, options);
            // Override the ID if one was specified for consistency with other language SDKs.
            merged.Id = id ?? merged.Id;
            return merged;
        }
        /// <summary>
        /// Get an existing OauthSettings resource's state with the given name, ID, and optional extra
        /// properties used to qualify the lookup.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resulting resource.</param>
        /// <param name="id">The unique provider ID of the resource to lookup.</param>
        /// <param name="state">Any extra arguments used during the lookup.</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public static OauthSettings Get(string name, Input<string> id, OauthSettingsState? state = null, CustomResourceOptions? options = null)
        {
            return new OauthSettings(name, id, state, options);
        }
    }

    public sealed class OauthSettingsArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// Setting this to `True` will disallow using OAuth authentication directly via API and SDK calls. Note that this does not affect authentication flows that are configured to use OAuth.
        /// </summary>
        [Input("disabled")]
        public Input<bool>? Disabled { get; set; }

        /// <summary>
        /// The ID of the project that these settings belong to. Changing this value will require the resource to be deleted and recreated.
        /// </summary>
        [Input("projectId", required: true)]
        public Input<string> ProjectId { get; set; } = null!;

        public OauthSettingsArgs()
        {
        }
        public static new OauthSettingsArgs Empty => new OauthSettingsArgs();
    }

    public sealed class OauthSettingsState : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// Setting this to `True` will disallow using OAuth authentication directly via API and SDK calls. Note that this does not affect authentication flows that are configured to use OAuth.
        /// </summary>
        [Input("disabled")]
        public Input<bool>? Disabled { get; set; }

        /// <summary>
        /// The ID of the project that these settings belong to. Changing this value will require the resource to be deleted and recreated.
        /// </summary>
        [Input("projectId")]
        public Input<string>? ProjectId { get; set; }

        public OauthSettingsState()
        {
        }
        public static new OauthSettingsState Empty => new OauthSettingsState();
    }
}
