// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Descope.Pulumi.Descope
{
    /// <summary>
    /// Manages a Descope project. A project is the core entity in Descope—its authentication settings, user flows, roles, connectors, applications, and other configuration are managed with the standalone `descope_*` resources that reference the project by ID.
    /// 
    /// This resource manages _project configuration_, not users or tenants. For user management, use the [Descope Management API](https://docs.descope.com/api/openapi) or [SDKs](https://docs.descope.com).
    /// 
    /// For a full reference of all supported connectors, see the [connectors reference](https://docs.descope.com/connectors) in the Descope documentation.
    /// 
    /// ## Example Usage
    /// 
    /// ### Basic Project
    /// 
    /// ```csharp
    /// using System.Collections.Generic;
    /// using System.Linq;
    /// using Pulumi;
    /// using Descope = Descope.Pulumi.Descope;
    /// 
    /// return await Deployment.RunAsync(() =&gt; 
    /// {
    ///     var example = new Descope.Project("example", new()
    ///     {
    ///         Name = "my-app",
    ///         Environment = "production",
    ///         Tags = new[]
    ///         {
    ///             "prod",
    ///             "v2",
    ///         },
    ///     });
    /// 
    /// });
    /// ```
    /// 
    /// ### Authentication Methods
    /// 
    /// Authentication method settings are managed with their own standalone resources, such as
    /// `descope.MagiclinkSettings`, `descope.OtpSettings`,
    /// `descope.PasswordSettings`, and `descope.SsoSettings`:
    /// 
    /// ```csharp
    /// using System.Collections.Generic;
    /// using System.Linq;
    /// using Pulumi;
    /// using Descope = Descope.Pulumi.Descope;
    /// 
    /// return await Deployment.RunAsync(() =&gt; 
    /// {
    ///     var example = new Descope.Project("example", new()
    ///     {
    ///         Name = "my-app",
    ///     });
    /// 
    ///     var exampleMagiclinkSettings = new Descope.MagiclinkSettings("example", new()
    ///     {
    ///         ProjectId = example.Id,
    ///         ExpirationTime = "1 hour",
    ///     });
    /// 
    ///     var examplePasswordSettings = new Descope.PasswordSettings("example", new()
    ///     {
    ///         ProjectId = example.Id,
    ///         Lock = true,
    ///         LockAttempts = 5,
    ///         MinLength = 12,
    ///     });
    /// 
    /// });
    /// ```
    /// 
    /// ### Roles and Permissions (RBAC)
    /// 
    /// Roles and permissions are managed as standalone resources that reference the project by ID:
    /// 
    /// ```csharp
    /// using System.Collections.Generic;
    /// using System.Linq;
    /// using Pulumi;
    /// using Descope = Descope.Pulumi.Descope;
    /// 
    /// return await Deployment.RunAsync(() =&gt; 
    /// {
    ///     var example = new Descope.Project("example", new()
    ///     {
    ///         Name = "my-app",
    ///     });
    /// 
    ///     var readData = new Descope.Permission("read_data", new()
    ///     {
    ///         ProjectId = example.Id,
    ///         Name = "read:data",
    ///         Description = "Read access to application data",
    ///     });
    /// 
    ///     var writeData = new Descope.Permission("write_data", new()
    ///     {
    ///         ProjectId = example.Id,
    ///         Name = "write:data",
    ///         Description = "Write access to application data",
    ///     });
    /// 
    ///     var adminPanel = new Descope.Permission("admin_panel", new()
    ///     {
    ///         ProjectId = example.Id,
    ///         Name = "admin:panel",
    ///         Description = "Access to the admin panel",
    ///     });
    /// 
    ///     var viewer = new Descope.Role("viewer", new()
    ///     {
    ///         ProjectId = example.Id,
    ///         Name = "viewer",
    ///         Description = "Can read data",
    ///         Permissions = new[]
    ///         {
    ///             readData.Name,
    ///         },
    ///     });
    /// 
    ///     var editor = new Descope.Role("editor", new()
    ///     {
    ///         ProjectId = example.Id,
    ///         Name = "editor",
    ///         Description = "Can read and write data",
    ///         Permissions = new[]
    ///         {
    ///             readData.Name,
    ///             writeData.Name,
    ///         },
    ///     });
    /// 
    ///     var admin = new Descope.Role("admin", new()
    ///     {
    ///         ProjectId = example.Id,
    ///         Name = "admin",
    ///         Description = "Full access",
    ///         Permissions = new[]
    ///         {
    ///             readData.Name,
    ///             writeData.Name,
    ///             adminPanel.Name,
    ///         },
    ///     });
    /// 
    /// });
    /// ```
    /// 
    /// ### Connectors
    /// 
    /// Integrate with third-party services using standalone per-type connector resources:
    /// 
    /// ```csharp
    /// using System.Collections.Generic;
    /// using System.Linq;
    /// using Pulumi;
    /// using Descope = Descope.Pulumi.Descope;
    /// 
    /// return await Deployment.RunAsync(() =&gt; 
    /// {
    ///     var example = new Descope.Project("example", new()
    ///     {
    ///         Name = "my-app",
    ///     });
    /// 
    ///     // Generic HTTP webhook with bearer token auth
    ///     var eligibility = new Descope.HttpConnector("eligibility", new()
    ///     {
    ///         ProjectId = example.Id,
    ///         Name = "User Eligibility Check",
    ///         Description = "Checks if a new user is allowed to register",
    ///         BaseUrl = "https://api.example.com",
    ///         Authentication = new Descope.Inputs.HttpConnectorAuthenticationArgs
    ///         {
    ///             BearerToken = webhookSecret,
    ///         },
    ///     });
    /// 
    ///     // SendGrid for email delivery
    ///     var email = new Descope.SendgridConnector("email", new()
    ///     {
    ///         ProjectId = example.Id,
    ///         Name = "Transactional Email",
    ///         SenderEmail = "noreply@example.com",
    ///         SenderName = "My App",
    ///         ApiKey = sendgridApiKey,
    ///     });
    /// 
    ///     // Twilio for SMS OTP
    ///     var sms = new Descope.TwilioCoreConnector("sms", new()
    ///     {
    ///         ProjectId = example.Id,
    ///         Name = "SMS OTP",
    ///         AccountSid = twilioAccountSid,
    ///         FromPhone = "+15551234567",
    ///         AuthToken = twilioAuthToken,
    ///     });
    /// 
    /// });
    /// ```
    /// 
    /// ### Project and Session Settings
    /// 
    /// General project settings, session behavior, and user invitations are managed with the
    /// standalone `descope.ProjectSettings`,
    /// `descope.SessionSettings`, and
    /// `descope.InviteSettings` resources:
    /// 
    /// ```csharp
    /// using System.Collections.Generic;
    /// using System.Linq;
    /// using Pulumi;
    /// using Descope = Descope.Pulumi.Descope;
    /// 
    /// return await Deployment.RunAsync(() =&gt; 
    /// {
    ///     var example = new Descope.Project("example", new()
    ///     {
    ///         Name = "my-app",
    ///     });
    /// 
    ///     var exampleProjectSettings = new Descope.ProjectSettings("example", new()
    ///     {
    ///         ProjectId = example.Id,
    ///         AppUrl = "https://app.example.com",
    ///         ApprovedDomains = new[]
    ///         {
    ///             "example.com",
    ///             "app.example.com",
    ///         },
    ///     });
    /// 
    ///     var exampleSessionSettings = new Descope.SessionSettings("example", new()
    ///     {
    ///         ProjectId = example.Id,
    ///         RefreshTokenExpiration = "3 weeks",
    ///         SessionTokenExpiration = "15 minutes",
    ///         RefreshTokenRotation = true,
    ///         EnableInactivity = true,
    ///         InactivityTime = "30 minutes",
    ///     });
    /// 
    ///     var exampleInviteSettings = new Descope.InviteSettings("example", new()
    ///     {
    ///         ProjectId = example.Id,
    ///         RequireInvitation = true,
    ///         InviteUrl = "https://app.example.com/invite",
    ///     });
    /// 
    /// });
    /// ```
    /// 
    /// ### Federated Applications
    /// 
    /// Federated (SSO IdP) applications and their app-scoped roles and permissions are managed
    /// with the standalone `descope.OidcApp`, `descope.SamlApp`, `descope.WsfedApp`,
    /// `descope.AppRole`, and `descope.AppPermission` resources that reference the project by ID:
    /// 
    /// ```csharp
    /// using System.Collections.Generic;
    /// using System.Linq;
    /// using Pulumi;
    /// using Descope = Descope.Pulumi.Descope;
    /// 
    /// return await Deployment.RunAsync(() =&gt; 
    /// {
    ///     var example = new Descope.Project("example", new()
    ///     {
    ///         Name = "my-app",
    ///     });
    /// 
    ///     var web = new Descope.OidcApp("web", new()
    ///     {
    ///         ProjectId = example.Id,
    ///         Name = "My Web App",
    ///         Description = "Primary web application",
    ///         LoginPageUrl = "https://app.example.com/login",
    ///     });
    /// 
    ///     var readReports = new Descope.AppPermission("read_reports", new()
    ///     {
    ///         ProjectId = example.Id,
    ///         AppId = web.OidcAppId,
    ///         Name = "read:reports",
    ///     });
    /// 
    ///     var analyst = new Descope.AppRole("analyst", new()
    ///     {
    ///         ProjectId = example.Id,
    ///         AppId = web.OidcAppId,
    ///         Name = "analyst",
    ///         PermissionIds = new[]
    ///         {
    ///             readReports.Id,
    ///         },
    ///     });
    /// 
    /// });
    /// ```
    /// 
    /// ### JWT Templates
    /// 
    /// JWT templates are managed with the standalone `descope.JwtTemplate` resource that
    /// references the project by ID:
    /// 
    /// ```csharp
    /// using System.Collections.Generic;
    /// using System.Linq;
    /// using System.Text.Json;
    /// using Pulumi;
    /// using Descope = Descope.Pulumi.Descope;
    /// 
    /// return await Deployment.RunAsync(() =&gt; 
    /// {
    ///     var example = new Descope.Project("example", new()
    ///     {
    ///         Name = "my-app",
    ///     });
    /// 
    ///     var appClaims = new Descope.JwtTemplate("app_claims", new()
    ///     {
    ///         ProjectId = example.Id,
    ///         Name = "app-claims",
    ///         Description = "Adds subscription tier and org context to user JWTs",
    ///         Type = "user",
    ///         Template = JsonSerializer.Serialize(new Dictionary&lt;string, object?&gt;
    ///         {
    ///             ["tier"] = "@user.customAttributes.subscriptionTier",
    ///             ["org_id"] = "@user.tenants[0].tenantId",
    ///         }),
    ///         ExcludePermissionClaim = true,
    ///         AddJtiClaim = true,
    ///         OverrideSubjectClaim = true,
    ///     });
    /// 
    /// });
    /// ```
    /// 
    /// ### SSO Settings
    /// 
    /// Global settings for Single Sign-On across tenants are managed with the standalone
    /// `descope.SsoSettings` resource:
    /// 
    /// ```csharp
    /// using System.Collections.Generic;
    /// using System.Linq;
    /// using Pulumi;
    /// using Descope = Descope.Pulumi.Descope;
    /// 
    /// return await Deployment.RunAsync(() =&gt; 
    /// {
    ///     var example = new Descope.Project("example", new()
    ///     {
    ///         Name = "my-app",
    ///     });
    /// 
    ///     var exampleSsoSettings = new Descope.SsoSettings("example", new()
    ///     {
    ///         ProjectId = example.Id,
    ///         MergeUsers = true,
    ///         AllowOverrideRoles = true,
    ///         MandatoryUserAttributes = new[]
    ///         {
    ///             new Descope.Inputs.SsoSettingsMandatoryUserAttributeArgs
    ///             {
    ///                 Id = "email",
    ///             },
    ///             new Descope.Inputs.SsoSettingsMandatoryUserAttributeArgs
    ///             {
    ///                 Id = "name",
    ///             },
    ///             new Descope.Inputs.SsoSettingsMandatoryUserAttributeArgs
    ///             {
    ///                 Id = "department",
    ///                 Custom = true,
    ///             },
    ///         },
    ///         SsoSuiteSettings = new Descope.Inputs.SsoSettingsSsoSuiteSettingsArgs
    ///         {
    ///             StyleId = "my-brand-style",
    ///             HideScim = false,
    ///             HideSaml = false,
    ///             HideOidc = false,
    ///         },
    ///     });
    /// 
    /// });
    /// ```
    /// </summary>
    [DescopeResourceType("descope:index/project:Project")]
    public partial class Project : global::Pulumi.CustomResource
    {
        /// <summary>
        /// Protects the project from being accidentally destroyed. When this attribute isn't set, deletion protection is enabled automatically for every project, whatever its `Environment` attribute is set to. To destroy a protected project, set this attribute to `False` and apply the change first. Note that this only guards operations performed through this provider, so removing the resource from the Terraform state is not prevented.
        /// </summary>
        [Output("deletionProtection")]
        public Output<bool?> DeletionProtection { get; private set; } = null!;

        /// <summary>
        /// This can be set to `Production` to mark production projects, otherwise this should be left unset for development or staging projects.
        /// </summary>
        [Output("environment")]
        public Output<string> Environment { get; private set; } = null!;

        /// <summary>
        /// The name of the Descope project.
        /// </summary>
        [Output("name")]
        public Output<string> Name { get; private set; } = null!;

        /// <summary>
        /// Descriptive tags for your Descope project. Each tag must be no more than 50 characters long.
        /// </summary>
        [Output("tags")]
        public Output<ImmutableArray<string>> Tags { get; private set; } = null!;


        /// <summary>
        /// Create a Project resource with the given unique name, arguments, and options.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resource</param>
        /// <param name="args">The arguments used to populate this resource's properties</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public Project(string name, ProjectArgs? args = null, CustomResourceOptions? options = null)
            : base("descope:index/project:Project", name, args ?? new ProjectArgs(), MakeResourceOptions(options, ""))
        {
        }

        private Project(string name, Input<string> id, ProjectState? state = null, CustomResourceOptions? options = null)
            : base("descope:index/project:Project", name, state, MakeResourceOptions(options, id))
        {
        }

        private static CustomResourceOptions MakeResourceOptions(CustomResourceOptions? options, Input<string>? id)
        {
            var defaultOptions = new CustomResourceOptions
            {
                Version = Utilities.Version,
                PluginDownloadURL = "github://api.github.com/descope",
            };
            var merged = CustomResourceOptions.Merge(defaultOptions, options);
            // Override the ID if one was specified for consistency with other language SDKs.
            merged.Id = id ?? merged.Id;
            return merged;
        }
        /// <summary>
        /// Get an existing Project resource's state with the given name, ID, and optional extra
        /// properties used to qualify the lookup.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resulting resource.</param>
        /// <param name="id">The unique provider ID of the resource to lookup.</param>
        /// <param name="state">Any extra arguments used during the lookup.</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public static Project Get(string name, Input<string> id, ProjectState? state = null, CustomResourceOptions? options = null)
        {
            return new Project(name, id, state, options);
        }
    }

    public sealed class ProjectArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// Protects the project from being accidentally destroyed. When this attribute isn't set, deletion protection is enabled automatically for every project, whatever its `Environment` attribute is set to. To destroy a protected project, set this attribute to `False` and apply the change first. Note that this only guards operations performed through this provider, so removing the resource from the Terraform state is not prevented.
        /// </summary>
        [Input("deletionProtection")]
        public Input<bool>? DeletionProtection { get; set; }

        /// <summary>
        /// This can be set to `Production` to mark production projects, otherwise this should be left unset for development or staging projects.
        /// </summary>
        [Input("environment")]
        public Input<string>? Environment { get; set; }

        /// <summary>
        /// The name of the Descope project.
        /// </summary>
        [Input("name")]
        public Input<string>? Name { get; set; }

        [Input("tags")]
        private InputList<string>? _tags;

        /// <summary>
        /// Descriptive tags for your Descope project. Each tag must be no more than 50 characters long.
        /// </summary>
        public InputList<string> Tags
        {
            get => _tags ?? (_tags = new InputList<string>());
            set => _tags = value;
        }

        public ProjectArgs()
        {
        }
        public static new ProjectArgs Empty => new ProjectArgs();
    }

    public sealed class ProjectState : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// Protects the project from being accidentally destroyed. When this attribute isn't set, deletion protection is enabled automatically for every project, whatever its `Environment` attribute is set to. To destroy a protected project, set this attribute to `False` and apply the change first. Note that this only guards operations performed through this provider, so removing the resource from the Terraform state is not prevented.
        /// </summary>
        [Input("deletionProtection")]
        public Input<bool>? DeletionProtection { get; set; }

        /// <summary>
        /// This can be set to `Production` to mark production projects, otherwise this should be left unset for development or staging projects.
        /// </summary>
        [Input("environment")]
        public Input<string>? Environment { get; set; }

        /// <summary>
        /// The name of the Descope project.
        /// </summary>
        [Input("name")]
        public Input<string>? Name { get; set; }

        [Input("tags")]
        private InputList<string>? _tags;

        /// <summary>
        /// Descriptive tags for your Descope project. Each tag must be no more than 50 characters long.
        /// </summary>
        public InputList<string> Tags
        {
            get => _tags ?? (_tags = new InputList<string>());
            set => _tags = value;
        }

        public ProjectState()
        {
        }
        public static new ProjectState Empty => new ProjectState();
    }
}
