// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Descope.Pulumi.Descope
{
    /// <summary>
    /// Manages a SMTP connector and its configuration in a Descope project. A general purpose SMTP connector for sending emails through your own mail server.
    /// </summary>
    [DescopeResourceType("descope:index/smtpConnector:SmtpConnector")]
    public partial class SmtpConnector : global::Pulumi.CustomResource
    {
        /// <summary>
        /// The authentication method to use when connecting to the SMTP server.
        /// </summary>
        [Output("authMethod")]
        public Output<string> AuthMethod { get; private set; } = null!;

        /// <summary>
        /// A description of what your connector is used for.
        /// </summary>
        [Output("description")]
        public Output<string> Description { get; private set; } = null!;

        /// <summary>
        /// The hostname or IP address of the SMTP server.
        /// </summary>
        [Output("host")]
        public Output<string> Host { get; private set; } = null!;

        /// <summary>
        /// A custom name for your connector.
        /// </summary>
        [Output("name")]
        public Output<string> Name { get; private set; } = null!;

        /// <summary>
        /// The password used to authenticate with the SMTP server.
        /// </summary>
        [Output("password")]
        public Output<string> Password { get; private set; } = null!;

        /// <summary>
        /// The port the SMTP server listens on.
        /// </summary>
        [Output("port")]
        public Output<double> Port { get; private set; } = null!;

        /// <summary>
        /// The ID of the Descope project that the connector belongs to. Changing this value will require the resource to be deleted and recreated.
        /// </summary>
        [Output("projectId")]
        public Output<string> ProjectId { get; private set; } = null!;

        /// <summary>
        /// The email address that emails are sent from. Make sure it is properly registered with your server.
        /// </summary>
        [Output("senderEmail")]
        public Output<string> SenderEmail { get; private set; } = null!;

        /// <summary>
        /// The name shown as the sender of the emails.
        /// </summary>
        [Output("senderName")]
        public Output<string> SenderName { get; private set; } = null!;

        /// <summary>
        /// Whether the connector should send all requests from specific static IPs.
        /// </summary>
        [Output("useStaticIps")]
        public Output<bool> UseStaticIps { get; private set; } = null!;

        /// <summary>
        /// The username used to authenticate with the SMTP server.
        /// </summary>
        [Output("username")]
        public Output<string> Username { get; private set; } = null!;


        /// <summary>
        /// Create a SmtpConnector resource with the given unique name, arguments, and options.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resource</param>
        /// <param name="args">The arguments used to populate this resource's properties</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public SmtpConnector(string name, SmtpConnectorArgs args, CustomResourceOptions? options = null)
            : base("descope:index/smtpConnector:SmtpConnector", name, args ?? new SmtpConnectorArgs(), MakeResourceOptions(options, ""))
        {
        }

        private SmtpConnector(string name, Input<string> id, SmtpConnectorState? state = null, CustomResourceOptions? options = null)
            : base("descope:index/smtpConnector:SmtpConnector", name, state, MakeResourceOptions(options, id))
        {
        }

        private static CustomResourceOptions MakeResourceOptions(CustomResourceOptions? options, Input<string>? id)
        {
            var defaultOptions = new CustomResourceOptions
            {
                Version = Utilities.Version,
                PluginDownloadURL = "github://api.github.com/descope",
                AdditionalSecretOutputs =
                {
                    "password",
                },
            };
            var merged = CustomResourceOptions.Merge(defaultOptions, options);
            // Override the ID if one was specified for consistency with other language SDKs.
            merged.Id = id ?? merged.Id;
            return merged;
        }
        /// <summary>
        /// Get an existing SmtpConnector resource's state with the given name, ID, and optional extra
        /// properties used to qualify the lookup.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resulting resource.</param>
        /// <param name="id">The unique provider ID of the resource to lookup.</param>
        /// <param name="state">Any extra arguments used during the lookup.</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public static SmtpConnector Get(string name, Input<string> id, SmtpConnectorState? state = null, CustomResourceOptions? options = null)
        {
            return new SmtpConnector(name, id, state, options);
        }
    }

    public sealed class SmtpConnectorArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// The authentication method to use when connecting to the SMTP server.
        /// </summary>
        [Input("authMethod")]
        public Input<string>? AuthMethod { get; set; }

        /// <summary>
        /// A description of what your connector is used for.
        /// </summary>
        [Input("description")]
        public Input<string>? Description { get; set; }

        /// <summary>
        /// The hostname or IP address of the SMTP server.
        /// </summary>
        [Input("host", required: true)]
        public Input<string> Host { get; set; } = null!;

        /// <summary>
        /// A custom name for your connector.
        /// </summary>
        [Input("name")]
        public Input<string>? Name { get; set; }

        [Input("password", required: true)]
        private Input<string>? _password;

        /// <summary>
        /// The password used to authenticate with the SMTP server.
        /// </summary>
        public Input<string>? Password
        {
            get => _password;
            set
            {
                var emptySecret = Output.CreateSecret(0);
                _password = Output.Tuple<Input<string>?, int>(value, emptySecret).Apply(t => t.Item1);
            }
        }

        /// <summary>
        /// The port the SMTP server listens on.
        /// </summary>
        [Input("port")]
        public Input<double>? Port { get; set; }

        /// <summary>
        /// The ID of the Descope project that the connector belongs to. Changing this value will require the resource to be deleted and recreated.
        /// </summary>
        [Input("projectId", required: true)]
        public Input<string> ProjectId { get; set; } = null!;

        /// <summary>
        /// The email address that emails are sent from. Make sure it is properly registered with your server.
        /// </summary>
        [Input("senderEmail", required: true)]
        public Input<string> SenderEmail { get; set; } = null!;

        /// <summary>
        /// The name shown as the sender of the emails.
        /// </summary>
        [Input("senderName")]
        public Input<string>? SenderName { get; set; }

        /// <summary>
        /// Whether the connector should send all requests from specific static IPs.
        /// </summary>
        [Input("useStaticIps")]
        public Input<bool>? UseStaticIps { get; set; }

        /// <summary>
        /// The username used to authenticate with the SMTP server.
        /// </summary>
        [Input("username", required: true)]
        public Input<string> Username { get; set; } = null!;

        public SmtpConnectorArgs()
        {
        }
        public static new SmtpConnectorArgs Empty => new SmtpConnectorArgs();
    }

    public sealed class SmtpConnectorState : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// The authentication method to use when connecting to the SMTP server.
        /// </summary>
        [Input("authMethod")]
        public Input<string>? AuthMethod { get; set; }

        /// <summary>
        /// A description of what your connector is used for.
        /// </summary>
        [Input("description")]
        public Input<string>? Description { get; set; }

        /// <summary>
        /// The hostname or IP address of the SMTP server.
        /// </summary>
        [Input("host")]
        public Input<string>? Host { get; set; }

        /// <summary>
        /// A custom name for your connector.
        /// </summary>
        [Input("name")]
        public Input<string>? Name { get; set; }

        [Input("password")]
        private Input<string>? _password;

        /// <summary>
        /// The password used to authenticate with the SMTP server.
        /// </summary>
        public Input<string>? Password
        {
            get => _password;
            set
            {
                var emptySecret = Output.CreateSecret(0);
                _password = Output.Tuple<Input<string>?, int>(value, emptySecret).Apply(t => t.Item1);
            }
        }

        /// <summary>
        /// The port the SMTP server listens on.
        /// </summary>
        [Input("port")]
        public Input<double>? Port { get; set; }

        /// <summary>
        /// The ID of the Descope project that the connector belongs to. Changing this value will require the resource to be deleted and recreated.
        /// </summary>
        [Input("projectId")]
        public Input<string>? ProjectId { get; set; }

        /// <summary>
        /// The email address that emails are sent from. Make sure it is properly registered with your server.
        /// </summary>
        [Input("senderEmail")]
        public Input<string>? SenderEmail { get; set; }

        /// <summary>
        /// The name shown as the sender of the emails.
        /// </summary>
        [Input("senderName")]
        public Input<string>? SenderName { get; set; }

        /// <summary>
        /// Whether the connector should send all requests from specific static IPs.
        /// </summary>
        [Input("useStaticIps")]
        public Input<bool>? UseStaticIps { get; set; }

        /// <summary>
        /// The username used to authenticate with the SMTP server.
        /// </summary>
        [Input("username")]
        public Input<string>? Username { get; set; }

        public SmtpConnectorState()
        {
        }
        public static new SmtpConnectorState Empty => new SmtpConnectorState();
    }
}
