# coding=utf-8
# *** WARNING: this file was generated by pulumi-language-python. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import builtins as _builtins
import warnings
import sys
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
if sys.version_info >= (3, 11):
    from typing import NotRequired, TypedDict, TypeAlias
else:
    from typing_extensions import NotRequired, TypedDict, TypeAlias
from . import _utilities
from . import outputs
from ._inputs import *

__all__ = ['AwsEventbridgeConnectorArgs', 'AwsEventbridgeConnector']

@pulumi.input_type
class AwsEventbridgeConnectorArgs:
    def __init__(__self__, *,
                 detail_type: pulumi.Input[_builtins.str],
                 event_bus_name: pulumi.Input[_builtins.str],
                 project_id: pulumi.Input[_builtins.str],
                 region: pulumi.Input[_builtins.str],
                 source: pulumi.Input[_builtins.str],
                 access_key_id: pulumi.Input[Optional[_builtins.str]] = None,
                 audit_enabled: pulumi.Input[Optional[_builtins.bool]] = None,
                 audit_filters: pulumi.Input[Optional[Sequence[pulumi.Input['AwsEventbridgeConnectorAuditFilterArgs']]]] = None,
                 auth_type: pulumi.Input[Optional[_builtins.str]] = None,
                 description: pulumi.Input[Optional[_builtins.str]] = None,
                 disabled: pulumi.Input[Optional[_builtins.bool]] = None,
                 external_id: pulumi.Input[Optional[_builtins.str]] = None,
                 mask_pii: pulumi.Input[Optional[_builtins.bool]] = None,
                 name: pulumi.Input[Optional[_builtins.str]] = None,
                 role_arn: pulumi.Input[Optional[_builtins.str]] = None,
                 secret_access_key: pulumi.Input[Optional[_builtins.str]] = None,
                 troubleshoot_log_enabled: pulumi.Input[Optional[_builtins.bool]] = None):
        """
        The set of arguments for constructing a AwsEventbridgeConnector resource.

        :param pulumi.Input[_builtins.str] detail_type: The detail type for the EventBridge event. This is a free-form string used to identify the event type, e.g. `descope.audit.event`.
        :param pulumi.Input[_builtins.str] event_bus_name: The name or ARN of the EventBridge event bus. Use `default` for the default event bus or provide a custom event bus name/ARN.
        :param pulumi.Input[_builtins.str] project_id: The ID of the Descope project that the connector belongs to. Changing this value will require the resource to be deleted and recreated.
        :param pulumi.Input[_builtins.str] region: The AWS EventBridge region, e.g. `us-east-1`.
        :param pulumi.Input[_builtins.str] source: The source of the EventBridge event. This identifies the application or service that is generating the event, e.g. `descope.auth`.
        :param pulumi.Input[_builtins.str] access_key_id: The unique AWS access key ID.
        :param pulumi.Input[_builtins.bool] audit_enabled: Whether to enable streaming of audit events.
        :param pulumi.Input[Sequence[pulumi.Input['AwsEventbridgeConnectorAuditFilterArgs']]] audit_filters: Specify which events will be sent to the external audit service (including tenant selection).
        :param pulumi.Input[_builtins.str] auth_type: The authentication type to use.
        :param pulumi.Input[_builtins.str] description: A description of what your connector is used for.
        :param pulumi.Input[_builtins.bool] disabled: Whether the connector is disabled. This can be used to temporarily stop a connector from executing without fully deleting it.
        :param pulumi.Input[_builtins.str] external_id: The external ID to use when assuming the role.
        :param pulumi.Input[_builtins.bool] mask_pii: Whether to mask personally identifiable information in the logs.
        :param pulumi.Input[_builtins.str] name: A custom name for your connector.
        :param pulumi.Input[_builtins.str] role_arn: The Amazon Resource Name (ARN) of the role to assume.
        :param pulumi.Input[_builtins.str] secret_access_key: The secret AWS access key.
        :param pulumi.Input[_builtins.bool] troubleshoot_log_enabled: Whether to send troubleshooting events.
        """
        pulumi.set(__self__, "detail_type", detail_type)
        pulumi.set(__self__, "event_bus_name", event_bus_name)
        pulumi.set(__self__, "project_id", project_id)
        pulumi.set(__self__, "region", region)
        pulumi.set(__self__, "source", source)
        if access_key_id is not None:
            pulumi.set(__self__, "access_key_id", access_key_id)
        if audit_enabled is not None:
            pulumi.set(__self__, "audit_enabled", audit_enabled)
        if audit_filters is not None:
            pulumi.set(__self__, "audit_filters", audit_filters)
        if auth_type is not None:
            pulumi.set(__self__, "auth_type", auth_type)
        if description is not None:
            pulumi.set(__self__, "description", description)
        if disabled is not None:
            pulumi.set(__self__, "disabled", disabled)
        if external_id is not None:
            pulumi.set(__self__, "external_id", external_id)
        if mask_pii is not None:
            pulumi.set(__self__, "mask_pii", mask_pii)
        if name is not None:
            pulumi.set(__self__, "name", name)
        if role_arn is not None:
            pulumi.set(__self__, "role_arn", role_arn)
        if secret_access_key is not None:
            pulumi.set(__self__, "secret_access_key", secret_access_key)
        if troubleshoot_log_enabled is not None:
            pulumi.set(__self__, "troubleshoot_log_enabled", troubleshoot_log_enabled)

    @_builtins.property
    @pulumi.getter(name="detailType")
    def detail_type(self) -> pulumi.Input[_builtins.str]:
        """
        The detail type for the EventBridge event. This is a free-form string used to identify the event type, e.g. `descope.audit.event`.
        """
        return pulumi.get(self, "detail_type")

    @detail_type.setter
    def detail_type(self, value: pulumi.Input[_builtins.str]):
        pulumi.set(self, "detail_type", value)

    @_builtins.property
    @pulumi.getter(name="eventBusName")
    def event_bus_name(self) -> pulumi.Input[_builtins.str]:
        """
        The name or ARN of the EventBridge event bus. Use `default` for the default event bus or provide a custom event bus name/ARN.
        """
        return pulumi.get(self, "event_bus_name")

    @event_bus_name.setter
    def event_bus_name(self, value: pulumi.Input[_builtins.str]):
        pulumi.set(self, "event_bus_name", value)

    @_builtins.property
    @pulumi.getter(name="projectId")
    def project_id(self) -> pulumi.Input[_builtins.str]:
        """
        The ID of the Descope project that the connector belongs to. Changing this value will require the resource to be deleted and recreated.
        """
        return pulumi.get(self, "project_id")

    @project_id.setter
    def project_id(self, value: pulumi.Input[_builtins.str]):
        pulumi.set(self, "project_id", value)

    @_builtins.property
    @pulumi.getter
    def region(self) -> pulumi.Input[_builtins.str]:
        """
        The AWS EventBridge region, e.g. `us-east-1`.
        """
        return pulumi.get(self, "region")

    @region.setter
    def region(self, value: pulumi.Input[_builtins.str]):
        pulumi.set(self, "region", value)

    @_builtins.property
    @pulumi.getter
    def source(self) -> pulumi.Input[_builtins.str]:
        """
        The source of the EventBridge event. This identifies the application or service that is generating the event, e.g. `descope.auth`.
        """
        return pulumi.get(self, "source")

    @source.setter
    def source(self, value: pulumi.Input[_builtins.str]):
        pulumi.set(self, "source", value)

    @_builtins.property
    @pulumi.getter(name="accessKeyId")
    def access_key_id(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        The unique AWS access key ID.
        """
        return pulumi.get(self, "access_key_id")

    @access_key_id.setter
    def access_key_id(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "access_key_id", value)

    @_builtins.property
    @pulumi.getter(name="auditEnabled")
    def audit_enabled(self) -> pulumi.Input[Optional[_builtins.bool]]:
        """
        Whether to enable streaming of audit events.
        """
        return pulumi.get(self, "audit_enabled")

    @audit_enabled.setter
    def audit_enabled(self, value: pulumi.Input[Optional[_builtins.bool]]):
        pulumi.set(self, "audit_enabled", value)

    @_builtins.property
    @pulumi.getter(name="auditFilters")
    def audit_filters(self) -> pulumi.Input[Optional[Sequence[pulumi.Input['AwsEventbridgeConnectorAuditFilterArgs']]]]:
        """
        Specify which events will be sent to the external audit service (including tenant selection).
        """
        return pulumi.get(self, "audit_filters")

    @audit_filters.setter
    def audit_filters(self, value: pulumi.Input[Optional[Sequence[pulumi.Input['AwsEventbridgeConnectorAuditFilterArgs']]]]):
        pulumi.set(self, "audit_filters", value)

    @_builtins.property
    @pulumi.getter(name="authType")
    def auth_type(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        The authentication type to use.
        """
        return pulumi.get(self, "auth_type")

    @auth_type.setter
    def auth_type(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "auth_type", value)

    @_builtins.property
    @pulumi.getter
    def description(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        A description of what your connector is used for.
        """
        return pulumi.get(self, "description")

    @description.setter
    def description(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "description", value)

    @_builtins.property
    @pulumi.getter
    def disabled(self) -> pulumi.Input[Optional[_builtins.bool]]:
        """
        Whether the connector is disabled. This can be used to temporarily stop a connector from executing without fully deleting it.
        """
        return pulumi.get(self, "disabled")

    @disabled.setter
    def disabled(self, value: pulumi.Input[Optional[_builtins.bool]]):
        pulumi.set(self, "disabled", value)

    @_builtins.property
    @pulumi.getter(name="externalId")
    def external_id(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        The external ID to use when assuming the role.
        """
        return pulumi.get(self, "external_id")

    @external_id.setter
    def external_id(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "external_id", value)

    @_builtins.property
    @pulumi.getter(name="maskPii")
    def mask_pii(self) -> pulumi.Input[Optional[_builtins.bool]]:
        """
        Whether to mask personally identifiable information in the logs.
        """
        return pulumi.get(self, "mask_pii")

    @mask_pii.setter
    def mask_pii(self, value: pulumi.Input[Optional[_builtins.bool]]):
        pulumi.set(self, "mask_pii", value)

    @_builtins.property
    @pulumi.getter
    def name(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        A custom name for your connector.
        """
        return pulumi.get(self, "name")

    @name.setter
    def name(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "name", value)

    @_builtins.property
    @pulumi.getter(name="roleArn")
    def role_arn(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        The Amazon Resource Name (ARN) of the role to assume.
        """
        return pulumi.get(self, "role_arn")

    @role_arn.setter
    def role_arn(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "role_arn", value)

    @_builtins.property
    @pulumi.getter(name="secretAccessKey")
    def secret_access_key(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        The secret AWS access key.
        """
        return pulumi.get(self, "secret_access_key")

    @secret_access_key.setter
    def secret_access_key(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "secret_access_key", value)

    @_builtins.property
    @pulumi.getter(name="troubleshootLogEnabled")
    def troubleshoot_log_enabled(self) -> pulumi.Input[Optional[_builtins.bool]]:
        """
        Whether to send troubleshooting events.
        """
        return pulumi.get(self, "troubleshoot_log_enabled")

    @troubleshoot_log_enabled.setter
    def troubleshoot_log_enabled(self, value: pulumi.Input[Optional[_builtins.bool]]):
        pulumi.set(self, "troubleshoot_log_enabled", value)


@pulumi.input_type
class _AwsEventbridgeConnectorState:
    def __init__(__self__, *,
                 access_key_id: pulumi.Input[Optional[_builtins.str]] = None,
                 audit_enabled: pulumi.Input[Optional[_builtins.bool]] = None,
                 audit_filters: pulumi.Input[Optional[Sequence[pulumi.Input['AwsEventbridgeConnectorAuditFilterArgs']]]] = None,
                 auth_type: pulumi.Input[Optional[_builtins.str]] = None,
                 description: pulumi.Input[Optional[_builtins.str]] = None,
                 detail_type: pulumi.Input[Optional[_builtins.str]] = None,
                 disabled: pulumi.Input[Optional[_builtins.bool]] = None,
                 event_bus_name: pulumi.Input[Optional[_builtins.str]] = None,
                 external_id: pulumi.Input[Optional[_builtins.str]] = None,
                 mask_pii: pulumi.Input[Optional[_builtins.bool]] = None,
                 name: pulumi.Input[Optional[_builtins.str]] = None,
                 project_id: pulumi.Input[Optional[_builtins.str]] = None,
                 region: pulumi.Input[Optional[_builtins.str]] = None,
                 role_arn: pulumi.Input[Optional[_builtins.str]] = None,
                 secret_access_key: pulumi.Input[Optional[_builtins.str]] = None,
                 source: pulumi.Input[Optional[_builtins.str]] = None,
                 troubleshoot_log_enabled: pulumi.Input[Optional[_builtins.bool]] = None):
        """
        Input properties used for looking up and filtering AwsEventbridgeConnector resources.

        :param pulumi.Input[_builtins.str] access_key_id: The unique AWS access key ID.
        :param pulumi.Input[_builtins.bool] audit_enabled: Whether to enable streaming of audit events.
        :param pulumi.Input[Sequence[pulumi.Input['AwsEventbridgeConnectorAuditFilterArgs']]] audit_filters: Specify which events will be sent to the external audit service (including tenant selection).
        :param pulumi.Input[_builtins.str] auth_type: The authentication type to use.
        :param pulumi.Input[_builtins.str] description: A description of what your connector is used for.
        :param pulumi.Input[_builtins.str] detail_type: The detail type for the EventBridge event. This is a free-form string used to identify the event type, e.g. `descope.audit.event`.
        :param pulumi.Input[_builtins.bool] disabled: Whether the connector is disabled. This can be used to temporarily stop a connector from executing without fully deleting it.
        :param pulumi.Input[_builtins.str] event_bus_name: The name or ARN of the EventBridge event bus. Use `default` for the default event bus or provide a custom event bus name/ARN.
        :param pulumi.Input[_builtins.str] external_id: The external ID to use when assuming the role.
        :param pulumi.Input[_builtins.bool] mask_pii: Whether to mask personally identifiable information in the logs.
        :param pulumi.Input[_builtins.str] name: A custom name for your connector.
        :param pulumi.Input[_builtins.str] project_id: The ID of the Descope project that the connector belongs to. Changing this value will require the resource to be deleted and recreated.
        :param pulumi.Input[_builtins.str] region: The AWS EventBridge region, e.g. `us-east-1`.
        :param pulumi.Input[_builtins.str] role_arn: The Amazon Resource Name (ARN) of the role to assume.
        :param pulumi.Input[_builtins.str] secret_access_key: The secret AWS access key.
        :param pulumi.Input[_builtins.str] source: The source of the EventBridge event. This identifies the application or service that is generating the event, e.g. `descope.auth`.
        :param pulumi.Input[_builtins.bool] troubleshoot_log_enabled: Whether to send troubleshooting events.
        """
        if access_key_id is not None:
            pulumi.set(__self__, "access_key_id", access_key_id)
        if audit_enabled is not None:
            pulumi.set(__self__, "audit_enabled", audit_enabled)
        if audit_filters is not None:
            pulumi.set(__self__, "audit_filters", audit_filters)
        if auth_type is not None:
            pulumi.set(__self__, "auth_type", auth_type)
        if description is not None:
            pulumi.set(__self__, "description", description)
        if detail_type is not None:
            pulumi.set(__self__, "detail_type", detail_type)
        if disabled is not None:
            pulumi.set(__self__, "disabled", disabled)
        if event_bus_name is not None:
            pulumi.set(__self__, "event_bus_name", event_bus_name)
        if external_id is not None:
            pulumi.set(__self__, "external_id", external_id)
        if mask_pii is not None:
            pulumi.set(__self__, "mask_pii", mask_pii)
        if name is not None:
            pulumi.set(__self__, "name", name)
        if project_id is not None:
            pulumi.set(__self__, "project_id", project_id)
        if region is not None:
            pulumi.set(__self__, "region", region)
        if role_arn is not None:
            pulumi.set(__self__, "role_arn", role_arn)
        if secret_access_key is not None:
            pulumi.set(__self__, "secret_access_key", secret_access_key)
        if source is not None:
            pulumi.set(__self__, "source", source)
        if troubleshoot_log_enabled is not None:
            pulumi.set(__self__, "troubleshoot_log_enabled", troubleshoot_log_enabled)

    @_builtins.property
    @pulumi.getter(name="accessKeyId")
    def access_key_id(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        The unique AWS access key ID.
        """
        return pulumi.get(self, "access_key_id")

    @access_key_id.setter
    def access_key_id(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "access_key_id", value)

    @_builtins.property
    @pulumi.getter(name="auditEnabled")
    def audit_enabled(self) -> pulumi.Input[Optional[_builtins.bool]]:
        """
        Whether to enable streaming of audit events.
        """
        return pulumi.get(self, "audit_enabled")

    @audit_enabled.setter
    def audit_enabled(self, value: pulumi.Input[Optional[_builtins.bool]]):
        pulumi.set(self, "audit_enabled", value)

    @_builtins.property
    @pulumi.getter(name="auditFilters")
    def audit_filters(self) -> pulumi.Input[Optional[Sequence[pulumi.Input['AwsEventbridgeConnectorAuditFilterArgs']]]]:
        """
        Specify which events will be sent to the external audit service (including tenant selection).
        """
        return pulumi.get(self, "audit_filters")

    @audit_filters.setter
    def audit_filters(self, value: pulumi.Input[Optional[Sequence[pulumi.Input['AwsEventbridgeConnectorAuditFilterArgs']]]]):
        pulumi.set(self, "audit_filters", value)

    @_builtins.property
    @pulumi.getter(name="authType")
    def auth_type(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        The authentication type to use.
        """
        return pulumi.get(self, "auth_type")

    @auth_type.setter
    def auth_type(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "auth_type", value)

    @_builtins.property
    @pulumi.getter
    def description(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        A description of what your connector is used for.
        """
        return pulumi.get(self, "description")

    @description.setter
    def description(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "description", value)

    @_builtins.property
    @pulumi.getter(name="detailType")
    def detail_type(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        The detail type for the EventBridge event. This is a free-form string used to identify the event type, e.g. `descope.audit.event`.
        """
        return pulumi.get(self, "detail_type")

    @detail_type.setter
    def detail_type(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "detail_type", value)

    @_builtins.property
    @pulumi.getter
    def disabled(self) -> pulumi.Input[Optional[_builtins.bool]]:
        """
        Whether the connector is disabled. This can be used to temporarily stop a connector from executing without fully deleting it.
        """
        return pulumi.get(self, "disabled")

    @disabled.setter
    def disabled(self, value: pulumi.Input[Optional[_builtins.bool]]):
        pulumi.set(self, "disabled", value)

    @_builtins.property
    @pulumi.getter(name="eventBusName")
    def event_bus_name(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        The name or ARN of the EventBridge event bus. Use `default` for the default event bus or provide a custom event bus name/ARN.
        """
        return pulumi.get(self, "event_bus_name")

    @event_bus_name.setter
    def event_bus_name(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "event_bus_name", value)

    @_builtins.property
    @pulumi.getter(name="externalId")
    def external_id(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        The external ID to use when assuming the role.
        """
        return pulumi.get(self, "external_id")

    @external_id.setter
    def external_id(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "external_id", value)

    @_builtins.property
    @pulumi.getter(name="maskPii")
    def mask_pii(self) -> pulumi.Input[Optional[_builtins.bool]]:
        """
        Whether to mask personally identifiable information in the logs.
        """
        return pulumi.get(self, "mask_pii")

    @mask_pii.setter
    def mask_pii(self, value: pulumi.Input[Optional[_builtins.bool]]):
        pulumi.set(self, "mask_pii", value)

    @_builtins.property
    @pulumi.getter
    def name(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        A custom name for your connector.
        """
        return pulumi.get(self, "name")

    @name.setter
    def name(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "name", value)

    @_builtins.property
    @pulumi.getter(name="projectId")
    def project_id(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        The ID of the Descope project that the connector belongs to. Changing this value will require the resource to be deleted and recreated.
        """
        return pulumi.get(self, "project_id")

    @project_id.setter
    def project_id(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "project_id", value)

    @_builtins.property
    @pulumi.getter
    def region(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        The AWS EventBridge region, e.g. `us-east-1`.
        """
        return pulumi.get(self, "region")

    @region.setter
    def region(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "region", value)

    @_builtins.property
    @pulumi.getter(name="roleArn")
    def role_arn(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        The Amazon Resource Name (ARN) of the role to assume.
        """
        return pulumi.get(self, "role_arn")

    @role_arn.setter
    def role_arn(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "role_arn", value)

    @_builtins.property
    @pulumi.getter(name="secretAccessKey")
    def secret_access_key(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        The secret AWS access key.
        """
        return pulumi.get(self, "secret_access_key")

    @secret_access_key.setter
    def secret_access_key(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "secret_access_key", value)

    @_builtins.property
    @pulumi.getter
    def source(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        The source of the EventBridge event. This identifies the application or service that is generating the event, e.g. `descope.auth`.
        """
        return pulumi.get(self, "source")

    @source.setter
    def source(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "source", value)

    @_builtins.property
    @pulumi.getter(name="troubleshootLogEnabled")
    def troubleshoot_log_enabled(self) -> pulumi.Input[Optional[_builtins.bool]]:
        """
        Whether to send troubleshooting events.
        """
        return pulumi.get(self, "troubleshoot_log_enabled")

    @troubleshoot_log_enabled.setter
    def troubleshoot_log_enabled(self, value: pulumi.Input[Optional[_builtins.bool]]):
        pulumi.set(self, "troubleshoot_log_enabled", value)


@pulumi.type_token("descope:index/awsEventbridgeConnector:AwsEventbridgeConnector")
class AwsEventbridgeConnector(pulumi.CustomResource):
    @overload
    def __init__(__self__,
                 resource_name: str,
                 opts: Optional[pulumi.ResourceOptions] = None,
                 access_key_id: pulumi.Input[Optional[_builtins.str]] = None,
                 audit_enabled: pulumi.Input[Optional[_builtins.bool]] = None,
                 audit_filters: pulumi.Input[Optional[Sequence[pulumi.Input[Union['AwsEventbridgeConnectorAuditFilterArgs', 'AwsEventbridgeConnectorAuditFilterArgsDict']]]]] = None,
                 auth_type: pulumi.Input[Optional[_builtins.str]] = None,
                 description: pulumi.Input[Optional[_builtins.str]] = None,
                 detail_type: pulumi.Input[Optional[_builtins.str]] = None,
                 disabled: pulumi.Input[Optional[_builtins.bool]] = None,
                 event_bus_name: pulumi.Input[Optional[_builtins.str]] = None,
                 external_id: pulumi.Input[Optional[_builtins.str]] = None,
                 mask_pii: pulumi.Input[Optional[_builtins.bool]] = None,
                 name: pulumi.Input[Optional[_builtins.str]] = None,
                 project_id: pulumi.Input[Optional[_builtins.str]] = None,
                 region: pulumi.Input[Optional[_builtins.str]] = None,
                 role_arn: pulumi.Input[Optional[_builtins.str]] = None,
                 secret_access_key: pulumi.Input[Optional[_builtins.str]] = None,
                 source: pulumi.Input[Optional[_builtins.str]] = None,
                 troubleshoot_log_enabled: pulumi.Input[Optional[_builtins.bool]] = None,
                 __props__=None):
        """
        Manages a AWS EventBridge connector and its configuration in a Descope project. Stream authentication audit logs with the Amazon EventBridge connector.


        :param str resource_name: The name of the resource.
        :param pulumi.ResourceOptions opts: Options for the resource.
        :param pulumi.Input[_builtins.str] access_key_id: The unique AWS access key ID.
        :param pulumi.Input[_builtins.bool] audit_enabled: Whether to enable streaming of audit events.
        :param pulumi.Input[Sequence[pulumi.Input[Union['AwsEventbridgeConnectorAuditFilterArgs', 'AwsEventbridgeConnectorAuditFilterArgsDict']]]] audit_filters: Specify which events will be sent to the external audit service (including tenant selection).
        :param pulumi.Input[_builtins.str] auth_type: The authentication type to use.
        :param pulumi.Input[_builtins.str] description: A description of what your connector is used for.
        :param pulumi.Input[_builtins.str] detail_type: The detail type for the EventBridge event. This is a free-form string used to identify the event type, e.g. `descope.audit.event`.
        :param pulumi.Input[_builtins.bool] disabled: Whether the connector is disabled. This can be used to temporarily stop a connector from executing without fully deleting it.
        :param pulumi.Input[_builtins.str] event_bus_name: The name or ARN of the EventBridge event bus. Use `default` for the default event bus or provide a custom event bus name/ARN.
        :param pulumi.Input[_builtins.str] external_id: The external ID to use when assuming the role.
        :param pulumi.Input[_builtins.bool] mask_pii: Whether to mask personally identifiable information in the logs.
        :param pulumi.Input[_builtins.str] name: A custom name for your connector.
        :param pulumi.Input[_builtins.str] project_id: The ID of the Descope project that the connector belongs to. Changing this value will require the resource to be deleted and recreated.
        :param pulumi.Input[_builtins.str] region: The AWS EventBridge region, e.g. `us-east-1`.
        :param pulumi.Input[_builtins.str] role_arn: The Amazon Resource Name (ARN) of the role to assume.
        :param pulumi.Input[_builtins.str] secret_access_key: The secret AWS access key.
        :param pulumi.Input[_builtins.str] source: The source of the EventBridge event. This identifies the application or service that is generating the event, e.g. `descope.auth`.
        :param pulumi.Input[_builtins.bool] troubleshoot_log_enabled: Whether to send troubleshooting events.
        """
        ...
    @overload
    def __init__(__self__,
                 resource_name: str,
                 args: AwsEventbridgeConnectorArgs,
                 opts: Optional[pulumi.ResourceOptions] = None):
        """
        Manages a AWS EventBridge connector and its configuration in a Descope project. Stream authentication audit logs with the Amazon EventBridge connector.


        :param str resource_name: The name of the resource.
        :param AwsEventbridgeConnectorArgs args: The arguments to use to populate this resource's properties.
        :param pulumi.ResourceOptions opts: Options for the resource.
        """
        ...
    def __init__(__self__, resource_name: str, *args, **kwargs):
        resource_args, opts = _utilities.get_resource_args_opts(AwsEventbridgeConnectorArgs, pulumi.ResourceOptions, *args, **kwargs)
        if resource_args is not None:
            __self__._internal_init(resource_name, opts, **resource_args.__dict__)
        else:
            __self__._internal_init(resource_name, *args, **kwargs)

    def _internal_init(__self__,
                 resource_name: str,
                 opts: Optional[pulumi.ResourceOptions] = None,
                 access_key_id: pulumi.Input[Optional[_builtins.str]] = None,
                 audit_enabled: pulumi.Input[Optional[_builtins.bool]] = None,
                 audit_filters: pulumi.Input[Optional[Sequence[pulumi.Input[Union['AwsEventbridgeConnectorAuditFilterArgs', 'AwsEventbridgeConnectorAuditFilterArgsDict']]]]] = None,
                 auth_type: pulumi.Input[Optional[_builtins.str]] = None,
                 description: pulumi.Input[Optional[_builtins.str]] = None,
                 detail_type: pulumi.Input[Optional[_builtins.str]] = None,
                 disabled: pulumi.Input[Optional[_builtins.bool]] = None,
                 event_bus_name: pulumi.Input[Optional[_builtins.str]] = None,
                 external_id: pulumi.Input[Optional[_builtins.str]] = None,
                 mask_pii: pulumi.Input[Optional[_builtins.bool]] = None,
                 name: pulumi.Input[Optional[_builtins.str]] = None,
                 project_id: pulumi.Input[Optional[_builtins.str]] = None,
                 region: pulumi.Input[Optional[_builtins.str]] = None,
                 role_arn: pulumi.Input[Optional[_builtins.str]] = None,
                 secret_access_key: pulumi.Input[Optional[_builtins.str]] = None,
                 source: pulumi.Input[Optional[_builtins.str]] = None,
                 troubleshoot_log_enabled: pulumi.Input[Optional[_builtins.bool]] = None,
                 __props__=None):
        opts = pulumi.ResourceOptions.merge(_utilities.get_resource_opts_defaults(), opts)
        if not isinstance(opts, pulumi.ResourceOptions):
            raise TypeError('Expected resource options to be a ResourceOptions instance')
        if opts.id is None:
            if __props__ is not None:
                raise TypeError('__props__ is only valid when passed in combination with a valid opts.id to get an existing resource')
            __props__ = AwsEventbridgeConnectorArgs.__new__(AwsEventbridgeConnectorArgs)

            __props__.__dict__["access_key_id"] = None if access_key_id is None else pulumi.Output.secret(access_key_id)
            __props__.__dict__["audit_enabled"] = audit_enabled
            __props__.__dict__["audit_filters"] = audit_filters
            __props__.__dict__["auth_type"] = auth_type
            __props__.__dict__["description"] = description
            if detail_type is None and not opts.urn:
                raise TypeError("Missing required property 'detail_type'")
            __props__.__dict__["detail_type"] = detail_type
            __props__.__dict__["disabled"] = disabled
            if event_bus_name is None and not opts.urn:
                raise TypeError("Missing required property 'event_bus_name'")
            __props__.__dict__["event_bus_name"] = event_bus_name
            __props__.__dict__["external_id"] = external_id
            __props__.__dict__["mask_pii"] = mask_pii
            __props__.__dict__["name"] = name
            if project_id is None and not opts.urn:
                raise TypeError("Missing required property 'project_id'")
            __props__.__dict__["project_id"] = project_id
            if region is None and not opts.urn:
                raise TypeError("Missing required property 'region'")
            __props__.__dict__["region"] = region
            __props__.__dict__["role_arn"] = role_arn
            __props__.__dict__["secret_access_key"] = None if secret_access_key is None else pulumi.Output.secret(secret_access_key)
            if source is None and not opts.urn:
                raise TypeError("Missing required property 'source'")
            __props__.__dict__["source"] = source
            __props__.__dict__["troubleshoot_log_enabled"] = troubleshoot_log_enabled
        secret_opts = pulumi.ResourceOptions(additional_secret_outputs=["accessKeyId", "secretAccessKey"])
        opts = pulumi.ResourceOptions.merge(opts, secret_opts)
        super(AwsEventbridgeConnector, __self__).__init__(
            'descope:index/awsEventbridgeConnector:AwsEventbridgeConnector',
            resource_name,
            __props__,
            opts)

    @staticmethod
    def get(resource_name: str,
            id: pulumi.Input[str],
            opts: Optional[pulumi.ResourceOptions] = None,
            access_key_id: pulumi.Input[Optional[_builtins.str]] = None,
            audit_enabled: pulumi.Input[Optional[_builtins.bool]] = None,
            audit_filters: pulumi.Input[Optional[Sequence[pulumi.Input[Union['AwsEventbridgeConnectorAuditFilterArgs', 'AwsEventbridgeConnectorAuditFilterArgsDict']]]]] = None,
            auth_type: pulumi.Input[Optional[_builtins.str]] = None,
            description: pulumi.Input[Optional[_builtins.str]] = None,
            detail_type: pulumi.Input[Optional[_builtins.str]] = None,
            disabled: pulumi.Input[Optional[_builtins.bool]] = None,
            event_bus_name: pulumi.Input[Optional[_builtins.str]] = None,
            external_id: pulumi.Input[Optional[_builtins.str]] = None,
            mask_pii: pulumi.Input[Optional[_builtins.bool]] = None,
            name: pulumi.Input[Optional[_builtins.str]] = None,
            project_id: pulumi.Input[Optional[_builtins.str]] = None,
            region: pulumi.Input[Optional[_builtins.str]] = None,
            role_arn: pulumi.Input[Optional[_builtins.str]] = None,
            secret_access_key: pulumi.Input[Optional[_builtins.str]] = None,
            source: pulumi.Input[Optional[_builtins.str]] = None,
            troubleshoot_log_enabled: pulumi.Input[Optional[_builtins.bool]] = None) -> 'AwsEventbridgeConnector':
        """
        Get an existing AwsEventbridgeConnector resource's state with the given name, id, and optional extra
        properties used to qualify the lookup.

        :param str resource_name: The unique name of the resulting resource.
        :param pulumi.Input[str] id: The unique provider ID of the resource to lookup.
        :param pulumi.ResourceOptions opts: Options for the resource.
        :param pulumi.Input[_builtins.str] access_key_id: The unique AWS access key ID.
        :param pulumi.Input[_builtins.bool] audit_enabled: Whether to enable streaming of audit events.
        :param pulumi.Input[Sequence[pulumi.Input[Union['AwsEventbridgeConnectorAuditFilterArgs', 'AwsEventbridgeConnectorAuditFilterArgsDict']]]] audit_filters: Specify which events will be sent to the external audit service (including tenant selection).
        :param pulumi.Input[_builtins.str] auth_type: The authentication type to use.
        :param pulumi.Input[_builtins.str] description: A description of what your connector is used for.
        :param pulumi.Input[_builtins.str] detail_type: The detail type for the EventBridge event. This is a free-form string used to identify the event type, e.g. `descope.audit.event`.
        :param pulumi.Input[_builtins.bool] disabled: Whether the connector is disabled. This can be used to temporarily stop a connector from executing without fully deleting it.
        :param pulumi.Input[_builtins.str] event_bus_name: The name or ARN of the EventBridge event bus. Use `default` for the default event bus or provide a custom event bus name/ARN.
        :param pulumi.Input[_builtins.str] external_id: The external ID to use when assuming the role.
        :param pulumi.Input[_builtins.bool] mask_pii: Whether to mask personally identifiable information in the logs.
        :param pulumi.Input[_builtins.str] name: A custom name for your connector.
        :param pulumi.Input[_builtins.str] project_id: The ID of the Descope project that the connector belongs to. Changing this value will require the resource to be deleted and recreated.
        :param pulumi.Input[_builtins.str] region: The AWS EventBridge region, e.g. `us-east-1`.
        :param pulumi.Input[_builtins.str] role_arn: The Amazon Resource Name (ARN) of the role to assume.
        :param pulumi.Input[_builtins.str] secret_access_key: The secret AWS access key.
        :param pulumi.Input[_builtins.str] source: The source of the EventBridge event. This identifies the application or service that is generating the event, e.g. `descope.auth`.
        :param pulumi.Input[_builtins.bool] troubleshoot_log_enabled: Whether to send troubleshooting events.
        """
        opts = pulumi.ResourceOptions.merge(opts, pulumi.ResourceOptions(id=id))

        __props__ = _AwsEventbridgeConnectorState.__new__(_AwsEventbridgeConnectorState)

        __props__.__dict__["access_key_id"] = access_key_id
        __props__.__dict__["audit_enabled"] = audit_enabled
        __props__.__dict__["audit_filters"] = audit_filters
        __props__.__dict__["auth_type"] = auth_type
        __props__.__dict__["description"] = description
        __props__.__dict__["detail_type"] = detail_type
        __props__.__dict__["disabled"] = disabled
        __props__.__dict__["event_bus_name"] = event_bus_name
        __props__.__dict__["external_id"] = external_id
        __props__.__dict__["mask_pii"] = mask_pii
        __props__.__dict__["name"] = name
        __props__.__dict__["project_id"] = project_id
        __props__.__dict__["region"] = region
        __props__.__dict__["role_arn"] = role_arn
        __props__.__dict__["secret_access_key"] = secret_access_key
        __props__.__dict__["source"] = source
        __props__.__dict__["troubleshoot_log_enabled"] = troubleshoot_log_enabled
        return AwsEventbridgeConnector(resource_name, opts=opts, __props__=__props__)

    @_builtins.property
    @pulumi.getter(name="accessKeyId")
    def access_key_id(self) -> pulumi.Output[_builtins.str]:
        """
        The unique AWS access key ID.
        """
        return pulumi.get(self, "access_key_id")

    @_builtins.property
    @pulumi.getter(name="auditEnabled")
    def audit_enabled(self) -> pulumi.Output[_builtins.bool]:
        """
        Whether to enable streaming of audit events.
        """
        return pulumi.get(self, "audit_enabled")

    @_builtins.property
    @pulumi.getter(name="auditFilters")
    def audit_filters(self) -> pulumi.Output[Sequence['outputs.AwsEventbridgeConnectorAuditFilter']]:
        """
        Specify which events will be sent to the external audit service (including tenant selection).
        """
        return pulumi.get(self, "audit_filters")

    @_builtins.property
    @pulumi.getter(name="authType")
    def auth_type(self) -> pulumi.Output[_builtins.str]:
        """
        The authentication type to use.
        """
        return pulumi.get(self, "auth_type")

    @_builtins.property
    @pulumi.getter
    def description(self) -> pulumi.Output[_builtins.str]:
        """
        A description of what your connector is used for.
        """
        return pulumi.get(self, "description")

    @_builtins.property
    @pulumi.getter(name="detailType")
    def detail_type(self) -> pulumi.Output[_builtins.str]:
        """
        The detail type for the EventBridge event. This is a free-form string used to identify the event type, e.g. `descope.audit.event`.
        """
        return pulumi.get(self, "detail_type")

    @_builtins.property
    @pulumi.getter
    def disabled(self) -> pulumi.Output[_builtins.bool]:
        """
        Whether the connector is disabled. This can be used to temporarily stop a connector from executing without fully deleting it.
        """
        return pulumi.get(self, "disabled")

    @_builtins.property
    @pulumi.getter(name="eventBusName")
    def event_bus_name(self) -> pulumi.Output[_builtins.str]:
        """
        The name or ARN of the EventBridge event bus. Use `default` for the default event bus or provide a custom event bus name/ARN.
        """
        return pulumi.get(self, "event_bus_name")

    @_builtins.property
    @pulumi.getter(name="externalId")
    def external_id(self) -> pulumi.Output[_builtins.str]:
        """
        The external ID to use when assuming the role.
        """
        return pulumi.get(self, "external_id")

    @_builtins.property
    @pulumi.getter(name="maskPii")
    def mask_pii(self) -> pulumi.Output[_builtins.bool]:
        """
        Whether to mask personally identifiable information in the logs.
        """
        return pulumi.get(self, "mask_pii")

    @_builtins.property
    @pulumi.getter
    def name(self) -> pulumi.Output[_builtins.str]:
        """
        A custom name for your connector.
        """
        return pulumi.get(self, "name")

    @_builtins.property
    @pulumi.getter(name="projectId")
    def project_id(self) -> pulumi.Output[_builtins.str]:
        """
        The ID of the Descope project that the connector belongs to. Changing this value will require the resource to be deleted and recreated.
        """
        return pulumi.get(self, "project_id")

    @_builtins.property
    @pulumi.getter
    def region(self) -> pulumi.Output[_builtins.str]:
        """
        The AWS EventBridge region, e.g. `us-east-1`.
        """
        return pulumi.get(self, "region")

    @_builtins.property
    @pulumi.getter(name="roleArn")
    def role_arn(self) -> pulumi.Output[_builtins.str]:
        """
        The Amazon Resource Name (ARN) of the role to assume.
        """
        return pulumi.get(self, "role_arn")

    @_builtins.property
    @pulumi.getter(name="secretAccessKey")
    def secret_access_key(self) -> pulumi.Output[_builtins.str]:
        """
        The secret AWS access key.
        """
        return pulumi.get(self, "secret_access_key")

    @_builtins.property
    @pulumi.getter
    def source(self) -> pulumi.Output[_builtins.str]:
        """
        The source of the EventBridge event. This identifies the application or service that is generating the event, e.g. `descope.auth`.
        """
        return pulumi.get(self, "source")

    @_builtins.property
    @pulumi.getter(name="troubleshootLogEnabled")
    def troubleshoot_log_enabled(self) -> pulumi.Output[_builtins.bool]:
        """
        Whether to send troubleshooting events.
        """
        return pulumi.get(self, "troubleshoot_log_enabled")

