# coding=utf-8
# *** WARNING: this file was generated by pulumi-language-python. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import builtins as _builtins
import warnings
import sys
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
if sys.version_info >= (3, 11):
    from typing import NotRequired, TypedDict, TypeAlias
else:
    from typing_extensions import NotRequired, TypedDict, TypeAlias
from . import _utilities

__all__ = ['SessionSettingsArgs', 'SessionSettings']

@pulumi.input_type
class SessionSettingsArgs:
    def __init__(__self__, *,
                 project_id: pulumi.Input[_builtins.str],
                 access_key_jwt_template: pulumi.Input[Optional[_builtins.str]] = None,
                 access_key_session_token_expiration: pulumi.Input[Optional[_builtins.str]] = None,
                 enable_inactivity: pulumi.Input[Optional[_builtins.bool]] = None,
                 inactivity_time: pulumi.Input[Optional[_builtins.str]] = None,
                 refresh_token_cookie_domain: pulumi.Input[Optional[_builtins.str]] = None,
                 refresh_token_cookie_policy: pulumi.Input[Optional[_builtins.str]] = None,
                 refresh_token_expiration: pulumi.Input[Optional[_builtins.str]] = None,
                 refresh_token_response_method: pulumi.Input[Optional[_builtins.str]] = None,
                 refresh_token_rotation: pulumi.Input[Optional[_builtins.bool]] = None,
                 session_token_cookie_domain: pulumi.Input[Optional[_builtins.str]] = None,
                 session_token_cookie_policy: pulumi.Input[Optional[_builtins.str]] = None,
                 session_token_expiration: pulumi.Input[Optional[_builtins.str]] = None,
                 session_token_response_method: pulumi.Input[Optional[_builtins.str]] = None,
                 step_up_token_expiration: pulumi.Input[Optional[_builtins.str]] = None,
                 trusted_device_token_expiration: pulumi.Input[Optional[_builtins.str]] = None,
                 user_jwt_template: pulumi.Input[Optional[_builtins.str]] = None):
        """
        The set of arguments for constructing a SessionSettings resource.

        :param pulumi.Input[_builtins.str] project_id: The ID of the project that these settings belong to. Changing this value will require the resource to be deleted and recreated.
        :param pulumi.Input[_builtins.str] access_key_jwt_template: The ID of the JWT template used for access key session tokens.
        :param pulumi.Input[_builtins.str] access_key_session_token_expiration: How long access key session tokens remain valid before they expire.
        :param pulumi.Input[_builtins.bool] enable_inactivity: Whether to detect idle sessions and close them on behalf of the user.
        :param pulumi.Input[_builtins.str] inactivity_time: How long a session can be inactive before it's closed, when `enable_inactivity` is set.
        :param pulumi.Input[_builtins.str] refresh_token_cookie_domain: The domain the refresh token cookie is restricted to.
        :param pulumi.Input[_builtins.str] refresh_token_cookie_policy: The SameSite cookie policy for the refresh token cookie, either `strict`, `lax` or `none`.
        :param pulumi.Input[_builtins.str] refresh_token_expiration: How long refresh tokens remain valid before they expire.
        :param pulumi.Input[_builtins.str] refresh_token_response_method: How refresh tokens are managed by the Descope SDKs, either `response_body` or `cookies`.
        :param pulumi.Input[_builtins.bool] refresh_token_rotation: Whether to rotate the refresh token every time it's used to refresh the session.
        :param pulumi.Input[_builtins.str] session_token_cookie_domain: The domain the session token cookie is restricted to.
        :param pulumi.Input[_builtins.str] session_token_cookie_policy: The SameSite cookie policy for the session token cookie, either `strict`, `lax` or `none`.
        :param pulumi.Input[_builtins.str] session_token_expiration: How long session tokens remain valid before they expire.
        :param pulumi.Input[_builtins.str] session_token_response_method: How session tokens are managed by the Descope SDKs, either `response_body` or `cookies`.
        :param pulumi.Input[_builtins.str] step_up_token_expiration: How long step up tokens remain valid before they expire.
        :param pulumi.Input[_builtins.str] trusted_device_token_expiration: How long trusted device tokens remain valid before they expire.
        :param pulumi.Input[_builtins.str] user_jwt_template: The ID of the JWT template used for user session tokens (e.g. `descope_jwt_template.example.id`).
        """
        pulumi.set(__self__, "project_id", project_id)
        if access_key_jwt_template is not None:
            pulumi.set(__self__, "access_key_jwt_template", access_key_jwt_template)
        if access_key_session_token_expiration is not None:
            pulumi.set(__self__, "access_key_session_token_expiration", access_key_session_token_expiration)
        if enable_inactivity is not None:
            pulumi.set(__self__, "enable_inactivity", enable_inactivity)
        if inactivity_time is not None:
            pulumi.set(__self__, "inactivity_time", inactivity_time)
        if refresh_token_cookie_domain is not None:
            pulumi.set(__self__, "refresh_token_cookie_domain", refresh_token_cookie_domain)
        if refresh_token_cookie_policy is not None:
            pulumi.set(__self__, "refresh_token_cookie_policy", refresh_token_cookie_policy)
        if refresh_token_expiration is not None:
            pulumi.set(__self__, "refresh_token_expiration", refresh_token_expiration)
        if refresh_token_response_method is not None:
            pulumi.set(__self__, "refresh_token_response_method", refresh_token_response_method)
        if refresh_token_rotation is not None:
            pulumi.set(__self__, "refresh_token_rotation", refresh_token_rotation)
        if session_token_cookie_domain is not None:
            pulumi.set(__self__, "session_token_cookie_domain", session_token_cookie_domain)
        if session_token_cookie_policy is not None:
            pulumi.set(__self__, "session_token_cookie_policy", session_token_cookie_policy)
        if session_token_expiration is not None:
            pulumi.set(__self__, "session_token_expiration", session_token_expiration)
        if session_token_response_method is not None:
            pulumi.set(__self__, "session_token_response_method", session_token_response_method)
        if step_up_token_expiration is not None:
            pulumi.set(__self__, "step_up_token_expiration", step_up_token_expiration)
        if trusted_device_token_expiration is not None:
            pulumi.set(__self__, "trusted_device_token_expiration", trusted_device_token_expiration)
        if user_jwt_template is not None:
            pulumi.set(__self__, "user_jwt_template", user_jwt_template)

    @_builtins.property
    @pulumi.getter(name="projectId")
    def project_id(self) -> pulumi.Input[_builtins.str]:
        """
        The ID of the project that these settings belong to. Changing this value will require the resource to be deleted and recreated.
        """
        return pulumi.get(self, "project_id")

    @project_id.setter
    def project_id(self, value: pulumi.Input[_builtins.str]):
        pulumi.set(self, "project_id", value)

    @_builtins.property
    @pulumi.getter(name="accessKeyJwtTemplate")
    def access_key_jwt_template(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        The ID of the JWT template used for access key session tokens.
        """
        return pulumi.get(self, "access_key_jwt_template")

    @access_key_jwt_template.setter
    def access_key_jwt_template(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "access_key_jwt_template", value)

    @_builtins.property
    @pulumi.getter(name="accessKeySessionTokenExpiration")
    def access_key_session_token_expiration(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        How long access key session tokens remain valid before they expire.
        """
        return pulumi.get(self, "access_key_session_token_expiration")

    @access_key_session_token_expiration.setter
    def access_key_session_token_expiration(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "access_key_session_token_expiration", value)

    @_builtins.property
    @pulumi.getter(name="enableInactivity")
    def enable_inactivity(self) -> pulumi.Input[Optional[_builtins.bool]]:
        """
        Whether to detect idle sessions and close them on behalf of the user.
        """
        return pulumi.get(self, "enable_inactivity")

    @enable_inactivity.setter
    def enable_inactivity(self, value: pulumi.Input[Optional[_builtins.bool]]):
        pulumi.set(self, "enable_inactivity", value)

    @_builtins.property
    @pulumi.getter(name="inactivityTime")
    def inactivity_time(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        How long a session can be inactive before it's closed, when `enable_inactivity` is set.
        """
        return pulumi.get(self, "inactivity_time")

    @inactivity_time.setter
    def inactivity_time(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "inactivity_time", value)

    @_builtins.property
    @pulumi.getter(name="refreshTokenCookieDomain")
    def refresh_token_cookie_domain(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        The domain the refresh token cookie is restricted to.
        """
        return pulumi.get(self, "refresh_token_cookie_domain")

    @refresh_token_cookie_domain.setter
    def refresh_token_cookie_domain(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "refresh_token_cookie_domain", value)

    @_builtins.property
    @pulumi.getter(name="refreshTokenCookiePolicy")
    def refresh_token_cookie_policy(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        The SameSite cookie policy for the refresh token cookie, either `strict`, `lax` or `none`.
        """
        return pulumi.get(self, "refresh_token_cookie_policy")

    @refresh_token_cookie_policy.setter
    def refresh_token_cookie_policy(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "refresh_token_cookie_policy", value)

    @_builtins.property
    @pulumi.getter(name="refreshTokenExpiration")
    def refresh_token_expiration(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        How long refresh tokens remain valid before they expire.
        """
        return pulumi.get(self, "refresh_token_expiration")

    @refresh_token_expiration.setter
    def refresh_token_expiration(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "refresh_token_expiration", value)

    @_builtins.property
    @pulumi.getter(name="refreshTokenResponseMethod")
    def refresh_token_response_method(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        How refresh tokens are managed by the Descope SDKs, either `response_body` or `cookies`.
        """
        return pulumi.get(self, "refresh_token_response_method")

    @refresh_token_response_method.setter
    def refresh_token_response_method(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "refresh_token_response_method", value)

    @_builtins.property
    @pulumi.getter(name="refreshTokenRotation")
    def refresh_token_rotation(self) -> pulumi.Input[Optional[_builtins.bool]]:
        """
        Whether to rotate the refresh token every time it's used to refresh the session.
        """
        return pulumi.get(self, "refresh_token_rotation")

    @refresh_token_rotation.setter
    def refresh_token_rotation(self, value: pulumi.Input[Optional[_builtins.bool]]):
        pulumi.set(self, "refresh_token_rotation", value)

    @_builtins.property
    @pulumi.getter(name="sessionTokenCookieDomain")
    def session_token_cookie_domain(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        The domain the session token cookie is restricted to.
        """
        return pulumi.get(self, "session_token_cookie_domain")

    @session_token_cookie_domain.setter
    def session_token_cookie_domain(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "session_token_cookie_domain", value)

    @_builtins.property
    @pulumi.getter(name="sessionTokenCookiePolicy")
    def session_token_cookie_policy(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        The SameSite cookie policy for the session token cookie, either `strict`, `lax` or `none`.
        """
        return pulumi.get(self, "session_token_cookie_policy")

    @session_token_cookie_policy.setter
    def session_token_cookie_policy(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "session_token_cookie_policy", value)

    @_builtins.property
    @pulumi.getter(name="sessionTokenExpiration")
    def session_token_expiration(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        How long session tokens remain valid before they expire.
        """
        return pulumi.get(self, "session_token_expiration")

    @session_token_expiration.setter
    def session_token_expiration(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "session_token_expiration", value)

    @_builtins.property
    @pulumi.getter(name="sessionTokenResponseMethod")
    def session_token_response_method(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        How session tokens are managed by the Descope SDKs, either `response_body` or `cookies`.
        """
        return pulumi.get(self, "session_token_response_method")

    @session_token_response_method.setter
    def session_token_response_method(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "session_token_response_method", value)

    @_builtins.property
    @pulumi.getter(name="stepUpTokenExpiration")
    def step_up_token_expiration(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        How long step up tokens remain valid before they expire.
        """
        return pulumi.get(self, "step_up_token_expiration")

    @step_up_token_expiration.setter
    def step_up_token_expiration(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "step_up_token_expiration", value)

    @_builtins.property
    @pulumi.getter(name="trustedDeviceTokenExpiration")
    def trusted_device_token_expiration(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        How long trusted device tokens remain valid before they expire.
        """
        return pulumi.get(self, "trusted_device_token_expiration")

    @trusted_device_token_expiration.setter
    def trusted_device_token_expiration(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "trusted_device_token_expiration", value)

    @_builtins.property
    @pulumi.getter(name="userJwtTemplate")
    def user_jwt_template(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        The ID of the JWT template used for user session tokens (e.g. `descope_jwt_template.example.id`).
        """
        return pulumi.get(self, "user_jwt_template")

    @user_jwt_template.setter
    def user_jwt_template(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "user_jwt_template", value)


@pulumi.input_type
class _SessionSettingsState:
    def __init__(__self__, *,
                 access_key_jwt_template: pulumi.Input[Optional[_builtins.str]] = None,
                 access_key_session_token_expiration: pulumi.Input[Optional[_builtins.str]] = None,
                 enable_inactivity: pulumi.Input[Optional[_builtins.bool]] = None,
                 inactivity_time: pulumi.Input[Optional[_builtins.str]] = None,
                 project_id: pulumi.Input[Optional[_builtins.str]] = None,
                 refresh_token_cookie_domain: pulumi.Input[Optional[_builtins.str]] = None,
                 refresh_token_cookie_policy: pulumi.Input[Optional[_builtins.str]] = None,
                 refresh_token_expiration: pulumi.Input[Optional[_builtins.str]] = None,
                 refresh_token_response_method: pulumi.Input[Optional[_builtins.str]] = None,
                 refresh_token_rotation: pulumi.Input[Optional[_builtins.bool]] = None,
                 session_token_cookie_domain: pulumi.Input[Optional[_builtins.str]] = None,
                 session_token_cookie_policy: pulumi.Input[Optional[_builtins.str]] = None,
                 session_token_expiration: pulumi.Input[Optional[_builtins.str]] = None,
                 session_token_response_method: pulumi.Input[Optional[_builtins.str]] = None,
                 step_up_token_expiration: pulumi.Input[Optional[_builtins.str]] = None,
                 trusted_device_token_expiration: pulumi.Input[Optional[_builtins.str]] = None,
                 user_jwt_template: pulumi.Input[Optional[_builtins.str]] = None):
        """
        Input properties used for looking up and filtering SessionSettings resources.

        :param pulumi.Input[_builtins.str] access_key_jwt_template: The ID of the JWT template used for access key session tokens.
        :param pulumi.Input[_builtins.str] access_key_session_token_expiration: How long access key session tokens remain valid before they expire.
        :param pulumi.Input[_builtins.bool] enable_inactivity: Whether to detect idle sessions and close them on behalf of the user.
        :param pulumi.Input[_builtins.str] inactivity_time: How long a session can be inactive before it's closed, when `enable_inactivity` is set.
        :param pulumi.Input[_builtins.str] project_id: The ID of the project that these settings belong to. Changing this value will require the resource to be deleted and recreated.
        :param pulumi.Input[_builtins.str] refresh_token_cookie_domain: The domain the refresh token cookie is restricted to.
        :param pulumi.Input[_builtins.str] refresh_token_cookie_policy: The SameSite cookie policy for the refresh token cookie, either `strict`, `lax` or `none`.
        :param pulumi.Input[_builtins.str] refresh_token_expiration: How long refresh tokens remain valid before they expire.
        :param pulumi.Input[_builtins.str] refresh_token_response_method: How refresh tokens are managed by the Descope SDKs, either `response_body` or `cookies`.
        :param pulumi.Input[_builtins.bool] refresh_token_rotation: Whether to rotate the refresh token every time it's used to refresh the session.
        :param pulumi.Input[_builtins.str] session_token_cookie_domain: The domain the session token cookie is restricted to.
        :param pulumi.Input[_builtins.str] session_token_cookie_policy: The SameSite cookie policy for the session token cookie, either `strict`, `lax` or `none`.
        :param pulumi.Input[_builtins.str] session_token_expiration: How long session tokens remain valid before they expire.
        :param pulumi.Input[_builtins.str] session_token_response_method: How session tokens are managed by the Descope SDKs, either `response_body` or `cookies`.
        :param pulumi.Input[_builtins.str] step_up_token_expiration: How long step up tokens remain valid before they expire.
        :param pulumi.Input[_builtins.str] trusted_device_token_expiration: How long trusted device tokens remain valid before they expire.
        :param pulumi.Input[_builtins.str] user_jwt_template: The ID of the JWT template used for user session tokens (e.g. `descope_jwt_template.example.id`).
        """
        if access_key_jwt_template is not None:
            pulumi.set(__self__, "access_key_jwt_template", access_key_jwt_template)
        if access_key_session_token_expiration is not None:
            pulumi.set(__self__, "access_key_session_token_expiration", access_key_session_token_expiration)
        if enable_inactivity is not None:
            pulumi.set(__self__, "enable_inactivity", enable_inactivity)
        if inactivity_time is not None:
            pulumi.set(__self__, "inactivity_time", inactivity_time)
        if project_id is not None:
            pulumi.set(__self__, "project_id", project_id)
        if refresh_token_cookie_domain is not None:
            pulumi.set(__self__, "refresh_token_cookie_domain", refresh_token_cookie_domain)
        if refresh_token_cookie_policy is not None:
            pulumi.set(__self__, "refresh_token_cookie_policy", refresh_token_cookie_policy)
        if refresh_token_expiration is not None:
            pulumi.set(__self__, "refresh_token_expiration", refresh_token_expiration)
        if refresh_token_response_method is not None:
            pulumi.set(__self__, "refresh_token_response_method", refresh_token_response_method)
        if refresh_token_rotation is not None:
            pulumi.set(__self__, "refresh_token_rotation", refresh_token_rotation)
        if session_token_cookie_domain is not None:
            pulumi.set(__self__, "session_token_cookie_domain", session_token_cookie_domain)
        if session_token_cookie_policy is not None:
            pulumi.set(__self__, "session_token_cookie_policy", session_token_cookie_policy)
        if session_token_expiration is not None:
            pulumi.set(__self__, "session_token_expiration", session_token_expiration)
        if session_token_response_method is not None:
            pulumi.set(__self__, "session_token_response_method", session_token_response_method)
        if step_up_token_expiration is not None:
            pulumi.set(__self__, "step_up_token_expiration", step_up_token_expiration)
        if trusted_device_token_expiration is not None:
            pulumi.set(__self__, "trusted_device_token_expiration", trusted_device_token_expiration)
        if user_jwt_template is not None:
            pulumi.set(__self__, "user_jwt_template", user_jwt_template)

    @_builtins.property
    @pulumi.getter(name="accessKeyJwtTemplate")
    def access_key_jwt_template(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        The ID of the JWT template used for access key session tokens.
        """
        return pulumi.get(self, "access_key_jwt_template")

    @access_key_jwt_template.setter
    def access_key_jwt_template(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "access_key_jwt_template", value)

    @_builtins.property
    @pulumi.getter(name="accessKeySessionTokenExpiration")
    def access_key_session_token_expiration(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        How long access key session tokens remain valid before they expire.
        """
        return pulumi.get(self, "access_key_session_token_expiration")

    @access_key_session_token_expiration.setter
    def access_key_session_token_expiration(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "access_key_session_token_expiration", value)

    @_builtins.property
    @pulumi.getter(name="enableInactivity")
    def enable_inactivity(self) -> pulumi.Input[Optional[_builtins.bool]]:
        """
        Whether to detect idle sessions and close them on behalf of the user.
        """
        return pulumi.get(self, "enable_inactivity")

    @enable_inactivity.setter
    def enable_inactivity(self, value: pulumi.Input[Optional[_builtins.bool]]):
        pulumi.set(self, "enable_inactivity", value)

    @_builtins.property
    @pulumi.getter(name="inactivityTime")
    def inactivity_time(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        How long a session can be inactive before it's closed, when `enable_inactivity` is set.
        """
        return pulumi.get(self, "inactivity_time")

    @inactivity_time.setter
    def inactivity_time(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "inactivity_time", value)

    @_builtins.property
    @pulumi.getter(name="projectId")
    def project_id(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        The ID of the project that these settings belong to. Changing this value will require the resource to be deleted and recreated.
        """
        return pulumi.get(self, "project_id")

    @project_id.setter
    def project_id(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "project_id", value)

    @_builtins.property
    @pulumi.getter(name="refreshTokenCookieDomain")
    def refresh_token_cookie_domain(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        The domain the refresh token cookie is restricted to.
        """
        return pulumi.get(self, "refresh_token_cookie_domain")

    @refresh_token_cookie_domain.setter
    def refresh_token_cookie_domain(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "refresh_token_cookie_domain", value)

    @_builtins.property
    @pulumi.getter(name="refreshTokenCookiePolicy")
    def refresh_token_cookie_policy(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        The SameSite cookie policy for the refresh token cookie, either `strict`, `lax` or `none`.
        """
        return pulumi.get(self, "refresh_token_cookie_policy")

    @refresh_token_cookie_policy.setter
    def refresh_token_cookie_policy(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "refresh_token_cookie_policy", value)

    @_builtins.property
    @pulumi.getter(name="refreshTokenExpiration")
    def refresh_token_expiration(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        How long refresh tokens remain valid before they expire.
        """
        return pulumi.get(self, "refresh_token_expiration")

    @refresh_token_expiration.setter
    def refresh_token_expiration(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "refresh_token_expiration", value)

    @_builtins.property
    @pulumi.getter(name="refreshTokenResponseMethod")
    def refresh_token_response_method(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        How refresh tokens are managed by the Descope SDKs, either `response_body` or `cookies`.
        """
        return pulumi.get(self, "refresh_token_response_method")

    @refresh_token_response_method.setter
    def refresh_token_response_method(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "refresh_token_response_method", value)

    @_builtins.property
    @pulumi.getter(name="refreshTokenRotation")
    def refresh_token_rotation(self) -> pulumi.Input[Optional[_builtins.bool]]:
        """
        Whether to rotate the refresh token every time it's used to refresh the session.
        """
        return pulumi.get(self, "refresh_token_rotation")

    @refresh_token_rotation.setter
    def refresh_token_rotation(self, value: pulumi.Input[Optional[_builtins.bool]]):
        pulumi.set(self, "refresh_token_rotation", value)

    @_builtins.property
    @pulumi.getter(name="sessionTokenCookieDomain")
    def session_token_cookie_domain(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        The domain the session token cookie is restricted to.
        """
        return pulumi.get(self, "session_token_cookie_domain")

    @session_token_cookie_domain.setter
    def session_token_cookie_domain(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "session_token_cookie_domain", value)

    @_builtins.property
    @pulumi.getter(name="sessionTokenCookiePolicy")
    def session_token_cookie_policy(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        The SameSite cookie policy for the session token cookie, either `strict`, `lax` or `none`.
        """
        return pulumi.get(self, "session_token_cookie_policy")

    @session_token_cookie_policy.setter
    def session_token_cookie_policy(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "session_token_cookie_policy", value)

    @_builtins.property
    @pulumi.getter(name="sessionTokenExpiration")
    def session_token_expiration(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        How long session tokens remain valid before they expire.
        """
        return pulumi.get(self, "session_token_expiration")

    @session_token_expiration.setter
    def session_token_expiration(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "session_token_expiration", value)

    @_builtins.property
    @pulumi.getter(name="sessionTokenResponseMethod")
    def session_token_response_method(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        How session tokens are managed by the Descope SDKs, either `response_body` or `cookies`.
        """
        return pulumi.get(self, "session_token_response_method")

    @session_token_response_method.setter
    def session_token_response_method(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "session_token_response_method", value)

    @_builtins.property
    @pulumi.getter(name="stepUpTokenExpiration")
    def step_up_token_expiration(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        How long step up tokens remain valid before they expire.
        """
        return pulumi.get(self, "step_up_token_expiration")

    @step_up_token_expiration.setter
    def step_up_token_expiration(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "step_up_token_expiration", value)

    @_builtins.property
    @pulumi.getter(name="trustedDeviceTokenExpiration")
    def trusted_device_token_expiration(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        How long trusted device tokens remain valid before they expire.
        """
        return pulumi.get(self, "trusted_device_token_expiration")

    @trusted_device_token_expiration.setter
    def trusted_device_token_expiration(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "trusted_device_token_expiration", value)

    @_builtins.property
    @pulumi.getter(name="userJwtTemplate")
    def user_jwt_template(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        The ID of the JWT template used for user session tokens (e.g. `descope_jwt_template.example.id`).
        """
        return pulumi.get(self, "user_jwt_template")

    @user_jwt_template.setter
    def user_jwt_template(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "user_jwt_template", value)


@pulumi.type_token("descope:index/sessionSettings:SessionSettings")
class SessionSettings(pulumi.CustomResource):
    @overload
    def __init__(__self__,
                 resource_name: str,
                 opts: Optional[pulumi.ResourceOptions] = None,
                 access_key_jwt_template: pulumi.Input[Optional[_builtins.str]] = None,
                 access_key_session_token_expiration: pulumi.Input[Optional[_builtins.str]] = None,
                 enable_inactivity: pulumi.Input[Optional[_builtins.bool]] = None,
                 inactivity_time: pulumi.Input[Optional[_builtins.str]] = None,
                 project_id: pulumi.Input[Optional[_builtins.str]] = None,
                 refresh_token_cookie_domain: pulumi.Input[Optional[_builtins.str]] = None,
                 refresh_token_cookie_policy: pulumi.Input[Optional[_builtins.str]] = None,
                 refresh_token_expiration: pulumi.Input[Optional[_builtins.str]] = None,
                 refresh_token_response_method: pulumi.Input[Optional[_builtins.str]] = None,
                 refresh_token_rotation: pulumi.Input[Optional[_builtins.bool]] = None,
                 session_token_cookie_domain: pulumi.Input[Optional[_builtins.str]] = None,
                 session_token_cookie_policy: pulumi.Input[Optional[_builtins.str]] = None,
                 session_token_expiration: pulumi.Input[Optional[_builtins.str]] = None,
                 session_token_response_method: pulumi.Input[Optional[_builtins.str]] = None,
                 step_up_token_expiration: pulumi.Input[Optional[_builtins.str]] = None,
                 trusted_device_token_expiration: pulumi.Input[Optional[_builtins.str]] = None,
                 user_jwt_template: pulumi.Input[Optional[_builtins.str]] = None,
                 __props__=None):
        """
        Manages the project-level session management settings. This is a singleton resource, and its id is always the project ID.


        :param str resource_name: The name of the resource.
        :param pulumi.ResourceOptions opts: Options for the resource.
        :param pulumi.Input[_builtins.str] access_key_jwt_template: The ID of the JWT template used for access key session tokens.
        :param pulumi.Input[_builtins.str] access_key_session_token_expiration: How long access key session tokens remain valid before they expire.
        :param pulumi.Input[_builtins.bool] enable_inactivity: Whether to detect idle sessions and close them on behalf of the user.
        :param pulumi.Input[_builtins.str] inactivity_time: How long a session can be inactive before it's closed, when `enable_inactivity` is set.
        :param pulumi.Input[_builtins.str] project_id: The ID of the project that these settings belong to. Changing this value will require the resource to be deleted and recreated.
        :param pulumi.Input[_builtins.str] refresh_token_cookie_domain: The domain the refresh token cookie is restricted to.
        :param pulumi.Input[_builtins.str] refresh_token_cookie_policy: The SameSite cookie policy for the refresh token cookie, either `strict`, `lax` or `none`.
        :param pulumi.Input[_builtins.str] refresh_token_expiration: How long refresh tokens remain valid before they expire.
        :param pulumi.Input[_builtins.str] refresh_token_response_method: How refresh tokens are managed by the Descope SDKs, either `response_body` or `cookies`.
        :param pulumi.Input[_builtins.bool] refresh_token_rotation: Whether to rotate the refresh token every time it's used to refresh the session.
        :param pulumi.Input[_builtins.str] session_token_cookie_domain: The domain the session token cookie is restricted to.
        :param pulumi.Input[_builtins.str] session_token_cookie_policy: The SameSite cookie policy for the session token cookie, either `strict`, `lax` or `none`.
        :param pulumi.Input[_builtins.str] session_token_expiration: How long session tokens remain valid before they expire.
        :param pulumi.Input[_builtins.str] session_token_response_method: How session tokens are managed by the Descope SDKs, either `response_body` or `cookies`.
        :param pulumi.Input[_builtins.str] step_up_token_expiration: How long step up tokens remain valid before they expire.
        :param pulumi.Input[_builtins.str] trusted_device_token_expiration: How long trusted device tokens remain valid before they expire.
        :param pulumi.Input[_builtins.str] user_jwt_template: The ID of the JWT template used for user session tokens (e.g. `descope_jwt_template.example.id`).
        """
        ...
    @overload
    def __init__(__self__,
                 resource_name: str,
                 args: SessionSettingsArgs,
                 opts: Optional[pulumi.ResourceOptions] = None):
        """
        Manages the project-level session management settings. This is a singleton resource, and its id is always the project ID.


        :param str resource_name: The name of the resource.
        :param SessionSettingsArgs args: The arguments to use to populate this resource's properties.
        :param pulumi.ResourceOptions opts: Options for the resource.
        """
        ...
    def __init__(__self__, resource_name: str, *args, **kwargs):
        resource_args, opts = _utilities.get_resource_args_opts(SessionSettingsArgs, pulumi.ResourceOptions, *args, **kwargs)
        if resource_args is not None:
            __self__._internal_init(resource_name, opts, **resource_args.__dict__)
        else:
            __self__._internal_init(resource_name, *args, **kwargs)

    def _internal_init(__self__,
                 resource_name: str,
                 opts: Optional[pulumi.ResourceOptions] = None,
                 access_key_jwt_template: pulumi.Input[Optional[_builtins.str]] = None,
                 access_key_session_token_expiration: pulumi.Input[Optional[_builtins.str]] = None,
                 enable_inactivity: pulumi.Input[Optional[_builtins.bool]] = None,
                 inactivity_time: pulumi.Input[Optional[_builtins.str]] = None,
                 project_id: pulumi.Input[Optional[_builtins.str]] = None,
                 refresh_token_cookie_domain: pulumi.Input[Optional[_builtins.str]] = None,
                 refresh_token_cookie_policy: pulumi.Input[Optional[_builtins.str]] = None,
                 refresh_token_expiration: pulumi.Input[Optional[_builtins.str]] = None,
                 refresh_token_response_method: pulumi.Input[Optional[_builtins.str]] = None,
                 refresh_token_rotation: pulumi.Input[Optional[_builtins.bool]] = None,
                 session_token_cookie_domain: pulumi.Input[Optional[_builtins.str]] = None,
                 session_token_cookie_policy: pulumi.Input[Optional[_builtins.str]] = None,
                 session_token_expiration: pulumi.Input[Optional[_builtins.str]] = None,
                 session_token_response_method: pulumi.Input[Optional[_builtins.str]] = None,
                 step_up_token_expiration: pulumi.Input[Optional[_builtins.str]] = None,
                 trusted_device_token_expiration: pulumi.Input[Optional[_builtins.str]] = None,
                 user_jwt_template: pulumi.Input[Optional[_builtins.str]] = None,
                 __props__=None):
        opts = pulumi.ResourceOptions.merge(_utilities.get_resource_opts_defaults(), opts)
        if not isinstance(opts, pulumi.ResourceOptions):
            raise TypeError('Expected resource options to be a ResourceOptions instance')
        if opts.id is None:
            if __props__ is not None:
                raise TypeError('__props__ is only valid when passed in combination with a valid opts.id to get an existing resource')
            __props__ = SessionSettingsArgs.__new__(SessionSettingsArgs)

            __props__.__dict__["access_key_jwt_template"] = access_key_jwt_template
            __props__.__dict__["access_key_session_token_expiration"] = access_key_session_token_expiration
            __props__.__dict__["enable_inactivity"] = enable_inactivity
            __props__.__dict__["inactivity_time"] = inactivity_time
            if project_id is None and not opts.urn:
                raise TypeError("Missing required property 'project_id'")
            __props__.__dict__["project_id"] = project_id
            __props__.__dict__["refresh_token_cookie_domain"] = refresh_token_cookie_domain
            __props__.__dict__["refresh_token_cookie_policy"] = refresh_token_cookie_policy
            __props__.__dict__["refresh_token_expiration"] = refresh_token_expiration
            __props__.__dict__["refresh_token_response_method"] = refresh_token_response_method
            __props__.__dict__["refresh_token_rotation"] = refresh_token_rotation
            __props__.__dict__["session_token_cookie_domain"] = session_token_cookie_domain
            __props__.__dict__["session_token_cookie_policy"] = session_token_cookie_policy
            __props__.__dict__["session_token_expiration"] = session_token_expiration
            __props__.__dict__["session_token_response_method"] = session_token_response_method
            __props__.__dict__["step_up_token_expiration"] = step_up_token_expiration
            __props__.__dict__["trusted_device_token_expiration"] = trusted_device_token_expiration
            __props__.__dict__["user_jwt_template"] = user_jwt_template
        super(SessionSettings, __self__).__init__(
            'descope:index/sessionSettings:SessionSettings',
            resource_name,
            __props__,
            opts)

    @staticmethod
    def get(resource_name: str,
            id: pulumi.Input[str],
            opts: Optional[pulumi.ResourceOptions] = None,
            access_key_jwt_template: pulumi.Input[Optional[_builtins.str]] = None,
            access_key_session_token_expiration: pulumi.Input[Optional[_builtins.str]] = None,
            enable_inactivity: pulumi.Input[Optional[_builtins.bool]] = None,
            inactivity_time: pulumi.Input[Optional[_builtins.str]] = None,
            project_id: pulumi.Input[Optional[_builtins.str]] = None,
            refresh_token_cookie_domain: pulumi.Input[Optional[_builtins.str]] = None,
            refresh_token_cookie_policy: pulumi.Input[Optional[_builtins.str]] = None,
            refresh_token_expiration: pulumi.Input[Optional[_builtins.str]] = None,
            refresh_token_response_method: pulumi.Input[Optional[_builtins.str]] = None,
            refresh_token_rotation: pulumi.Input[Optional[_builtins.bool]] = None,
            session_token_cookie_domain: pulumi.Input[Optional[_builtins.str]] = None,
            session_token_cookie_policy: pulumi.Input[Optional[_builtins.str]] = None,
            session_token_expiration: pulumi.Input[Optional[_builtins.str]] = None,
            session_token_response_method: pulumi.Input[Optional[_builtins.str]] = None,
            step_up_token_expiration: pulumi.Input[Optional[_builtins.str]] = None,
            trusted_device_token_expiration: pulumi.Input[Optional[_builtins.str]] = None,
            user_jwt_template: pulumi.Input[Optional[_builtins.str]] = None) -> 'SessionSettings':
        """
        Get an existing SessionSettings resource's state with the given name, id, and optional extra
        properties used to qualify the lookup.

        :param str resource_name: The unique name of the resulting resource.
        :param pulumi.Input[str] id: The unique provider ID of the resource to lookup.
        :param pulumi.ResourceOptions opts: Options for the resource.
        :param pulumi.Input[_builtins.str] access_key_jwt_template: The ID of the JWT template used for access key session tokens.
        :param pulumi.Input[_builtins.str] access_key_session_token_expiration: How long access key session tokens remain valid before they expire.
        :param pulumi.Input[_builtins.bool] enable_inactivity: Whether to detect idle sessions and close them on behalf of the user.
        :param pulumi.Input[_builtins.str] inactivity_time: How long a session can be inactive before it's closed, when `enable_inactivity` is set.
        :param pulumi.Input[_builtins.str] project_id: The ID of the project that these settings belong to. Changing this value will require the resource to be deleted and recreated.
        :param pulumi.Input[_builtins.str] refresh_token_cookie_domain: The domain the refresh token cookie is restricted to.
        :param pulumi.Input[_builtins.str] refresh_token_cookie_policy: The SameSite cookie policy for the refresh token cookie, either `strict`, `lax` or `none`.
        :param pulumi.Input[_builtins.str] refresh_token_expiration: How long refresh tokens remain valid before they expire.
        :param pulumi.Input[_builtins.str] refresh_token_response_method: How refresh tokens are managed by the Descope SDKs, either `response_body` or `cookies`.
        :param pulumi.Input[_builtins.bool] refresh_token_rotation: Whether to rotate the refresh token every time it's used to refresh the session.
        :param pulumi.Input[_builtins.str] session_token_cookie_domain: The domain the session token cookie is restricted to.
        :param pulumi.Input[_builtins.str] session_token_cookie_policy: The SameSite cookie policy for the session token cookie, either `strict`, `lax` or `none`.
        :param pulumi.Input[_builtins.str] session_token_expiration: How long session tokens remain valid before they expire.
        :param pulumi.Input[_builtins.str] session_token_response_method: How session tokens are managed by the Descope SDKs, either `response_body` or `cookies`.
        :param pulumi.Input[_builtins.str] step_up_token_expiration: How long step up tokens remain valid before they expire.
        :param pulumi.Input[_builtins.str] trusted_device_token_expiration: How long trusted device tokens remain valid before they expire.
        :param pulumi.Input[_builtins.str] user_jwt_template: The ID of the JWT template used for user session tokens (e.g. `descope_jwt_template.example.id`).
        """
        opts = pulumi.ResourceOptions.merge(opts, pulumi.ResourceOptions(id=id))

        __props__ = _SessionSettingsState.__new__(_SessionSettingsState)

        __props__.__dict__["access_key_jwt_template"] = access_key_jwt_template
        __props__.__dict__["access_key_session_token_expiration"] = access_key_session_token_expiration
        __props__.__dict__["enable_inactivity"] = enable_inactivity
        __props__.__dict__["inactivity_time"] = inactivity_time
        __props__.__dict__["project_id"] = project_id
        __props__.__dict__["refresh_token_cookie_domain"] = refresh_token_cookie_domain
        __props__.__dict__["refresh_token_cookie_policy"] = refresh_token_cookie_policy
        __props__.__dict__["refresh_token_expiration"] = refresh_token_expiration
        __props__.__dict__["refresh_token_response_method"] = refresh_token_response_method
        __props__.__dict__["refresh_token_rotation"] = refresh_token_rotation
        __props__.__dict__["session_token_cookie_domain"] = session_token_cookie_domain
        __props__.__dict__["session_token_cookie_policy"] = session_token_cookie_policy
        __props__.__dict__["session_token_expiration"] = session_token_expiration
        __props__.__dict__["session_token_response_method"] = session_token_response_method
        __props__.__dict__["step_up_token_expiration"] = step_up_token_expiration
        __props__.__dict__["trusted_device_token_expiration"] = trusted_device_token_expiration
        __props__.__dict__["user_jwt_template"] = user_jwt_template
        return SessionSettings(resource_name, opts=opts, __props__=__props__)

    @_builtins.property
    @pulumi.getter(name="accessKeyJwtTemplate")
    def access_key_jwt_template(self) -> pulumi.Output[_builtins.str]:
        """
        The ID of the JWT template used for access key session tokens.
        """
        return pulumi.get(self, "access_key_jwt_template")

    @_builtins.property
    @pulumi.getter(name="accessKeySessionTokenExpiration")
    def access_key_session_token_expiration(self) -> pulumi.Output[_builtins.str]:
        """
        How long access key session tokens remain valid before they expire.
        """
        return pulumi.get(self, "access_key_session_token_expiration")

    @_builtins.property
    @pulumi.getter(name="enableInactivity")
    def enable_inactivity(self) -> pulumi.Output[_builtins.bool]:
        """
        Whether to detect idle sessions and close them on behalf of the user.
        """
        return pulumi.get(self, "enable_inactivity")

    @_builtins.property
    @pulumi.getter(name="inactivityTime")
    def inactivity_time(self) -> pulumi.Output[_builtins.str]:
        """
        How long a session can be inactive before it's closed, when `enable_inactivity` is set.
        """
        return pulumi.get(self, "inactivity_time")

    @_builtins.property
    @pulumi.getter(name="projectId")
    def project_id(self) -> pulumi.Output[_builtins.str]:
        """
        The ID of the project that these settings belong to. Changing this value will require the resource to be deleted and recreated.
        """
        return pulumi.get(self, "project_id")

    @_builtins.property
    @pulumi.getter(name="refreshTokenCookieDomain")
    def refresh_token_cookie_domain(self) -> pulumi.Output[_builtins.str]:
        """
        The domain the refresh token cookie is restricted to.
        """
        return pulumi.get(self, "refresh_token_cookie_domain")

    @_builtins.property
    @pulumi.getter(name="refreshTokenCookiePolicy")
    def refresh_token_cookie_policy(self) -> pulumi.Output[_builtins.str]:
        """
        The SameSite cookie policy for the refresh token cookie, either `strict`, `lax` or `none`.
        """
        return pulumi.get(self, "refresh_token_cookie_policy")

    @_builtins.property
    @pulumi.getter(name="refreshTokenExpiration")
    def refresh_token_expiration(self) -> pulumi.Output[_builtins.str]:
        """
        How long refresh tokens remain valid before they expire.
        """
        return pulumi.get(self, "refresh_token_expiration")

    @_builtins.property
    @pulumi.getter(name="refreshTokenResponseMethod")
    def refresh_token_response_method(self) -> pulumi.Output[_builtins.str]:
        """
        How refresh tokens are managed by the Descope SDKs, either `response_body` or `cookies`.
        """
        return pulumi.get(self, "refresh_token_response_method")

    @_builtins.property
    @pulumi.getter(name="refreshTokenRotation")
    def refresh_token_rotation(self) -> pulumi.Output[_builtins.bool]:
        """
        Whether to rotate the refresh token every time it's used to refresh the session.
        """
        return pulumi.get(self, "refresh_token_rotation")

    @_builtins.property
    @pulumi.getter(name="sessionTokenCookieDomain")
    def session_token_cookie_domain(self) -> pulumi.Output[_builtins.str]:
        """
        The domain the session token cookie is restricted to.
        """
        return pulumi.get(self, "session_token_cookie_domain")

    @_builtins.property
    @pulumi.getter(name="sessionTokenCookiePolicy")
    def session_token_cookie_policy(self) -> pulumi.Output[_builtins.str]:
        """
        The SameSite cookie policy for the session token cookie, either `strict`, `lax` or `none`.
        """
        return pulumi.get(self, "session_token_cookie_policy")

    @_builtins.property
    @pulumi.getter(name="sessionTokenExpiration")
    def session_token_expiration(self) -> pulumi.Output[_builtins.str]:
        """
        How long session tokens remain valid before they expire.
        """
        return pulumi.get(self, "session_token_expiration")

    @_builtins.property
    @pulumi.getter(name="sessionTokenResponseMethod")
    def session_token_response_method(self) -> pulumi.Output[_builtins.str]:
        """
        How session tokens are managed by the Descope SDKs, either `response_body` or `cookies`.
        """
        return pulumi.get(self, "session_token_response_method")

    @_builtins.property
    @pulumi.getter(name="stepUpTokenExpiration")
    def step_up_token_expiration(self) -> pulumi.Output[_builtins.str]:
        """
        How long step up tokens remain valid before they expire.
        """
        return pulumi.get(self, "step_up_token_expiration")

    @_builtins.property
    @pulumi.getter(name="trustedDeviceTokenExpiration")
    def trusted_device_token_expiration(self) -> pulumi.Output[_builtins.str]:
        """
        How long trusted device tokens remain valid before they expire.
        """
        return pulumi.get(self, "trusted_device_token_expiration")

    @_builtins.property
    @pulumi.getter(name="userJwtTemplate")
    def user_jwt_template(self) -> pulumi.Output[_builtins.str]:
        """
        The ID of the JWT template used for user session tokens (e.g. `descope_jwt_template.example.id`).
        """
        return pulumi.get(self, "user_jwt_template")

