// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.descope.pulumi.descope;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Import;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import java.lang.Boolean;
import java.lang.String;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;


public final class IntercomConnectorArgs extends com.pulumi.resources.ResourceArgs {

    public static final IntercomConnectorArgs Empty = new IntercomConnectorArgs();

    /**
     * A description of what your connector is used for.
     * 
     */
    @Import(name="description")
    private @Nullable Output<String> description;

    /**
     * @return A description of what your connector is used for.
     * 
     */
    public Optional<Output<String>> description() {
        return Optional.ofNullable(this.description);
    }

    /**
     * Whether the connector is disabled. This can be used to temporarily stop a connector from executing without fully deleting it.
     * 
     */
    @Import(name="disabled")
    private @Nullable Output<Boolean> disabled;

    /**
     * @return Whether the connector is disabled. This can be used to temporarily stop a connector from executing without fully deleting it.
     * 
     */
    public Optional<Output<Boolean>> disabled() {
        return Optional.ofNullable(this.disabled);
    }

    /**
     * A custom name for your connector.
     * 
     */
    @Import(name="name")
    private @Nullable Output<String> name;

    /**
     * @return A custom name for your connector.
     * 
     */
    public Optional<Output<String>> name() {
        return Optional.ofNullable(this.name);
    }

    /**
     * The ID of the Descope project that the connector belongs to. Changing this value will require the resource to be deleted and recreated.
     * 
     */
    @Import(name="projectId", required=true)
    private Output<String> projectId;

    /**
     * @return The ID of the Descope project that the connector belongs to. Changing this value will require the resource to be deleted and recreated.
     * 
     */
    public Output<String> projectId() {
        return this.projectId;
    }

    /**
     * Regional Hosting - US, EU, or AU. default: US
     * 
     */
    @Import(name="region")
    private @Nullable Output<String> region;

    /**
     * @return Regional Hosting - US, EU, or AU. default: US
     * 
     */
    public Optional<Output<String>> region() {
        return Optional.ofNullable(this.region);
    }

    /**
     * The Intercom access token.
     * 
     */
    @Import(name="token", required=true)
    private Output<String> token;

    /**
     * @return The Intercom access token.
     * 
     */
    public Output<String> token() {
        return this.token;
    }

    private IntercomConnectorArgs() {}

    private IntercomConnectorArgs(IntercomConnectorArgs $) {
        this.description = $.description;
        this.disabled = $.disabled;
        this.name = $.name;
        this.projectId = $.projectId;
        this.region = $.region;
        this.token = $.token;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(IntercomConnectorArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private IntercomConnectorArgs $;

        public Builder() {
            $ = new IntercomConnectorArgs();
        }

        public Builder(IntercomConnectorArgs defaults) {
            $ = new IntercomConnectorArgs(Objects.requireNonNull(defaults));
        }

        /**
         * @param description A description of what your connector is used for.
         * 
         * @return builder
         * 
         */
        public Builder description(@Nullable Output<String> description) {
            $.description = description;
            return this;
        }

        /**
         * @param description A description of what your connector is used for.
         * 
         * @return builder
         * 
         */
        public Builder description(String description) {
            return description(Output.of(description));
        }

        /**
         * @param disabled Whether the connector is disabled. This can be used to temporarily stop a connector from executing without fully deleting it.
         * 
         * @return builder
         * 
         */
        public Builder disabled(@Nullable Output<Boolean> disabled) {
            $.disabled = disabled;
            return this;
        }

        /**
         * @param disabled Whether the connector is disabled. This can be used to temporarily stop a connector from executing without fully deleting it.
         * 
         * @return builder
         * 
         */
        public Builder disabled(Boolean disabled) {
            return disabled(Output.of(disabled));
        }

        /**
         * @param name A custom name for your connector.
         * 
         * @return builder
         * 
         */
        public Builder name(@Nullable Output<String> name) {
            $.name = name;
            return this;
        }

        /**
         * @param name A custom name for your connector.
         * 
         * @return builder
         * 
         */
        public Builder name(String name) {
            return name(Output.of(name));
        }

        /**
         * @param projectId The ID of the Descope project that the connector belongs to. Changing this value will require the resource to be deleted and recreated.
         * 
         * @return builder
         * 
         */
        public Builder projectId(Output<String> projectId) {
            $.projectId = projectId;
            return this;
        }

        /**
         * @param projectId The ID of the Descope project that the connector belongs to. Changing this value will require the resource to be deleted and recreated.
         * 
         * @return builder
         * 
         */
        public Builder projectId(String projectId) {
            return projectId(Output.of(projectId));
        }

        /**
         * @param region Regional Hosting - US, EU, or AU. default: US
         * 
         * @return builder
         * 
         */
        public Builder region(@Nullable Output<String> region) {
            $.region = region;
            return this;
        }

        /**
         * @param region Regional Hosting - US, EU, or AU. default: US
         * 
         * @return builder
         * 
         */
        public Builder region(String region) {
            return region(Output.of(region));
        }

        /**
         * @param token The Intercom access token.
         * 
         * @return builder
         * 
         */
        public Builder token(Output<String> token) {
            $.token = token;
            return this;
        }

        /**
         * @param token The Intercom access token.
         * 
         * @return builder
         * 
         */
        public Builder token(String token) {
            return token(Output.of(token));
        }

        public IntercomConnectorArgs build() {
            if ($.projectId == null) {
                throw new MissingRequiredPropertyException("IntercomConnectorArgs", "projectId");
            }
            if ($.token == null) {
                throw new MissingRequiredPropertyException("IntercomConnectorArgs", "token");
            }
            return $;
        }
    }

}
