// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.descope.pulumi.descope;

import com.descope.pulumi.descope.OauthSettingsArgs;
import com.descope.pulumi.descope.Utilities;
import com.descope.pulumi.descope.inputs.OauthSettingsState;
import com.pulumi.core.Output;
import com.pulumi.core.annotations.Export;
import com.pulumi.core.annotations.ResourceType;
import com.pulumi.core.internal.Codegen;
import java.lang.Boolean;
import java.lang.String;
import javax.annotation.Nullable;

/**
 * Manages the project-level OAuth authentication settings. This is a singleton resource, and its id is always the project ID. Individual OAuth providers are managed with the descope.OauthProvider resource.
 * 
 */
@ResourceType(type="descope:index/oauthSettings:OauthSettings")
public class OauthSettings extends com.pulumi.resources.CustomResource {
    /**
     * Setting this to `true` will disallow using OAuth authentication directly via API and SDK calls. Note that this does not affect authentication flows that are configured to use OAuth.
     * 
     */
    @Export(name="disabled", refs={Boolean.class}, tree="[0]")
    private Output<Boolean> disabled;

    /**
     * @return Setting this to `true` will disallow using OAuth authentication directly via API and SDK calls. Note that this does not affect authentication flows that are configured to use OAuth.
     * 
     */
    public Output<Boolean> disabled() {
        return this.disabled;
    }
    /**
     * The ID of the project that these settings belong to. Changing this value will require the resource to be deleted and recreated.
     * 
     */
    @Export(name="projectId", refs={String.class}, tree="[0]")
    private Output<String> projectId;

    /**
     * @return The ID of the project that these settings belong to. Changing this value will require the resource to be deleted and recreated.
     * 
     */
    public Output<String> projectId() {
        return this.projectId;
    }

    /**
     *
     * @param name The _unique_ name of the resulting resource.
     */
    public OauthSettings(java.lang.String name) {
        this(name, OauthSettingsArgs.Empty);
    }
    /**
     *
     * @param name The _unique_ name of the resulting resource.
     * @param args The arguments to use to populate this resource's properties.
     */
    public OauthSettings(java.lang.String name, OauthSettingsArgs args) {
        this(name, args, null);
    }
    /**
     *
     * @param name The _unique_ name of the resulting resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param options A bag of options that control this resource's behavior.
     */
    public OauthSettings(java.lang.String name, OauthSettingsArgs args, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        super("descope:index/oauthSettings:OauthSettings", name, makeArgs(args, options), makeResourceOptions(options, Codegen.empty()), false);
    }

    private OauthSettings(java.lang.String name, Output<java.lang.String> id, @Nullable OauthSettingsState state, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        super("descope:index/oauthSettings:OauthSettings", name, state, makeResourceOptions(options, id), false);
    }

    private static OauthSettingsArgs makeArgs(OauthSettingsArgs args, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        if (options != null && options.getUrn().isPresent()) {
            return null;
        }
        return args == null ? OauthSettingsArgs.Empty : args;
    }

    private static com.pulumi.resources.CustomResourceOptions makeResourceOptions(@Nullable com.pulumi.resources.CustomResourceOptions options, @Nullable Output<java.lang.String> id) {
        var defaultOptions = com.pulumi.resources.CustomResourceOptions.builder()
            .version(Utilities.getVersion())
            .pluginDownloadURL("github://api.github.com/descope")
            .build();
        return com.pulumi.resources.CustomResourceOptions.merge(defaultOptions, options, id);
    }

    /**
     * Get an existing Host resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state
     * @param options Optional settings to control the behavior of the CustomResource.
     */
    public static OauthSettings get(java.lang.String name, Output<java.lang.String> id, @Nullable OauthSettingsState state, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        return new OauthSettings(name, id, state, options);
    }
}
