// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.descope.pulumi.descope;

import com.descope.pulumi.descope.OtpSettingsArgs;
import com.descope.pulumi.descope.Utilities;
import com.descope.pulumi.descope.inputs.OtpSettingsState;
import com.pulumi.core.Output;
import com.pulumi.core.annotations.Export;
import com.pulumi.core.annotations.ResourceType;
import com.pulumi.core.internal.Codegen;
import java.lang.Boolean;
import java.lang.String;
import javax.annotation.Nullable;

/**
 * Manages the project-level one-time passcode authentication settings. This is a singleton resource, and its id is always the project ID.
 * 
 */
@ResourceType(type="descope:index/otpSettings:OtpSettings")
public class OtpSettings extends com.pulumi.resources.CustomResource {
    /**
     * Setting this to `true` will disallow using OTP authentication directly via API and SDK calls. Note that this does not affect authentication flows that are configured to use OTP.
     * 
     */
    @Export(name="disabled", refs={Boolean.class}, tree="[0]")
    private Output<Boolean> disabled;

    /**
     * @return Setting this to `true` will disallow using OTP authentication directly via API and SDK calls. Note that this does not affect authentication flows that are configured to use OTP.
     * 
     */
    public Output<Boolean> disabled() {
        return this.disabled;
    }
    /**
     * The domain to embed in OTP messages.
     * 
     */
    @Export(name="domain", refs={String.class}, tree="[0]")
    private Output<String> domain;

    /**
     * @return The domain to embed in OTP messages.
     * 
     */
    public Output<String> domain() {
        return this.domain;
    }
    /**
     * The ID of an email connector to use for sending emails. An empty value (the default) selects the built-in Descope delivery service.
     * 
     */
    @Export(name="emailConnectorId", refs={String.class}, tree="[0]")
    private Output<String> emailConnectorId;

    /**
     * @return The ID of an email connector to use for sending emails. An empty value (the default) selects the built-in Descope delivery service.
     * 
     */
    public Output<String> emailConnectorId() {
        return this.emailConnectorId;
    }
    /**
     * The ID of the email template to send to users, taken from a `descope.EmailTemplate` resource with its `method` set to `otp`. An empty value (the default) selects the built-in System template.
     * 
     */
    @Export(name="emailTemplateId", refs={String.class}, tree="[0]")
    private Output<String> emailTemplateId;

    /**
     * @return The ID of the email template to send to users, taken from a `descope.EmailTemplate` resource with its `method` set to `otp`. An empty value (the default) selects the built-in System template.
     * 
     */
    public Output<String> emailTemplateId() {
        return this.emailTemplateId;
    }
    /**
     * The amount of time that an OTP code will be valid for.
     * 
     */
    @Export(name="expirationTime", refs={String.class}, tree="[0]")
    private Output<String> expirationTime;

    /**
     * @return The amount of time that an OTP code will be valid for.
     * 
     */
    public Output<String> expirationTime() {
        return this.expirationTime;
    }
    /**
     * The ID of the project that these settings belong to. Changing this value will require the resource to be deleted and recreated.
     * 
     */
    @Export(name="projectId", refs={String.class}, tree="[0]")
    private Output<String> projectId;

    /**
     * @return The ID of the project that these settings belong to. Changing this value will require the resource to be deleted and recreated.
     * 
     */
    public Output<String> projectId() {
        return this.projectId;
    }
    /**
     * The ID of an SMS connector to use for sending text messages. An empty value (the default) selects the built-in Descope delivery service.
     * 
     */
    @Export(name="textConnectorId", refs={String.class}, tree="[0]")
    private Output<String> textConnectorId;

    /**
     * @return The ID of an SMS connector to use for sending text messages. An empty value (the default) selects the built-in Descope delivery service.
     * 
     */
    public Output<String> textConnectorId() {
        return this.textConnectorId;
    }
    /**
     * The ID of the text template to send to users, taken from a `descope.TextTemplate` resource with its `method` set to `otp`. An empty value (the default) selects the built-in System template.
     * 
     */
    @Export(name="textTemplateId", refs={String.class}, tree="[0]")
    private Output<String> textTemplateId;

    /**
     * @return The ID of the text template to send to users, taken from a `descope.TextTemplate` resource with its `method` set to `otp`. An empty value (the default) selects the built-in System template.
     * 
     */
    public Output<String> textTemplateId() {
        return this.textTemplateId;
    }
    /**
     * The ID of a voice call connector to use for making voice calls. An empty value (the default) selects the built-in Descope delivery service.
     * 
     */
    @Export(name="voiceConnectorId", refs={String.class}, tree="[0]")
    private Output<String> voiceConnectorId;

    /**
     * @return The ID of a voice call connector to use for making voice calls. An empty value (the default) selects the built-in Descope delivery service.
     * 
     */
    public Output<String> voiceConnectorId() {
        return this.voiceConnectorId;
    }
    /**
     * The ID of the voice template to use in calls to users, taken from a `descope.VoiceTemplate` resource with its `method` set to `otp`. An empty value (the default) selects the built-in System template.
     * 
     */
    @Export(name="voiceTemplateId", refs={String.class}, tree="[0]")
    private Output<String> voiceTemplateId;

    /**
     * @return The ID of the voice template to use in calls to users, taken from a `descope.VoiceTemplate` resource with its `method` set to `otp`. An empty value (the default) selects the built-in System template.
     * 
     */
    public Output<String> voiceTemplateId() {
        return this.voiceTemplateId;
    }

    /**
     *
     * @param name The _unique_ name of the resulting resource.
     */
    public OtpSettings(java.lang.String name) {
        this(name, OtpSettingsArgs.Empty);
    }
    /**
     *
     * @param name The _unique_ name of the resulting resource.
     * @param args The arguments to use to populate this resource's properties.
     */
    public OtpSettings(java.lang.String name, OtpSettingsArgs args) {
        this(name, args, null);
    }
    /**
     *
     * @param name The _unique_ name of the resulting resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param options A bag of options that control this resource's behavior.
     */
    public OtpSettings(java.lang.String name, OtpSettingsArgs args, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        super("descope:index/otpSettings:OtpSettings", name, makeArgs(args, options), makeResourceOptions(options, Codegen.empty()), false);
    }

    private OtpSettings(java.lang.String name, Output<java.lang.String> id, @Nullable OtpSettingsState state, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        super("descope:index/otpSettings:OtpSettings", name, state, makeResourceOptions(options, id), false);
    }

    private static OtpSettingsArgs makeArgs(OtpSettingsArgs args, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        if (options != null && options.getUrn().isPresent()) {
            return null;
        }
        return args == null ? OtpSettingsArgs.Empty : args;
    }

    private static com.pulumi.resources.CustomResourceOptions makeResourceOptions(@Nullable com.pulumi.resources.CustomResourceOptions options, @Nullable Output<java.lang.String> id) {
        var defaultOptions = com.pulumi.resources.CustomResourceOptions.builder()
            .version(Utilities.getVersion())
            .pluginDownloadURL("github://api.github.com/descope")
            .build();
        return com.pulumi.resources.CustomResourceOptions.merge(defaultOptions, options, id);
    }

    /**
     * Get an existing Host resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state
     * @param options Optional settings to control the behavior of the CustomResource.
     */
    public static OtpSettings get(java.lang.String name, Output<java.lang.String> id, @Nullable OtpSettingsState state, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        return new OtpSettings(name, id, state, options);
    }
}
