// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.descope.pulumi.descope;

import com.descope.pulumi.descope.TwilioVerifyConnectorArgs;
import com.descope.pulumi.descope.Utilities;
import com.descope.pulumi.descope.inputs.TwilioVerifyConnectorState;
import com.pulumi.core.Output;
import com.pulumi.core.annotations.Export;
import com.pulumi.core.annotations.ResourceType;
import com.pulumi.core.internal.Codegen;
import java.lang.String;
import java.util.List;
import javax.annotation.Nullable;

/**
 * Manages a Twilio Verify connector and its configuration in a Descope project. Send verification codes through the Twilio Verify service.
 * 
 */
@ResourceType(type="descope:index/twilioVerifyConnector:TwilioVerifyConnector")
public class TwilioVerifyConnector extends com.pulumi.resources.CustomResource {
    /**
     * The Twilio account SID.
     * 
     */
    @Export(name="accountSid", refs={String.class}, tree="[0]")
    private Output<String> accountSid;

    /**
     * @return The Twilio account SID.
     * 
     */
    public Output<String> accountSid() {
        return this.accountSid;
    }
    /**
     * The Twilio API key. Set together with an API secret instead of an auth token.
     * 
     */
    @Export(name="apiKey", refs={String.class}, tree="[0]")
    private Output<String> apiKey;

    /**
     * @return The Twilio API key. Set together with an API secret instead of an auth token.
     * 
     */
    public Output<String> apiKey() {
        return this.apiKey;
    }
    /**
     * The Twilio API secret. Set together with an API key instead of an auth token.
     * 
     */
    @Export(name="apiSecret", refs={String.class}, tree="[0]")
    private Output<String> apiSecret;

    /**
     * @return The Twilio API secret. Set together with an API key instead of an auth token.
     * 
     */
    public Output<String> apiSecret() {
        return this.apiSecret;
    }
    /**
     * The Twilio auth token. Set either this or an API key and secret pair.
     * 
     */
    @Export(name="authToken", refs={String.class}, tree="[0]")
    private Output<String> authToken;

    /**
     * @return The Twilio auth token. Set either this or an API key and secret pair.
     * 
     */
    public Output<String> authToken() {
        return this.authToken;
    }
    /**
     * A description of what your connector is used for.
     * 
     */
    @Export(name="description", refs={String.class}, tree="[0]")
    private Output<String> description;

    /**
     * @return A description of what your connector is used for.
     * 
     */
    public Output<String> description() {
        return this.description;
    }
    /**
     * A custom name for your connector.
     * 
     */
    @Export(name="name", refs={String.class}, tree="[0]")
    private Output<String> name;

    /**
     * @return A custom name for your connector.
     * 
     */
    public Output<String> name() {
        return this.name;
    }
    /**
     * The ID of the Descope project that the connector belongs to. Changing this value will require the resource to be deleted and recreated.
     * 
     */
    @Export(name="projectId", refs={String.class}, tree="[0]")
    private Output<String> projectId;

    /**
     * @return The ID of the Descope project that the connector belongs to. Changing this value will require the resource to be deleted and recreated.
     * 
     */
    public Output<String> projectId() {
        return this.projectId;
    }
    /**
     * The sender shown as the origin of the verification messages, where supported.
     * 
     */
    @Export(name="sender", refs={String.class}, tree="[0]")
    private Output<String> sender;

    /**
     * @return The sender shown as the origin of the verification messages, where supported.
     * 
     */
    public Output<String> sender() {
        return this.sender;
    }
    /**
     * The Twilio Verify service SID used to send verification codes.
     * 
     */
    @Export(name="serviceSid", refs={String.class}, tree="[0]")
    private Output<String> serviceSid;

    /**
     * @return The Twilio Verify service SID used to send verification codes.
     * 
     */
    public Output<String> serviceSid() {
        return this.serviceSid;
    }

    /**
     *
     * @param name The _unique_ name of the resulting resource.
     */
    public TwilioVerifyConnector(java.lang.String name) {
        this(name, TwilioVerifyConnectorArgs.Empty);
    }
    /**
     *
     * @param name The _unique_ name of the resulting resource.
     * @param args The arguments to use to populate this resource's properties.
     */
    public TwilioVerifyConnector(java.lang.String name, TwilioVerifyConnectorArgs args) {
        this(name, args, null);
    }
    /**
     *
     * @param name The _unique_ name of the resulting resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param options A bag of options that control this resource's behavior.
     */
    public TwilioVerifyConnector(java.lang.String name, TwilioVerifyConnectorArgs args, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        super("descope:index/twilioVerifyConnector:TwilioVerifyConnector", name, makeArgs(args, options), makeResourceOptions(options, Codegen.empty()), false);
    }

    private TwilioVerifyConnector(java.lang.String name, Output<java.lang.String> id, @Nullable TwilioVerifyConnectorState state, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        super("descope:index/twilioVerifyConnector:TwilioVerifyConnector", name, state, makeResourceOptions(options, id), false);
    }

    private static TwilioVerifyConnectorArgs makeArgs(TwilioVerifyConnectorArgs args, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        if (options != null && options.getUrn().isPresent()) {
            return null;
        }
        return args == null ? TwilioVerifyConnectorArgs.Empty : args;
    }

    private static com.pulumi.resources.CustomResourceOptions makeResourceOptions(@Nullable com.pulumi.resources.CustomResourceOptions options, @Nullable Output<java.lang.String> id) {
        var defaultOptions = com.pulumi.resources.CustomResourceOptions.builder()
            .version(Utilities.getVersion())
            .pluginDownloadURL("github://api.github.com/descope")
            .additionalSecretOutputs(List.of(
                "apiKey",
                "apiSecret",
                "authToken"
            ))
            .build();
        return com.pulumi.resources.CustomResourceOptions.merge(defaultOptions, options, id);
    }

    /**
     * Get an existing Host resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state
     * @param options Optional settings to control the behavior of the CustomResource.
     */
    public static TwilioVerifyConnector get(java.lang.String name, Output<java.lang.String> id, @Nullable TwilioVerifyConnectorState state, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        return new TwilioVerifyConnector(name, id, state, options);
    }
}
