// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package descope

import (
	"context"
	"reflect"

	"errors"
	"github.com/descope/pulumi-descope/sdk/go/descope/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

// Manages a Datadog connector and its configuration in a Descope project. Stream authentication audit logs with the Datadog connector.
type DatadogConnector struct {
	pulumi.CustomResourceState

	// The unique Datadog organization key.
	ApiKey pulumi.StringOutput `pulumi:"apiKey"`
	// Whether to enable streaming of audit events.
	AuditEnabled pulumi.BoolOutput `pulumi:"auditEnabled"`
	// Specify which events will be sent to the external audit service (including tenant selection).
	AuditFilters DatadogConnectorAuditFilterArrayOutput `pulumi:"auditFilters"`
	// A description of what your connector is used for.
	Description pulumi.StringOutput `pulumi:"description"`
	// Whether the connector is disabled. This can be used to temporarily stop a connector from executing without fully deleting it.
	Disabled pulumi.BoolOutput `pulumi:"disabled"`
	// Whether to mask personally identifiable information in the logs.
	MaskPii pulumi.BoolOutput `pulumi:"maskPii"`
	// A custom name for your connector.
	Name pulumi.StringOutput `pulumi:"name"`
	// The ID of the Descope project that the connector belongs to. Changing this value will require the resource to be deleted and recreated.
	ProjectId pulumi.StringOutput `pulumi:"projectId"`
	// The Datadog site to send logs to. Default is `datadoghq.com`. European, free tier and other customers should set their site accordingly.
	Site pulumi.StringOutput `pulumi:"site"`
	// An optional custom source to use for log entries sent to Datadog. This can be used to differentiate between environments (e.g. `production`, `staging`). If left empty, the default Descope source will be used.
	Source pulumi.StringOutput `pulumi:"source"`
	// An optional comma-separated list of tags to append to all log entries sent to Datadog (e.g. `env:production,team:auth`). These are added in addition to any default tags. If left empty, only the default Descope tags will be used.
	Tags pulumi.StringOutput `pulumi:"tags"`
	// Whether to send troubleshooting events.
	TroubleshootLogEnabled pulumi.BoolOutput `pulumi:"troubleshootLogEnabled"`
}

// NewDatadogConnector registers a new resource with the given unique name, arguments, and options.
func NewDatadogConnector(ctx *pulumi.Context,
	name string, args *DatadogConnectorArgs, opts ...pulumi.ResourceOption) (*DatadogConnector, error) {
	if args == nil {
		return nil, errors.New("missing one or more required arguments")
	}

	if args.ApiKey == nil {
		return nil, errors.New("invalid value for required argument 'ApiKey'")
	}
	if args.ProjectId == nil {
		return nil, errors.New("invalid value for required argument 'ProjectId'")
	}
	if args.ApiKey != nil {
		args.ApiKey = pulumi.ToSecret(args.ApiKey).(pulumi.StringInput)
	}
	secrets := pulumi.AdditionalSecretOutputs([]string{
		"apiKey",
	})
	opts = append(opts, secrets)
	opts = internal.PkgResourceDefaultOpts(opts)
	var resource DatadogConnector
	err := ctx.RegisterResource("descope:index/datadogConnector:DatadogConnector", name, args, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// GetDatadogConnector gets an existing DatadogConnector resource's state with the given name, ID, and optional
// state properties that are used to uniquely qualify the lookup (nil if not required).
func GetDatadogConnector(ctx *pulumi.Context,
	name string, id pulumi.IDInput, state *DatadogConnectorState, opts ...pulumi.ResourceOption) (*DatadogConnector, error) {
	var resource DatadogConnector
	err := ctx.ReadResource("descope:index/datadogConnector:DatadogConnector", name, id, state, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// Input properties used for looking up and filtering DatadogConnector resources.
type datadogConnectorState struct {
	// The unique Datadog organization key.
	ApiKey *string `pulumi:"apiKey"`
	// Whether to enable streaming of audit events.
	AuditEnabled *bool `pulumi:"auditEnabled"`
	// Specify which events will be sent to the external audit service (including tenant selection).
	AuditFilters []DatadogConnectorAuditFilter `pulumi:"auditFilters"`
	// A description of what your connector is used for.
	Description *string `pulumi:"description"`
	// Whether the connector is disabled. This can be used to temporarily stop a connector from executing without fully deleting it.
	Disabled *bool `pulumi:"disabled"`
	// Whether to mask personally identifiable information in the logs.
	MaskPii *bool `pulumi:"maskPii"`
	// A custom name for your connector.
	Name *string `pulumi:"name"`
	// The ID of the Descope project that the connector belongs to. Changing this value will require the resource to be deleted and recreated.
	ProjectId *string `pulumi:"projectId"`
	// The Datadog site to send logs to. Default is `datadoghq.com`. European, free tier and other customers should set their site accordingly.
	Site *string `pulumi:"site"`
	// An optional custom source to use for log entries sent to Datadog. This can be used to differentiate between environments (e.g. `production`, `staging`). If left empty, the default Descope source will be used.
	Source *string `pulumi:"source"`
	// An optional comma-separated list of tags to append to all log entries sent to Datadog (e.g. `env:production,team:auth`). These are added in addition to any default tags. If left empty, only the default Descope tags will be used.
	Tags *string `pulumi:"tags"`
	// Whether to send troubleshooting events.
	TroubleshootLogEnabled *bool `pulumi:"troubleshootLogEnabled"`
}

type DatadogConnectorState struct {
	// The unique Datadog organization key.
	ApiKey pulumi.StringPtrInput
	// Whether to enable streaming of audit events.
	AuditEnabled pulumi.BoolPtrInput
	// Specify which events will be sent to the external audit service (including tenant selection).
	AuditFilters DatadogConnectorAuditFilterArrayInput
	// A description of what your connector is used for.
	Description pulumi.StringPtrInput
	// Whether the connector is disabled. This can be used to temporarily stop a connector from executing without fully deleting it.
	Disabled pulumi.BoolPtrInput
	// Whether to mask personally identifiable information in the logs.
	MaskPii pulumi.BoolPtrInput
	// A custom name for your connector.
	Name pulumi.StringPtrInput
	// The ID of the Descope project that the connector belongs to. Changing this value will require the resource to be deleted and recreated.
	ProjectId pulumi.StringPtrInput
	// The Datadog site to send logs to. Default is `datadoghq.com`. European, free tier and other customers should set their site accordingly.
	Site pulumi.StringPtrInput
	// An optional custom source to use for log entries sent to Datadog. This can be used to differentiate between environments (e.g. `production`, `staging`). If left empty, the default Descope source will be used.
	Source pulumi.StringPtrInput
	// An optional comma-separated list of tags to append to all log entries sent to Datadog (e.g. `env:production,team:auth`). These are added in addition to any default tags. If left empty, only the default Descope tags will be used.
	Tags pulumi.StringPtrInput
	// Whether to send troubleshooting events.
	TroubleshootLogEnabled pulumi.BoolPtrInput
}

func (DatadogConnectorState) ElementType() reflect.Type {
	return reflect.TypeOf((*datadogConnectorState)(nil)).Elem()
}

type datadogConnectorArgs struct {
	// The unique Datadog organization key.
	ApiKey string `pulumi:"apiKey"`
	// Whether to enable streaming of audit events.
	AuditEnabled *bool `pulumi:"auditEnabled"`
	// Specify which events will be sent to the external audit service (including tenant selection).
	AuditFilters []DatadogConnectorAuditFilter `pulumi:"auditFilters"`
	// A description of what your connector is used for.
	Description *string `pulumi:"description"`
	// Whether the connector is disabled. This can be used to temporarily stop a connector from executing without fully deleting it.
	Disabled *bool `pulumi:"disabled"`
	// Whether to mask personally identifiable information in the logs.
	MaskPii *bool `pulumi:"maskPii"`
	// A custom name for your connector.
	Name *string `pulumi:"name"`
	// The ID of the Descope project that the connector belongs to. Changing this value will require the resource to be deleted and recreated.
	ProjectId string `pulumi:"projectId"`
	// The Datadog site to send logs to. Default is `datadoghq.com`. European, free tier and other customers should set their site accordingly.
	Site *string `pulumi:"site"`
	// An optional custom source to use for log entries sent to Datadog. This can be used to differentiate between environments (e.g. `production`, `staging`). If left empty, the default Descope source will be used.
	Source *string `pulumi:"source"`
	// An optional comma-separated list of tags to append to all log entries sent to Datadog (e.g. `env:production,team:auth`). These are added in addition to any default tags. If left empty, only the default Descope tags will be used.
	Tags *string `pulumi:"tags"`
	// Whether to send troubleshooting events.
	TroubleshootLogEnabled *bool `pulumi:"troubleshootLogEnabled"`
}

// The set of arguments for constructing a DatadogConnector resource.
type DatadogConnectorArgs struct {
	// The unique Datadog organization key.
	ApiKey pulumi.StringInput
	// Whether to enable streaming of audit events.
	AuditEnabled pulumi.BoolPtrInput
	// Specify which events will be sent to the external audit service (including tenant selection).
	AuditFilters DatadogConnectorAuditFilterArrayInput
	// A description of what your connector is used for.
	Description pulumi.StringPtrInput
	// Whether the connector is disabled. This can be used to temporarily stop a connector from executing without fully deleting it.
	Disabled pulumi.BoolPtrInput
	// Whether to mask personally identifiable information in the logs.
	MaskPii pulumi.BoolPtrInput
	// A custom name for your connector.
	Name pulumi.StringPtrInput
	// The ID of the Descope project that the connector belongs to. Changing this value will require the resource to be deleted and recreated.
	ProjectId pulumi.StringInput
	// The Datadog site to send logs to. Default is `datadoghq.com`. European, free tier and other customers should set their site accordingly.
	Site pulumi.StringPtrInput
	// An optional custom source to use for log entries sent to Datadog. This can be used to differentiate between environments (e.g. `production`, `staging`). If left empty, the default Descope source will be used.
	Source pulumi.StringPtrInput
	// An optional comma-separated list of tags to append to all log entries sent to Datadog (e.g. `env:production,team:auth`). These are added in addition to any default tags. If left empty, only the default Descope tags will be used.
	Tags pulumi.StringPtrInput
	// Whether to send troubleshooting events.
	TroubleshootLogEnabled pulumi.BoolPtrInput
}

func (DatadogConnectorArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*datadogConnectorArgs)(nil)).Elem()
}

type DatadogConnectorInput interface {
	pulumi.Input

	ToDatadogConnectorOutput() DatadogConnectorOutput
	ToDatadogConnectorOutputWithContext(ctx context.Context) DatadogConnectorOutput
}

func (*DatadogConnector) ElementType() reflect.Type {
	return reflect.TypeOf((**DatadogConnector)(nil)).Elem()
}

func (i *DatadogConnector) ToDatadogConnectorOutput() DatadogConnectorOutput {
	return i.ToDatadogConnectorOutputWithContext(context.Background())
}

func (i *DatadogConnector) ToDatadogConnectorOutputWithContext(ctx context.Context) DatadogConnectorOutput {
	return pulumi.ToOutputWithContext(ctx, i).(DatadogConnectorOutput)
}

// DatadogConnectorArrayInput is an input type that accepts DatadogConnectorArray and DatadogConnectorArrayOutput values.
// You can construct a concrete instance of `DatadogConnectorArrayInput` via:
//
//	DatadogConnectorArray{ DatadogConnectorArgs{...} }
type DatadogConnectorArrayInput interface {
	pulumi.Input

	ToDatadogConnectorArrayOutput() DatadogConnectorArrayOutput
	ToDatadogConnectorArrayOutputWithContext(context.Context) DatadogConnectorArrayOutput
}

type DatadogConnectorArray []DatadogConnectorInput

func (DatadogConnectorArray) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*DatadogConnector)(nil)).Elem()
}

func (i DatadogConnectorArray) ToDatadogConnectorArrayOutput() DatadogConnectorArrayOutput {
	return i.ToDatadogConnectorArrayOutputWithContext(context.Background())
}

func (i DatadogConnectorArray) ToDatadogConnectorArrayOutputWithContext(ctx context.Context) DatadogConnectorArrayOutput {
	return pulumi.ToOutputWithContext(ctx, i).(DatadogConnectorArrayOutput)
}

// DatadogConnectorMapInput is an input type that accepts DatadogConnectorMap and DatadogConnectorMapOutput values.
// You can construct a concrete instance of `DatadogConnectorMapInput` via:
//
//	DatadogConnectorMap{ "key": DatadogConnectorArgs{...} }
type DatadogConnectorMapInput interface {
	pulumi.Input

	ToDatadogConnectorMapOutput() DatadogConnectorMapOutput
	ToDatadogConnectorMapOutputWithContext(context.Context) DatadogConnectorMapOutput
}

type DatadogConnectorMap map[string]DatadogConnectorInput

func (DatadogConnectorMap) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*DatadogConnector)(nil)).Elem()
}

func (i DatadogConnectorMap) ToDatadogConnectorMapOutput() DatadogConnectorMapOutput {
	return i.ToDatadogConnectorMapOutputWithContext(context.Background())
}

func (i DatadogConnectorMap) ToDatadogConnectorMapOutputWithContext(ctx context.Context) DatadogConnectorMapOutput {
	return pulumi.ToOutputWithContext(ctx, i).(DatadogConnectorMapOutput)
}

type DatadogConnectorOutput struct{ *pulumi.OutputState }

func (DatadogConnectorOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**DatadogConnector)(nil)).Elem()
}

func (o DatadogConnectorOutput) ToDatadogConnectorOutput() DatadogConnectorOutput {
	return o
}

func (o DatadogConnectorOutput) ToDatadogConnectorOutputWithContext(ctx context.Context) DatadogConnectorOutput {
	return o
}

// The unique Datadog organization key.
func (o DatadogConnectorOutput) ApiKey() pulumi.StringOutput {
	return o.ApplyT(func(v *DatadogConnector) pulumi.StringOutput { return v.ApiKey }).(pulumi.StringOutput)
}

// Whether to enable streaming of audit events.
func (o DatadogConnectorOutput) AuditEnabled() pulumi.BoolOutput {
	return o.ApplyT(func(v *DatadogConnector) pulumi.BoolOutput { return v.AuditEnabled }).(pulumi.BoolOutput)
}

// Specify which events will be sent to the external audit service (including tenant selection).
func (o DatadogConnectorOutput) AuditFilters() DatadogConnectorAuditFilterArrayOutput {
	return o.ApplyT(func(v *DatadogConnector) DatadogConnectorAuditFilterArrayOutput { return v.AuditFilters }).(DatadogConnectorAuditFilterArrayOutput)
}

// A description of what your connector is used for.
func (o DatadogConnectorOutput) Description() pulumi.StringOutput {
	return o.ApplyT(func(v *DatadogConnector) pulumi.StringOutput { return v.Description }).(pulumi.StringOutput)
}

// Whether the connector is disabled. This can be used to temporarily stop a connector from executing without fully deleting it.
func (o DatadogConnectorOutput) Disabled() pulumi.BoolOutput {
	return o.ApplyT(func(v *DatadogConnector) pulumi.BoolOutput { return v.Disabled }).(pulumi.BoolOutput)
}

// Whether to mask personally identifiable information in the logs.
func (o DatadogConnectorOutput) MaskPii() pulumi.BoolOutput {
	return o.ApplyT(func(v *DatadogConnector) pulumi.BoolOutput { return v.MaskPii }).(pulumi.BoolOutput)
}

// A custom name for your connector.
func (o DatadogConnectorOutput) Name() pulumi.StringOutput {
	return o.ApplyT(func(v *DatadogConnector) pulumi.StringOutput { return v.Name }).(pulumi.StringOutput)
}

// The ID of the Descope project that the connector belongs to. Changing this value will require the resource to be deleted and recreated.
func (o DatadogConnectorOutput) ProjectId() pulumi.StringOutput {
	return o.ApplyT(func(v *DatadogConnector) pulumi.StringOutput { return v.ProjectId }).(pulumi.StringOutput)
}

// The Datadog site to send logs to. Default is `datadoghq.com`. European, free tier and other customers should set their site accordingly.
func (o DatadogConnectorOutput) Site() pulumi.StringOutput {
	return o.ApplyT(func(v *DatadogConnector) pulumi.StringOutput { return v.Site }).(pulumi.StringOutput)
}

// An optional custom source to use for log entries sent to Datadog. This can be used to differentiate between environments (e.g. `production`, `staging`). If left empty, the default Descope source will be used.
func (o DatadogConnectorOutput) Source() pulumi.StringOutput {
	return o.ApplyT(func(v *DatadogConnector) pulumi.StringOutput { return v.Source }).(pulumi.StringOutput)
}

// An optional comma-separated list of tags to append to all log entries sent to Datadog (e.g. `env:production,team:auth`). These are added in addition to any default tags. If left empty, only the default Descope tags will be used.
func (o DatadogConnectorOutput) Tags() pulumi.StringOutput {
	return o.ApplyT(func(v *DatadogConnector) pulumi.StringOutput { return v.Tags }).(pulumi.StringOutput)
}

// Whether to send troubleshooting events.
func (o DatadogConnectorOutput) TroubleshootLogEnabled() pulumi.BoolOutput {
	return o.ApplyT(func(v *DatadogConnector) pulumi.BoolOutput { return v.TroubleshootLogEnabled }).(pulumi.BoolOutput)
}

type DatadogConnectorArrayOutput struct{ *pulumi.OutputState }

func (DatadogConnectorArrayOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*DatadogConnector)(nil)).Elem()
}

func (o DatadogConnectorArrayOutput) ToDatadogConnectorArrayOutput() DatadogConnectorArrayOutput {
	return o
}

func (o DatadogConnectorArrayOutput) ToDatadogConnectorArrayOutputWithContext(ctx context.Context) DatadogConnectorArrayOutput {
	return o
}

func (o DatadogConnectorArrayOutput) Index(i pulumi.IntInput) DatadogConnectorOutput {
	return pulumi.All(o, i).ApplyT(func(vs []interface{}) *DatadogConnector {
		return vs[0].([]*DatadogConnector)[vs[1].(int)]
	}).(DatadogConnectorOutput)
}

type DatadogConnectorMapOutput struct{ *pulumi.OutputState }

func (DatadogConnectorMapOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*DatadogConnector)(nil)).Elem()
}

func (o DatadogConnectorMapOutput) ToDatadogConnectorMapOutput() DatadogConnectorMapOutput {
	return o
}

func (o DatadogConnectorMapOutput) ToDatadogConnectorMapOutputWithContext(ctx context.Context) DatadogConnectorMapOutput {
	return o
}

func (o DatadogConnectorMapOutput) MapIndex(k pulumi.StringInput) DatadogConnectorOutput {
	return pulumi.All(o, k).ApplyT(func(vs []interface{}) *DatadogConnector {
		return vs[0].(map[string]*DatadogConnector)[vs[1].(string)]
	}).(DatadogConnectorOutput)
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*DatadogConnectorInput)(nil)).Elem(), &DatadogConnector{})
	pulumi.RegisterInputType(reflect.TypeOf((*DatadogConnectorArrayInput)(nil)).Elem(), DatadogConnectorArray{})
	pulumi.RegisterInputType(reflect.TypeOf((*DatadogConnectorMapInput)(nil)).Elem(), DatadogConnectorMap{})
	pulumi.RegisterOutputType(DatadogConnectorOutput{})
	pulumi.RegisterOutputType(DatadogConnectorArrayOutput{})
	pulumi.RegisterOutputType(DatadogConnectorMapOutput{})
}
