// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package descope

import (
	"context"
	"reflect"

	"errors"
	"github.com/descope/pulumi-descope/sdk/go/descope/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

// Manages a single OIDC federated application where Descope acts as the identity provider.
type OidcApp struct {
	pulumi.CustomResourceState

	// A list of approved redirect URLs for this application (supports `*` wildcards). When set, redirect URIs are validated against this per-app list; when empty, validation falls back to the project's approved/trusted domains.
	ApprovedRedirectUrls pulumi.StringArrayOutput `pulumi:"approvedRedirectUrls"`
	// Disables the `authorizationCode` grant type for this application.
	AuthorizationCodeDisabled pulumi.BoolOutput `pulumi:"authorizationCodeDisabled"`
	// The URL that Descope notifies with a logout token when the user's session ends, as per the [OIDC Back-Channel Logout](https://openid.net/specs/openid-connect-backchannel-1_0.html) specification. Leave empty to disable back-channel logout notifications for this application.
	BackchannelLogoutUrl pulumi.StringOutput `pulumi:"backchannelLogoutUrl"`
	// A list of supported claims. e.g. `sub`, `email`, `exp`.
	Claims pulumi.StringArrayOutput `pulumi:"claims"`
	// Disables the `clientCredentials` grant type for this application.
	ClientCredentialsDisabled pulumi.BoolOutput `pulumi:"clientCredentialsDisabled"`
	// A dedicated OIDC `clientId` to import for this application. When omitted, the `clientId` is generated by the server and is not returned on reads. Can only be set when the application is created, and changing it will require the resource to be deleted and recreated.
	ClientId pulumi.StringOutput `pulumi:"clientId"`
	// A dedicated OIDC `clientSecret` to import for this application. When omitted, a secret is generated server-side only for applications with a `confidential` client type, either on creation or when the application is later switched to `confidential`, and fetched into the Terraform state. Applications with other client types don't use a client secret and the value stays empty. The value in the state is never overwritten afterwards, so a secret rotated via the API or the Descope console is not reflected until the resource is replaced. Changing this value will require the resource to be deleted and recreated.
	ClientSecret pulumi.StringOutput `pulumi:"clientSecret"`
	// OAuth client confidentiality. One of `""` (default — legacy access-key authentication), `"confidential"` (a dedicated client secret is generated for the app), or `"public"` (PKCE only, no client secret). Changing this value on an existing application changes how its clients must authenticate, so coordinate the change with the application's developers.
	ClientType pulumi.StringOutput `pulumi:"clientType"`
	// A custom login page URL to redirect users to on IdP-initiated login flows, instead of the default login page.
	CustomIdpInitiatedLoginPageUrl pulumi.StringOutput `pulumi:"customIdpInitiatedLoginPageUrl"`
	// Controls the default `aud` claim of tokens issued for this application. One of `"projectId"` (the project ID only), `"clientId"` (the dedicated client ID only), `"appId"` (the application ID only), `"empty"` (no `aud` claim at all), or `""` (default — both the project ID and the client ID). Only applies to modern apps that set a `clientType`; legacy apps always use the project ID, so the empty default leaves their behavior unchanged.
	DefaultAudience pulumi.StringOutput `pulumi:"defaultAudience"`
	// Protects the application from being accidentally destroyed or replaced. Destroying or replacing a federated application breaks the service provider's configured integration and invalidates its client credentials, so these applications are protected by default. To allow the resource to be destroyed or replaced, for example in ephemeral test environments, set this attribute to `false` and apply the change first.
	DeletionProtection pulumi.BoolPtrOutput `pulumi:"deletionProtection"`
	// A description for the OIDC application.
	Description pulumi.StringOutput `pulumi:"description"`
	// Disables the `urn:ietf:params:oauth:grant-type:device_code` grant type for this application.
	DeviceCodeDisabled pulumi.BoolOutput `pulumi:"deviceCodeDisabled"`
	// Whether the application should be enabled or disabled.
	Disabled pulumi.BoolOutput `pulumi:"disabled"`
	// This configuration overrides the default behavior of the SSO application and forces the user to authenticate via the Descope flow, regardless of the SP's request.
	ForceAuthentication pulumi.BoolOutput `pulumi:"forceAuthentication"`
	// When enabled, the authorization code flow requires PKCE in addition to the normal client authentication. A confidential client must then present both its client secret and a valid PKCE `codeVerifier`. Public clients always use PKCE regardless of this setting.
	ForcePkce pulumi.BoolOutput `pulumi:"forcePkce"`
	// Disables the `urn:ietf:params:oauth:grant-type:jwt-bearer` grant type for this application.
	JwtBearerDisabled pulumi.BoolOutput `pulumi:"jwtBearerDisabled"`
	// The Flow Hosting URL. When left empty the project's default login page URL is used, and the computed value is reflected in this attribute. Read more about using this parameter with custom domain [here](https://docs.descope.com/sso-integrations/applications/saml-apps).
	LoginPageUrl pulumi.StringOutput `pulumi:"loginPageUrl"`
	// A logo for the OIDC application. Should be a hosted image URL.
	Logo pulumi.StringOutput `pulumi:"logo"`
	// A name for the OIDC application.
	Name pulumi.StringOutput `pulumi:"name"`
	// An optional identifier for the application. When omitted, an identifier is generated by the server. Can only be set when the application is created, and changing it will require the resource to be deleted and recreated.
	OidcAppId pulumi.StringOutput `pulumi:"oidcAppId"`
	// The ID of the project that this application belongs to. Changing this value will require the resource to be deleted and recreated.
	ProjectId pulumi.StringOutput `pulumi:"projectId"`
	// Disables the `refreshToken` grant type for this application.
	RefreshTokenDisabled pulumi.BoolOutput `pulumi:"refreshTokenDisabled"`
	// Controls the audience values appended to the issued token's `aud` claim for trusted sibling applications. One of `"projectId"`, `"clientId"`, `"appId"`, `"empty"` (add none), or `""` (default — both the project ID and the client ID). Independent of `defaultAudience`.
	TrustedAppsAudience pulumi.StringOutput `pulumi:"trustedAppsAudience"`
}

// NewOidcApp registers a new resource with the given unique name, arguments, and options.
func NewOidcApp(ctx *pulumi.Context,
	name string, args *OidcAppArgs, opts ...pulumi.ResourceOption) (*OidcApp, error) {
	if args == nil {
		return nil, errors.New("missing one or more required arguments")
	}

	if args.ProjectId == nil {
		return nil, errors.New("invalid value for required argument 'ProjectId'")
	}
	if args.ClientSecret != nil {
		args.ClientSecret = pulumi.ToSecret(args.ClientSecret).(pulumi.StringPtrInput)
	}
	secrets := pulumi.AdditionalSecretOutputs([]string{
		"clientSecret",
	})
	opts = append(opts, secrets)
	opts = internal.PkgResourceDefaultOpts(opts)
	var resource OidcApp
	err := ctx.RegisterResource("descope:index/oidcApp:OidcApp", name, args, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// GetOidcApp gets an existing OidcApp resource's state with the given name, ID, and optional
// state properties that are used to uniquely qualify the lookup (nil if not required).
func GetOidcApp(ctx *pulumi.Context,
	name string, id pulumi.IDInput, state *OidcAppState, opts ...pulumi.ResourceOption) (*OidcApp, error) {
	var resource OidcApp
	err := ctx.ReadResource("descope:index/oidcApp:OidcApp", name, id, state, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// Input properties used for looking up and filtering OidcApp resources.
type oidcAppState struct {
	// A list of approved redirect URLs for this application (supports `*` wildcards). When set, redirect URIs are validated against this per-app list; when empty, validation falls back to the project's approved/trusted domains.
	ApprovedRedirectUrls []string `pulumi:"approvedRedirectUrls"`
	// Disables the `authorizationCode` grant type for this application.
	AuthorizationCodeDisabled *bool `pulumi:"authorizationCodeDisabled"`
	// The URL that Descope notifies with a logout token when the user's session ends, as per the [OIDC Back-Channel Logout](https://openid.net/specs/openid-connect-backchannel-1_0.html) specification. Leave empty to disable back-channel logout notifications for this application.
	BackchannelLogoutUrl *string `pulumi:"backchannelLogoutUrl"`
	// A list of supported claims. e.g. `sub`, `email`, `exp`.
	Claims []string `pulumi:"claims"`
	// Disables the `clientCredentials` grant type for this application.
	ClientCredentialsDisabled *bool `pulumi:"clientCredentialsDisabled"`
	// A dedicated OIDC `clientId` to import for this application. When omitted, the `clientId` is generated by the server and is not returned on reads. Can only be set when the application is created, and changing it will require the resource to be deleted and recreated.
	ClientId *string `pulumi:"clientId"`
	// A dedicated OIDC `clientSecret` to import for this application. When omitted, a secret is generated server-side only for applications with a `confidential` client type, either on creation or when the application is later switched to `confidential`, and fetched into the Terraform state. Applications with other client types don't use a client secret and the value stays empty. The value in the state is never overwritten afterwards, so a secret rotated via the API or the Descope console is not reflected until the resource is replaced. Changing this value will require the resource to be deleted and recreated.
	ClientSecret *string `pulumi:"clientSecret"`
	// OAuth client confidentiality. One of `""` (default — legacy access-key authentication), `"confidential"` (a dedicated client secret is generated for the app), or `"public"` (PKCE only, no client secret). Changing this value on an existing application changes how its clients must authenticate, so coordinate the change with the application's developers.
	ClientType *string `pulumi:"clientType"`
	// A custom login page URL to redirect users to on IdP-initiated login flows, instead of the default login page.
	CustomIdpInitiatedLoginPageUrl *string `pulumi:"customIdpInitiatedLoginPageUrl"`
	// Controls the default `aud` claim of tokens issued for this application. One of `"projectId"` (the project ID only), `"clientId"` (the dedicated client ID only), `"appId"` (the application ID only), `"empty"` (no `aud` claim at all), or `""` (default — both the project ID and the client ID). Only applies to modern apps that set a `clientType`; legacy apps always use the project ID, so the empty default leaves their behavior unchanged.
	DefaultAudience *string `pulumi:"defaultAudience"`
	// Protects the application from being accidentally destroyed or replaced. Destroying or replacing a federated application breaks the service provider's configured integration and invalidates its client credentials, so these applications are protected by default. To allow the resource to be destroyed or replaced, for example in ephemeral test environments, set this attribute to `false` and apply the change first.
	DeletionProtection *bool `pulumi:"deletionProtection"`
	// A description for the OIDC application.
	Description *string `pulumi:"description"`
	// Disables the `urn:ietf:params:oauth:grant-type:device_code` grant type for this application.
	DeviceCodeDisabled *bool `pulumi:"deviceCodeDisabled"`
	// Whether the application should be enabled or disabled.
	Disabled *bool `pulumi:"disabled"`
	// This configuration overrides the default behavior of the SSO application and forces the user to authenticate via the Descope flow, regardless of the SP's request.
	ForceAuthentication *bool `pulumi:"forceAuthentication"`
	// When enabled, the authorization code flow requires PKCE in addition to the normal client authentication. A confidential client must then present both its client secret and a valid PKCE `codeVerifier`. Public clients always use PKCE regardless of this setting.
	ForcePkce *bool `pulumi:"forcePkce"`
	// Disables the `urn:ietf:params:oauth:grant-type:jwt-bearer` grant type for this application.
	JwtBearerDisabled *bool `pulumi:"jwtBearerDisabled"`
	// The Flow Hosting URL. When left empty the project's default login page URL is used, and the computed value is reflected in this attribute. Read more about using this parameter with custom domain [here](https://docs.descope.com/sso-integrations/applications/saml-apps).
	LoginPageUrl *string `pulumi:"loginPageUrl"`
	// A logo for the OIDC application. Should be a hosted image URL.
	Logo *string `pulumi:"logo"`
	// A name for the OIDC application.
	Name *string `pulumi:"name"`
	// An optional identifier for the application. When omitted, an identifier is generated by the server. Can only be set when the application is created, and changing it will require the resource to be deleted and recreated.
	OidcAppId *string `pulumi:"oidcAppId"`
	// The ID of the project that this application belongs to. Changing this value will require the resource to be deleted and recreated.
	ProjectId *string `pulumi:"projectId"`
	// Disables the `refreshToken` grant type for this application.
	RefreshTokenDisabled *bool `pulumi:"refreshTokenDisabled"`
	// Controls the audience values appended to the issued token's `aud` claim for trusted sibling applications. One of `"projectId"`, `"clientId"`, `"appId"`, `"empty"` (add none), or `""` (default — both the project ID and the client ID). Independent of `defaultAudience`.
	TrustedAppsAudience *string `pulumi:"trustedAppsAudience"`
}

type OidcAppState struct {
	// A list of approved redirect URLs for this application (supports `*` wildcards). When set, redirect URIs are validated against this per-app list; when empty, validation falls back to the project's approved/trusted domains.
	ApprovedRedirectUrls pulumi.StringArrayInput
	// Disables the `authorizationCode` grant type for this application.
	AuthorizationCodeDisabled pulumi.BoolPtrInput
	// The URL that Descope notifies with a logout token when the user's session ends, as per the [OIDC Back-Channel Logout](https://openid.net/specs/openid-connect-backchannel-1_0.html) specification. Leave empty to disable back-channel logout notifications for this application.
	BackchannelLogoutUrl pulumi.StringPtrInput
	// A list of supported claims. e.g. `sub`, `email`, `exp`.
	Claims pulumi.StringArrayInput
	// Disables the `clientCredentials` grant type for this application.
	ClientCredentialsDisabled pulumi.BoolPtrInput
	// A dedicated OIDC `clientId` to import for this application. When omitted, the `clientId` is generated by the server and is not returned on reads. Can only be set when the application is created, and changing it will require the resource to be deleted and recreated.
	ClientId pulumi.StringPtrInput
	// A dedicated OIDC `clientSecret` to import for this application. When omitted, a secret is generated server-side only for applications with a `confidential` client type, either on creation or when the application is later switched to `confidential`, and fetched into the Terraform state. Applications with other client types don't use a client secret and the value stays empty. The value in the state is never overwritten afterwards, so a secret rotated via the API or the Descope console is not reflected until the resource is replaced. Changing this value will require the resource to be deleted and recreated.
	ClientSecret pulumi.StringPtrInput
	// OAuth client confidentiality. One of `""` (default — legacy access-key authentication), `"confidential"` (a dedicated client secret is generated for the app), or `"public"` (PKCE only, no client secret). Changing this value on an existing application changes how its clients must authenticate, so coordinate the change with the application's developers.
	ClientType pulumi.StringPtrInput
	// A custom login page URL to redirect users to on IdP-initiated login flows, instead of the default login page.
	CustomIdpInitiatedLoginPageUrl pulumi.StringPtrInput
	// Controls the default `aud` claim of tokens issued for this application. One of `"projectId"` (the project ID only), `"clientId"` (the dedicated client ID only), `"appId"` (the application ID only), `"empty"` (no `aud` claim at all), or `""` (default — both the project ID and the client ID). Only applies to modern apps that set a `clientType`; legacy apps always use the project ID, so the empty default leaves their behavior unchanged.
	DefaultAudience pulumi.StringPtrInput
	// Protects the application from being accidentally destroyed or replaced. Destroying or replacing a federated application breaks the service provider's configured integration and invalidates its client credentials, so these applications are protected by default. To allow the resource to be destroyed or replaced, for example in ephemeral test environments, set this attribute to `false` and apply the change first.
	DeletionProtection pulumi.BoolPtrInput
	// A description for the OIDC application.
	Description pulumi.StringPtrInput
	// Disables the `urn:ietf:params:oauth:grant-type:device_code` grant type for this application.
	DeviceCodeDisabled pulumi.BoolPtrInput
	// Whether the application should be enabled or disabled.
	Disabled pulumi.BoolPtrInput
	// This configuration overrides the default behavior of the SSO application and forces the user to authenticate via the Descope flow, regardless of the SP's request.
	ForceAuthentication pulumi.BoolPtrInput
	// When enabled, the authorization code flow requires PKCE in addition to the normal client authentication. A confidential client must then present both its client secret and a valid PKCE `codeVerifier`. Public clients always use PKCE regardless of this setting.
	ForcePkce pulumi.BoolPtrInput
	// Disables the `urn:ietf:params:oauth:grant-type:jwt-bearer` grant type for this application.
	JwtBearerDisabled pulumi.BoolPtrInput
	// The Flow Hosting URL. When left empty the project's default login page URL is used, and the computed value is reflected in this attribute. Read more about using this parameter with custom domain [here](https://docs.descope.com/sso-integrations/applications/saml-apps).
	LoginPageUrl pulumi.StringPtrInput
	// A logo for the OIDC application. Should be a hosted image URL.
	Logo pulumi.StringPtrInput
	// A name for the OIDC application.
	Name pulumi.StringPtrInput
	// An optional identifier for the application. When omitted, an identifier is generated by the server. Can only be set when the application is created, and changing it will require the resource to be deleted and recreated.
	OidcAppId pulumi.StringPtrInput
	// The ID of the project that this application belongs to. Changing this value will require the resource to be deleted and recreated.
	ProjectId pulumi.StringPtrInput
	// Disables the `refreshToken` grant type for this application.
	RefreshTokenDisabled pulumi.BoolPtrInput
	// Controls the audience values appended to the issued token's `aud` claim for trusted sibling applications. One of `"projectId"`, `"clientId"`, `"appId"`, `"empty"` (add none), or `""` (default — both the project ID and the client ID). Independent of `defaultAudience`.
	TrustedAppsAudience pulumi.StringPtrInput
}

func (OidcAppState) ElementType() reflect.Type {
	return reflect.TypeOf((*oidcAppState)(nil)).Elem()
}

type oidcAppArgs struct {
	// A list of approved redirect URLs for this application (supports `*` wildcards). When set, redirect URIs are validated against this per-app list; when empty, validation falls back to the project's approved/trusted domains.
	ApprovedRedirectUrls []string `pulumi:"approvedRedirectUrls"`
	// Disables the `authorizationCode` grant type for this application.
	AuthorizationCodeDisabled *bool `pulumi:"authorizationCodeDisabled"`
	// The URL that Descope notifies with a logout token when the user's session ends, as per the [OIDC Back-Channel Logout](https://openid.net/specs/openid-connect-backchannel-1_0.html) specification. Leave empty to disable back-channel logout notifications for this application.
	BackchannelLogoutUrl *string `pulumi:"backchannelLogoutUrl"`
	// A list of supported claims. e.g. `sub`, `email`, `exp`.
	Claims []string `pulumi:"claims"`
	// Disables the `clientCredentials` grant type for this application.
	ClientCredentialsDisabled *bool `pulumi:"clientCredentialsDisabled"`
	// A dedicated OIDC `clientId` to import for this application. When omitted, the `clientId` is generated by the server and is not returned on reads. Can only be set when the application is created, and changing it will require the resource to be deleted and recreated.
	ClientId *string `pulumi:"clientId"`
	// A dedicated OIDC `clientSecret` to import for this application. When omitted, a secret is generated server-side only for applications with a `confidential` client type, either on creation or when the application is later switched to `confidential`, and fetched into the Terraform state. Applications with other client types don't use a client secret and the value stays empty. The value in the state is never overwritten afterwards, so a secret rotated via the API or the Descope console is not reflected until the resource is replaced. Changing this value will require the resource to be deleted and recreated.
	ClientSecret *string `pulumi:"clientSecret"`
	// OAuth client confidentiality. One of `""` (default — legacy access-key authentication), `"confidential"` (a dedicated client secret is generated for the app), or `"public"` (PKCE only, no client secret). Changing this value on an existing application changes how its clients must authenticate, so coordinate the change with the application's developers.
	ClientType *string `pulumi:"clientType"`
	// A custom login page URL to redirect users to on IdP-initiated login flows, instead of the default login page.
	CustomIdpInitiatedLoginPageUrl *string `pulumi:"customIdpInitiatedLoginPageUrl"`
	// Controls the default `aud` claim of tokens issued for this application. One of `"projectId"` (the project ID only), `"clientId"` (the dedicated client ID only), `"appId"` (the application ID only), `"empty"` (no `aud` claim at all), or `""` (default — both the project ID and the client ID). Only applies to modern apps that set a `clientType`; legacy apps always use the project ID, so the empty default leaves their behavior unchanged.
	DefaultAudience *string `pulumi:"defaultAudience"`
	// Protects the application from being accidentally destroyed or replaced. Destroying or replacing a federated application breaks the service provider's configured integration and invalidates its client credentials, so these applications are protected by default. To allow the resource to be destroyed or replaced, for example in ephemeral test environments, set this attribute to `false` and apply the change first.
	DeletionProtection *bool `pulumi:"deletionProtection"`
	// A description for the OIDC application.
	Description *string `pulumi:"description"`
	// Disables the `urn:ietf:params:oauth:grant-type:device_code` grant type for this application.
	DeviceCodeDisabled *bool `pulumi:"deviceCodeDisabled"`
	// Whether the application should be enabled or disabled.
	Disabled *bool `pulumi:"disabled"`
	// This configuration overrides the default behavior of the SSO application and forces the user to authenticate via the Descope flow, regardless of the SP's request.
	ForceAuthentication *bool `pulumi:"forceAuthentication"`
	// When enabled, the authorization code flow requires PKCE in addition to the normal client authentication. A confidential client must then present both its client secret and a valid PKCE `codeVerifier`. Public clients always use PKCE regardless of this setting.
	ForcePkce *bool `pulumi:"forcePkce"`
	// Disables the `urn:ietf:params:oauth:grant-type:jwt-bearer` grant type for this application.
	JwtBearerDisabled *bool `pulumi:"jwtBearerDisabled"`
	// The Flow Hosting URL. When left empty the project's default login page URL is used, and the computed value is reflected in this attribute. Read more about using this parameter with custom domain [here](https://docs.descope.com/sso-integrations/applications/saml-apps).
	LoginPageUrl *string `pulumi:"loginPageUrl"`
	// A logo for the OIDC application. Should be a hosted image URL.
	Logo *string `pulumi:"logo"`
	// A name for the OIDC application.
	Name *string `pulumi:"name"`
	// An optional identifier for the application. When omitted, an identifier is generated by the server. Can only be set when the application is created, and changing it will require the resource to be deleted and recreated.
	OidcAppId *string `pulumi:"oidcAppId"`
	// The ID of the project that this application belongs to. Changing this value will require the resource to be deleted and recreated.
	ProjectId string `pulumi:"projectId"`
	// Disables the `refreshToken` grant type for this application.
	RefreshTokenDisabled *bool `pulumi:"refreshTokenDisabled"`
	// Controls the audience values appended to the issued token's `aud` claim for trusted sibling applications. One of `"projectId"`, `"clientId"`, `"appId"`, `"empty"` (add none), or `""` (default — both the project ID and the client ID). Independent of `defaultAudience`.
	TrustedAppsAudience *string `pulumi:"trustedAppsAudience"`
}

// The set of arguments for constructing a OidcApp resource.
type OidcAppArgs struct {
	// A list of approved redirect URLs for this application (supports `*` wildcards). When set, redirect URIs are validated against this per-app list; when empty, validation falls back to the project's approved/trusted domains.
	ApprovedRedirectUrls pulumi.StringArrayInput
	// Disables the `authorizationCode` grant type for this application.
	AuthorizationCodeDisabled pulumi.BoolPtrInput
	// The URL that Descope notifies with a logout token when the user's session ends, as per the [OIDC Back-Channel Logout](https://openid.net/specs/openid-connect-backchannel-1_0.html) specification. Leave empty to disable back-channel logout notifications for this application.
	BackchannelLogoutUrl pulumi.StringPtrInput
	// A list of supported claims. e.g. `sub`, `email`, `exp`.
	Claims pulumi.StringArrayInput
	// Disables the `clientCredentials` grant type for this application.
	ClientCredentialsDisabled pulumi.BoolPtrInput
	// A dedicated OIDC `clientId` to import for this application. When omitted, the `clientId` is generated by the server and is not returned on reads. Can only be set when the application is created, and changing it will require the resource to be deleted and recreated.
	ClientId pulumi.StringPtrInput
	// A dedicated OIDC `clientSecret` to import for this application. When omitted, a secret is generated server-side only for applications with a `confidential` client type, either on creation or when the application is later switched to `confidential`, and fetched into the Terraform state. Applications with other client types don't use a client secret and the value stays empty. The value in the state is never overwritten afterwards, so a secret rotated via the API or the Descope console is not reflected until the resource is replaced. Changing this value will require the resource to be deleted and recreated.
	ClientSecret pulumi.StringPtrInput
	// OAuth client confidentiality. One of `""` (default — legacy access-key authentication), `"confidential"` (a dedicated client secret is generated for the app), or `"public"` (PKCE only, no client secret). Changing this value on an existing application changes how its clients must authenticate, so coordinate the change with the application's developers.
	ClientType pulumi.StringPtrInput
	// A custom login page URL to redirect users to on IdP-initiated login flows, instead of the default login page.
	CustomIdpInitiatedLoginPageUrl pulumi.StringPtrInput
	// Controls the default `aud` claim of tokens issued for this application. One of `"projectId"` (the project ID only), `"clientId"` (the dedicated client ID only), `"appId"` (the application ID only), `"empty"` (no `aud` claim at all), or `""` (default — both the project ID and the client ID). Only applies to modern apps that set a `clientType`; legacy apps always use the project ID, so the empty default leaves their behavior unchanged.
	DefaultAudience pulumi.StringPtrInput
	// Protects the application from being accidentally destroyed or replaced. Destroying or replacing a federated application breaks the service provider's configured integration and invalidates its client credentials, so these applications are protected by default. To allow the resource to be destroyed or replaced, for example in ephemeral test environments, set this attribute to `false` and apply the change first.
	DeletionProtection pulumi.BoolPtrInput
	// A description for the OIDC application.
	Description pulumi.StringPtrInput
	// Disables the `urn:ietf:params:oauth:grant-type:device_code` grant type for this application.
	DeviceCodeDisabled pulumi.BoolPtrInput
	// Whether the application should be enabled or disabled.
	Disabled pulumi.BoolPtrInput
	// This configuration overrides the default behavior of the SSO application and forces the user to authenticate via the Descope flow, regardless of the SP's request.
	ForceAuthentication pulumi.BoolPtrInput
	// When enabled, the authorization code flow requires PKCE in addition to the normal client authentication. A confidential client must then present both its client secret and a valid PKCE `codeVerifier`. Public clients always use PKCE regardless of this setting.
	ForcePkce pulumi.BoolPtrInput
	// Disables the `urn:ietf:params:oauth:grant-type:jwt-bearer` grant type for this application.
	JwtBearerDisabled pulumi.BoolPtrInput
	// The Flow Hosting URL. When left empty the project's default login page URL is used, and the computed value is reflected in this attribute. Read more about using this parameter with custom domain [here](https://docs.descope.com/sso-integrations/applications/saml-apps).
	LoginPageUrl pulumi.StringPtrInput
	// A logo for the OIDC application. Should be a hosted image URL.
	Logo pulumi.StringPtrInput
	// A name for the OIDC application.
	Name pulumi.StringPtrInput
	// An optional identifier for the application. When omitted, an identifier is generated by the server. Can only be set when the application is created, and changing it will require the resource to be deleted and recreated.
	OidcAppId pulumi.StringPtrInput
	// The ID of the project that this application belongs to. Changing this value will require the resource to be deleted and recreated.
	ProjectId pulumi.StringInput
	// Disables the `refreshToken` grant type for this application.
	RefreshTokenDisabled pulumi.BoolPtrInput
	// Controls the audience values appended to the issued token's `aud` claim for trusted sibling applications. One of `"projectId"`, `"clientId"`, `"appId"`, `"empty"` (add none), or `""` (default — both the project ID and the client ID). Independent of `defaultAudience`.
	TrustedAppsAudience pulumi.StringPtrInput
}

func (OidcAppArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*oidcAppArgs)(nil)).Elem()
}

type OidcAppInput interface {
	pulumi.Input

	ToOidcAppOutput() OidcAppOutput
	ToOidcAppOutputWithContext(ctx context.Context) OidcAppOutput
}

func (*OidcApp) ElementType() reflect.Type {
	return reflect.TypeOf((**OidcApp)(nil)).Elem()
}

func (i *OidcApp) ToOidcAppOutput() OidcAppOutput {
	return i.ToOidcAppOutputWithContext(context.Background())
}

func (i *OidcApp) ToOidcAppOutputWithContext(ctx context.Context) OidcAppOutput {
	return pulumi.ToOutputWithContext(ctx, i).(OidcAppOutput)
}

// OidcAppArrayInput is an input type that accepts OidcAppArray and OidcAppArrayOutput values.
// You can construct a concrete instance of `OidcAppArrayInput` via:
//
//	OidcAppArray{ OidcAppArgs{...} }
type OidcAppArrayInput interface {
	pulumi.Input

	ToOidcAppArrayOutput() OidcAppArrayOutput
	ToOidcAppArrayOutputWithContext(context.Context) OidcAppArrayOutput
}

type OidcAppArray []OidcAppInput

func (OidcAppArray) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*OidcApp)(nil)).Elem()
}

func (i OidcAppArray) ToOidcAppArrayOutput() OidcAppArrayOutput {
	return i.ToOidcAppArrayOutputWithContext(context.Background())
}

func (i OidcAppArray) ToOidcAppArrayOutputWithContext(ctx context.Context) OidcAppArrayOutput {
	return pulumi.ToOutputWithContext(ctx, i).(OidcAppArrayOutput)
}

// OidcAppMapInput is an input type that accepts OidcAppMap and OidcAppMapOutput values.
// You can construct a concrete instance of `OidcAppMapInput` via:
//
//	OidcAppMap{ "key": OidcAppArgs{...} }
type OidcAppMapInput interface {
	pulumi.Input

	ToOidcAppMapOutput() OidcAppMapOutput
	ToOidcAppMapOutputWithContext(context.Context) OidcAppMapOutput
}

type OidcAppMap map[string]OidcAppInput

func (OidcAppMap) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*OidcApp)(nil)).Elem()
}

func (i OidcAppMap) ToOidcAppMapOutput() OidcAppMapOutput {
	return i.ToOidcAppMapOutputWithContext(context.Background())
}

func (i OidcAppMap) ToOidcAppMapOutputWithContext(ctx context.Context) OidcAppMapOutput {
	return pulumi.ToOutputWithContext(ctx, i).(OidcAppMapOutput)
}

type OidcAppOutput struct{ *pulumi.OutputState }

func (OidcAppOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**OidcApp)(nil)).Elem()
}

func (o OidcAppOutput) ToOidcAppOutput() OidcAppOutput {
	return o
}

func (o OidcAppOutput) ToOidcAppOutputWithContext(ctx context.Context) OidcAppOutput {
	return o
}

// A list of approved redirect URLs for this application (supports `*` wildcards). When set, redirect URIs are validated against this per-app list; when empty, validation falls back to the project's approved/trusted domains.
func (o OidcAppOutput) ApprovedRedirectUrls() pulumi.StringArrayOutput {
	return o.ApplyT(func(v *OidcApp) pulumi.StringArrayOutput { return v.ApprovedRedirectUrls }).(pulumi.StringArrayOutput)
}

// Disables the `authorizationCode` grant type for this application.
func (o OidcAppOutput) AuthorizationCodeDisabled() pulumi.BoolOutput {
	return o.ApplyT(func(v *OidcApp) pulumi.BoolOutput { return v.AuthorizationCodeDisabled }).(pulumi.BoolOutput)
}

// The URL that Descope notifies with a logout token when the user's session ends, as per the [OIDC Back-Channel Logout](https://openid.net/specs/openid-connect-backchannel-1_0.html) specification. Leave empty to disable back-channel logout notifications for this application.
func (o OidcAppOutput) BackchannelLogoutUrl() pulumi.StringOutput {
	return o.ApplyT(func(v *OidcApp) pulumi.StringOutput { return v.BackchannelLogoutUrl }).(pulumi.StringOutput)
}

// A list of supported claims. e.g. `sub`, `email`, `exp`.
func (o OidcAppOutput) Claims() pulumi.StringArrayOutput {
	return o.ApplyT(func(v *OidcApp) pulumi.StringArrayOutput { return v.Claims }).(pulumi.StringArrayOutput)
}

// Disables the `clientCredentials` grant type for this application.
func (o OidcAppOutput) ClientCredentialsDisabled() pulumi.BoolOutput {
	return o.ApplyT(func(v *OidcApp) pulumi.BoolOutput { return v.ClientCredentialsDisabled }).(pulumi.BoolOutput)
}

// A dedicated OIDC `clientId` to import for this application. When omitted, the `clientId` is generated by the server and is not returned on reads. Can only be set when the application is created, and changing it will require the resource to be deleted and recreated.
func (o OidcAppOutput) ClientId() pulumi.StringOutput {
	return o.ApplyT(func(v *OidcApp) pulumi.StringOutput { return v.ClientId }).(pulumi.StringOutput)
}

// A dedicated OIDC `clientSecret` to import for this application. When omitted, a secret is generated server-side only for applications with a `confidential` client type, either on creation or when the application is later switched to `confidential`, and fetched into the Terraform state. Applications with other client types don't use a client secret and the value stays empty. The value in the state is never overwritten afterwards, so a secret rotated via the API or the Descope console is not reflected until the resource is replaced. Changing this value will require the resource to be deleted and recreated.
func (o OidcAppOutput) ClientSecret() pulumi.StringOutput {
	return o.ApplyT(func(v *OidcApp) pulumi.StringOutput { return v.ClientSecret }).(pulumi.StringOutput)
}

// OAuth client confidentiality. One of `""` (default — legacy access-key authentication), `"confidential"` (a dedicated client secret is generated for the app), or `"public"` (PKCE only, no client secret). Changing this value on an existing application changes how its clients must authenticate, so coordinate the change with the application's developers.
func (o OidcAppOutput) ClientType() pulumi.StringOutput {
	return o.ApplyT(func(v *OidcApp) pulumi.StringOutput { return v.ClientType }).(pulumi.StringOutput)
}

// A custom login page URL to redirect users to on IdP-initiated login flows, instead of the default login page.
func (o OidcAppOutput) CustomIdpInitiatedLoginPageUrl() pulumi.StringOutput {
	return o.ApplyT(func(v *OidcApp) pulumi.StringOutput { return v.CustomIdpInitiatedLoginPageUrl }).(pulumi.StringOutput)
}

// Controls the default `aud` claim of tokens issued for this application. One of `"projectId"` (the project ID only), `"clientId"` (the dedicated client ID only), `"appId"` (the application ID only), `"empty"` (no `aud` claim at all), or `""` (default — both the project ID and the client ID). Only applies to modern apps that set a `clientType`; legacy apps always use the project ID, so the empty default leaves their behavior unchanged.
func (o OidcAppOutput) DefaultAudience() pulumi.StringOutput {
	return o.ApplyT(func(v *OidcApp) pulumi.StringOutput { return v.DefaultAudience }).(pulumi.StringOutput)
}

// Protects the application from being accidentally destroyed or replaced. Destroying or replacing a federated application breaks the service provider's configured integration and invalidates its client credentials, so these applications are protected by default. To allow the resource to be destroyed or replaced, for example in ephemeral test environments, set this attribute to `false` and apply the change first.
func (o OidcAppOutput) DeletionProtection() pulumi.BoolPtrOutput {
	return o.ApplyT(func(v *OidcApp) pulumi.BoolPtrOutput { return v.DeletionProtection }).(pulumi.BoolPtrOutput)
}

// A description for the OIDC application.
func (o OidcAppOutput) Description() pulumi.StringOutput {
	return o.ApplyT(func(v *OidcApp) pulumi.StringOutput { return v.Description }).(pulumi.StringOutput)
}

// Disables the `urn:ietf:params:oauth:grant-type:device_code` grant type for this application.
func (o OidcAppOutput) DeviceCodeDisabled() pulumi.BoolOutput {
	return o.ApplyT(func(v *OidcApp) pulumi.BoolOutput { return v.DeviceCodeDisabled }).(pulumi.BoolOutput)
}

// Whether the application should be enabled or disabled.
func (o OidcAppOutput) Disabled() pulumi.BoolOutput {
	return o.ApplyT(func(v *OidcApp) pulumi.BoolOutput { return v.Disabled }).(pulumi.BoolOutput)
}

// This configuration overrides the default behavior of the SSO application and forces the user to authenticate via the Descope flow, regardless of the SP's request.
func (o OidcAppOutput) ForceAuthentication() pulumi.BoolOutput {
	return o.ApplyT(func(v *OidcApp) pulumi.BoolOutput { return v.ForceAuthentication }).(pulumi.BoolOutput)
}

// When enabled, the authorization code flow requires PKCE in addition to the normal client authentication. A confidential client must then present both its client secret and a valid PKCE `codeVerifier`. Public clients always use PKCE regardless of this setting.
func (o OidcAppOutput) ForcePkce() pulumi.BoolOutput {
	return o.ApplyT(func(v *OidcApp) pulumi.BoolOutput { return v.ForcePkce }).(pulumi.BoolOutput)
}

// Disables the `urn:ietf:params:oauth:grant-type:jwt-bearer` grant type for this application.
func (o OidcAppOutput) JwtBearerDisabled() pulumi.BoolOutput {
	return o.ApplyT(func(v *OidcApp) pulumi.BoolOutput { return v.JwtBearerDisabled }).(pulumi.BoolOutput)
}

// The Flow Hosting URL. When left empty the project's default login page URL is used, and the computed value is reflected in this attribute. Read more about using this parameter with custom domain [here](https://docs.descope.com/sso-integrations/applications/saml-apps).
func (o OidcAppOutput) LoginPageUrl() pulumi.StringOutput {
	return o.ApplyT(func(v *OidcApp) pulumi.StringOutput { return v.LoginPageUrl }).(pulumi.StringOutput)
}

// A logo for the OIDC application. Should be a hosted image URL.
func (o OidcAppOutput) Logo() pulumi.StringOutput {
	return o.ApplyT(func(v *OidcApp) pulumi.StringOutput { return v.Logo }).(pulumi.StringOutput)
}

// A name for the OIDC application.
func (o OidcAppOutput) Name() pulumi.StringOutput {
	return o.ApplyT(func(v *OidcApp) pulumi.StringOutput { return v.Name }).(pulumi.StringOutput)
}

// An optional identifier for the application. When omitted, an identifier is generated by the server. Can only be set when the application is created, and changing it will require the resource to be deleted and recreated.
func (o OidcAppOutput) OidcAppId() pulumi.StringOutput {
	return o.ApplyT(func(v *OidcApp) pulumi.StringOutput { return v.OidcAppId }).(pulumi.StringOutput)
}

// The ID of the project that this application belongs to. Changing this value will require the resource to be deleted and recreated.
func (o OidcAppOutput) ProjectId() pulumi.StringOutput {
	return o.ApplyT(func(v *OidcApp) pulumi.StringOutput { return v.ProjectId }).(pulumi.StringOutput)
}

// Disables the `refreshToken` grant type for this application.
func (o OidcAppOutput) RefreshTokenDisabled() pulumi.BoolOutput {
	return o.ApplyT(func(v *OidcApp) pulumi.BoolOutput { return v.RefreshTokenDisabled }).(pulumi.BoolOutput)
}

// Controls the audience values appended to the issued token's `aud` claim for trusted sibling applications. One of `"projectId"`, `"clientId"`, `"appId"`, `"empty"` (add none), or `""` (default — both the project ID and the client ID). Independent of `defaultAudience`.
func (o OidcAppOutput) TrustedAppsAudience() pulumi.StringOutput {
	return o.ApplyT(func(v *OidcApp) pulumi.StringOutput { return v.TrustedAppsAudience }).(pulumi.StringOutput)
}

type OidcAppArrayOutput struct{ *pulumi.OutputState }

func (OidcAppArrayOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*OidcApp)(nil)).Elem()
}

func (o OidcAppArrayOutput) ToOidcAppArrayOutput() OidcAppArrayOutput {
	return o
}

func (o OidcAppArrayOutput) ToOidcAppArrayOutputWithContext(ctx context.Context) OidcAppArrayOutput {
	return o
}

func (o OidcAppArrayOutput) Index(i pulumi.IntInput) OidcAppOutput {
	return pulumi.All(o, i).ApplyT(func(vs []interface{}) *OidcApp {
		return vs[0].([]*OidcApp)[vs[1].(int)]
	}).(OidcAppOutput)
}

type OidcAppMapOutput struct{ *pulumi.OutputState }

func (OidcAppMapOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*OidcApp)(nil)).Elem()
}

func (o OidcAppMapOutput) ToOidcAppMapOutput() OidcAppMapOutput {
	return o
}

func (o OidcAppMapOutput) ToOidcAppMapOutputWithContext(ctx context.Context) OidcAppMapOutput {
	return o
}

func (o OidcAppMapOutput) MapIndex(k pulumi.StringInput) OidcAppOutput {
	return pulumi.All(o, k).ApplyT(func(vs []interface{}) *OidcApp {
		return vs[0].(map[string]*OidcApp)[vs[1].(string)]
	}).(OidcAppOutput)
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*OidcAppInput)(nil)).Elem(), &OidcApp{})
	pulumi.RegisterInputType(reflect.TypeOf((*OidcAppArrayInput)(nil)).Elem(), OidcAppArray{})
	pulumi.RegisterInputType(reflect.TypeOf((*OidcAppMapInput)(nil)).Elem(), OidcAppMap{})
	pulumi.RegisterOutputType(OidcAppOutput{})
	pulumi.RegisterOutputType(OidcAppArrayOutput{})
	pulumi.RegisterOutputType(OidcAppMapOutput{})
}
