// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package descope

import (
	"context"
	"reflect"

	"errors"
	"github.com/descope/pulumi-descope/sdk/go/descope/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

// Manages a reCAPTCHA v2 connector and its configuration in a Descope project. Use the reCAPTCHA v2 "I'm not a robot" checkbox widget with your flows.
type RecaptchaV2Connector struct {
	pulumi.CustomResourceState

	// When override is enabled, return this score instead of calling Google.
	AssessmentScore pulumi.Float64Output `pulumi:"assessmentScore"`
	// For v2 verification, success maps to risk score 1 and failure to 0. Bot is detected when risk score is below this threshold (default 0.5).
	BotThreshold pulumi.Float64Output `pulumi:"botThreshold"`
	// A description of what your connector is used for.
	Description pulumi.StringOutput `pulumi:"description"`
	// Whether the connector is disabled. This can be used to temporarily stop a connector from executing without fully deleting it.
	Disabled pulumi.BoolOutput `pulumi:"disabled"`
	// A custom name for your connector.
	Name pulumi.StringOutput `pulumi:"name"`
	// Override the default assessment model. Intended for automated testing only.
	OverrideAssessment pulumi.BoolOutput `pulumi:"overrideAssessment"`
	// The ID of the Descope project that the connector belongs to. Changing this value will require the resource to be deleted and recreated.
	ProjectId pulumi.StringOutput `pulumi:"projectId"`
	// The secret key used to verify the user's response with Google siteverify.
	SecretKey pulumi.StringOutput `pulumi:"secretKey"`
	// The reCAPTCHA v2 site key from the Google reCAPTCHA admin console (checkbox / "I'm not a robot" type).
	SiteKey pulumi.StringOutput `pulumi:"siteKey"`
}

// NewRecaptchaV2Connector registers a new resource with the given unique name, arguments, and options.
func NewRecaptchaV2Connector(ctx *pulumi.Context,
	name string, args *RecaptchaV2ConnectorArgs, opts ...pulumi.ResourceOption) (*RecaptchaV2Connector, error) {
	if args == nil {
		return nil, errors.New("missing one or more required arguments")
	}

	if args.ProjectId == nil {
		return nil, errors.New("invalid value for required argument 'ProjectId'")
	}
	if args.SecretKey == nil {
		return nil, errors.New("invalid value for required argument 'SecretKey'")
	}
	if args.SiteKey == nil {
		return nil, errors.New("invalid value for required argument 'SiteKey'")
	}
	if args.SecretKey != nil {
		args.SecretKey = pulumi.ToSecret(args.SecretKey).(pulumi.StringInput)
	}
	secrets := pulumi.AdditionalSecretOutputs([]string{
		"secretKey",
	})
	opts = append(opts, secrets)
	opts = internal.PkgResourceDefaultOpts(opts)
	var resource RecaptchaV2Connector
	err := ctx.RegisterResource("descope:index/recaptchaV2Connector:RecaptchaV2Connector", name, args, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// GetRecaptchaV2Connector gets an existing RecaptchaV2Connector resource's state with the given name, ID, and optional
// state properties that are used to uniquely qualify the lookup (nil if not required).
func GetRecaptchaV2Connector(ctx *pulumi.Context,
	name string, id pulumi.IDInput, state *RecaptchaV2ConnectorState, opts ...pulumi.ResourceOption) (*RecaptchaV2Connector, error) {
	var resource RecaptchaV2Connector
	err := ctx.ReadResource("descope:index/recaptchaV2Connector:RecaptchaV2Connector", name, id, state, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// Input properties used for looking up and filtering RecaptchaV2Connector resources.
type recaptchaV2ConnectorState struct {
	// When override is enabled, return this score instead of calling Google.
	AssessmentScore *float64 `pulumi:"assessmentScore"`
	// For v2 verification, success maps to risk score 1 and failure to 0. Bot is detected when risk score is below this threshold (default 0.5).
	BotThreshold *float64 `pulumi:"botThreshold"`
	// A description of what your connector is used for.
	Description *string `pulumi:"description"`
	// Whether the connector is disabled. This can be used to temporarily stop a connector from executing without fully deleting it.
	Disabled *bool `pulumi:"disabled"`
	// A custom name for your connector.
	Name *string `pulumi:"name"`
	// Override the default assessment model. Intended for automated testing only.
	OverrideAssessment *bool `pulumi:"overrideAssessment"`
	// The ID of the Descope project that the connector belongs to. Changing this value will require the resource to be deleted and recreated.
	ProjectId *string `pulumi:"projectId"`
	// The secret key used to verify the user's response with Google siteverify.
	SecretKey *string `pulumi:"secretKey"`
	// The reCAPTCHA v2 site key from the Google reCAPTCHA admin console (checkbox / "I'm not a robot" type).
	SiteKey *string `pulumi:"siteKey"`
}

type RecaptchaV2ConnectorState struct {
	// When override is enabled, return this score instead of calling Google.
	AssessmentScore pulumi.Float64PtrInput
	// For v2 verification, success maps to risk score 1 and failure to 0. Bot is detected when risk score is below this threshold (default 0.5).
	BotThreshold pulumi.Float64PtrInput
	// A description of what your connector is used for.
	Description pulumi.StringPtrInput
	// Whether the connector is disabled. This can be used to temporarily stop a connector from executing without fully deleting it.
	Disabled pulumi.BoolPtrInput
	// A custom name for your connector.
	Name pulumi.StringPtrInput
	// Override the default assessment model. Intended for automated testing only.
	OverrideAssessment pulumi.BoolPtrInput
	// The ID of the Descope project that the connector belongs to. Changing this value will require the resource to be deleted and recreated.
	ProjectId pulumi.StringPtrInput
	// The secret key used to verify the user's response with Google siteverify.
	SecretKey pulumi.StringPtrInput
	// The reCAPTCHA v2 site key from the Google reCAPTCHA admin console (checkbox / "I'm not a robot" type).
	SiteKey pulumi.StringPtrInput
}

func (RecaptchaV2ConnectorState) ElementType() reflect.Type {
	return reflect.TypeOf((*recaptchaV2ConnectorState)(nil)).Elem()
}

type recaptchaV2ConnectorArgs struct {
	// When override is enabled, return this score instead of calling Google.
	AssessmentScore *float64 `pulumi:"assessmentScore"`
	// For v2 verification, success maps to risk score 1 and failure to 0. Bot is detected when risk score is below this threshold (default 0.5).
	BotThreshold *float64 `pulumi:"botThreshold"`
	// A description of what your connector is used for.
	Description *string `pulumi:"description"`
	// Whether the connector is disabled. This can be used to temporarily stop a connector from executing without fully deleting it.
	Disabled *bool `pulumi:"disabled"`
	// A custom name for your connector.
	Name *string `pulumi:"name"`
	// Override the default assessment model. Intended for automated testing only.
	OverrideAssessment *bool `pulumi:"overrideAssessment"`
	// The ID of the Descope project that the connector belongs to. Changing this value will require the resource to be deleted and recreated.
	ProjectId string `pulumi:"projectId"`
	// The secret key used to verify the user's response with Google siteverify.
	SecretKey string `pulumi:"secretKey"`
	// The reCAPTCHA v2 site key from the Google reCAPTCHA admin console (checkbox / "I'm not a robot" type).
	SiteKey string `pulumi:"siteKey"`
}

// The set of arguments for constructing a RecaptchaV2Connector resource.
type RecaptchaV2ConnectorArgs struct {
	// When override is enabled, return this score instead of calling Google.
	AssessmentScore pulumi.Float64PtrInput
	// For v2 verification, success maps to risk score 1 and failure to 0. Bot is detected when risk score is below this threshold (default 0.5).
	BotThreshold pulumi.Float64PtrInput
	// A description of what your connector is used for.
	Description pulumi.StringPtrInput
	// Whether the connector is disabled. This can be used to temporarily stop a connector from executing without fully deleting it.
	Disabled pulumi.BoolPtrInput
	// A custom name for your connector.
	Name pulumi.StringPtrInput
	// Override the default assessment model. Intended for automated testing only.
	OverrideAssessment pulumi.BoolPtrInput
	// The ID of the Descope project that the connector belongs to. Changing this value will require the resource to be deleted and recreated.
	ProjectId pulumi.StringInput
	// The secret key used to verify the user's response with Google siteverify.
	SecretKey pulumi.StringInput
	// The reCAPTCHA v2 site key from the Google reCAPTCHA admin console (checkbox / "I'm not a robot" type).
	SiteKey pulumi.StringInput
}

func (RecaptchaV2ConnectorArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*recaptchaV2ConnectorArgs)(nil)).Elem()
}

type RecaptchaV2ConnectorInput interface {
	pulumi.Input

	ToRecaptchaV2ConnectorOutput() RecaptchaV2ConnectorOutput
	ToRecaptchaV2ConnectorOutputWithContext(ctx context.Context) RecaptchaV2ConnectorOutput
}

func (*RecaptchaV2Connector) ElementType() reflect.Type {
	return reflect.TypeOf((**RecaptchaV2Connector)(nil)).Elem()
}

func (i *RecaptchaV2Connector) ToRecaptchaV2ConnectorOutput() RecaptchaV2ConnectorOutput {
	return i.ToRecaptchaV2ConnectorOutputWithContext(context.Background())
}

func (i *RecaptchaV2Connector) ToRecaptchaV2ConnectorOutputWithContext(ctx context.Context) RecaptchaV2ConnectorOutput {
	return pulumi.ToOutputWithContext(ctx, i).(RecaptchaV2ConnectorOutput)
}

// RecaptchaV2ConnectorArrayInput is an input type that accepts RecaptchaV2ConnectorArray and RecaptchaV2ConnectorArrayOutput values.
// You can construct a concrete instance of `RecaptchaV2ConnectorArrayInput` via:
//
//	RecaptchaV2ConnectorArray{ RecaptchaV2ConnectorArgs{...} }
type RecaptchaV2ConnectorArrayInput interface {
	pulumi.Input

	ToRecaptchaV2ConnectorArrayOutput() RecaptchaV2ConnectorArrayOutput
	ToRecaptchaV2ConnectorArrayOutputWithContext(context.Context) RecaptchaV2ConnectorArrayOutput
}

type RecaptchaV2ConnectorArray []RecaptchaV2ConnectorInput

func (RecaptchaV2ConnectorArray) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*RecaptchaV2Connector)(nil)).Elem()
}

func (i RecaptchaV2ConnectorArray) ToRecaptchaV2ConnectorArrayOutput() RecaptchaV2ConnectorArrayOutput {
	return i.ToRecaptchaV2ConnectorArrayOutputWithContext(context.Background())
}

func (i RecaptchaV2ConnectorArray) ToRecaptchaV2ConnectorArrayOutputWithContext(ctx context.Context) RecaptchaV2ConnectorArrayOutput {
	return pulumi.ToOutputWithContext(ctx, i).(RecaptchaV2ConnectorArrayOutput)
}

// RecaptchaV2ConnectorMapInput is an input type that accepts RecaptchaV2ConnectorMap and RecaptchaV2ConnectorMapOutput values.
// You can construct a concrete instance of `RecaptchaV2ConnectorMapInput` via:
//
//	RecaptchaV2ConnectorMap{ "key": RecaptchaV2ConnectorArgs{...} }
type RecaptchaV2ConnectorMapInput interface {
	pulumi.Input

	ToRecaptchaV2ConnectorMapOutput() RecaptchaV2ConnectorMapOutput
	ToRecaptchaV2ConnectorMapOutputWithContext(context.Context) RecaptchaV2ConnectorMapOutput
}

type RecaptchaV2ConnectorMap map[string]RecaptchaV2ConnectorInput

func (RecaptchaV2ConnectorMap) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*RecaptchaV2Connector)(nil)).Elem()
}

func (i RecaptchaV2ConnectorMap) ToRecaptchaV2ConnectorMapOutput() RecaptchaV2ConnectorMapOutput {
	return i.ToRecaptchaV2ConnectorMapOutputWithContext(context.Background())
}

func (i RecaptchaV2ConnectorMap) ToRecaptchaV2ConnectorMapOutputWithContext(ctx context.Context) RecaptchaV2ConnectorMapOutput {
	return pulumi.ToOutputWithContext(ctx, i).(RecaptchaV2ConnectorMapOutput)
}

type RecaptchaV2ConnectorOutput struct{ *pulumi.OutputState }

func (RecaptchaV2ConnectorOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**RecaptchaV2Connector)(nil)).Elem()
}

func (o RecaptchaV2ConnectorOutput) ToRecaptchaV2ConnectorOutput() RecaptchaV2ConnectorOutput {
	return o
}

func (o RecaptchaV2ConnectorOutput) ToRecaptchaV2ConnectorOutputWithContext(ctx context.Context) RecaptchaV2ConnectorOutput {
	return o
}

// When override is enabled, return this score instead of calling Google.
func (o RecaptchaV2ConnectorOutput) AssessmentScore() pulumi.Float64Output {
	return o.ApplyT(func(v *RecaptchaV2Connector) pulumi.Float64Output { return v.AssessmentScore }).(pulumi.Float64Output)
}

// For v2 verification, success maps to risk score 1 and failure to 0. Bot is detected when risk score is below this threshold (default 0.5).
func (o RecaptchaV2ConnectorOutput) BotThreshold() pulumi.Float64Output {
	return o.ApplyT(func(v *RecaptchaV2Connector) pulumi.Float64Output { return v.BotThreshold }).(pulumi.Float64Output)
}

// A description of what your connector is used for.
func (o RecaptchaV2ConnectorOutput) Description() pulumi.StringOutput {
	return o.ApplyT(func(v *RecaptchaV2Connector) pulumi.StringOutput { return v.Description }).(pulumi.StringOutput)
}

// Whether the connector is disabled. This can be used to temporarily stop a connector from executing without fully deleting it.
func (o RecaptchaV2ConnectorOutput) Disabled() pulumi.BoolOutput {
	return o.ApplyT(func(v *RecaptchaV2Connector) pulumi.BoolOutput { return v.Disabled }).(pulumi.BoolOutput)
}

// A custom name for your connector.
func (o RecaptchaV2ConnectorOutput) Name() pulumi.StringOutput {
	return o.ApplyT(func(v *RecaptchaV2Connector) pulumi.StringOutput { return v.Name }).(pulumi.StringOutput)
}

// Override the default assessment model. Intended for automated testing only.
func (o RecaptchaV2ConnectorOutput) OverrideAssessment() pulumi.BoolOutput {
	return o.ApplyT(func(v *RecaptchaV2Connector) pulumi.BoolOutput { return v.OverrideAssessment }).(pulumi.BoolOutput)
}

// The ID of the Descope project that the connector belongs to. Changing this value will require the resource to be deleted and recreated.
func (o RecaptchaV2ConnectorOutput) ProjectId() pulumi.StringOutput {
	return o.ApplyT(func(v *RecaptchaV2Connector) pulumi.StringOutput { return v.ProjectId }).(pulumi.StringOutput)
}

// The secret key used to verify the user's response with Google siteverify.
func (o RecaptchaV2ConnectorOutput) SecretKey() pulumi.StringOutput {
	return o.ApplyT(func(v *RecaptchaV2Connector) pulumi.StringOutput { return v.SecretKey }).(pulumi.StringOutput)
}

// The reCAPTCHA v2 site key from the Google reCAPTCHA admin console (checkbox / "I'm not a robot" type).
func (o RecaptchaV2ConnectorOutput) SiteKey() pulumi.StringOutput {
	return o.ApplyT(func(v *RecaptchaV2Connector) pulumi.StringOutput { return v.SiteKey }).(pulumi.StringOutput)
}

type RecaptchaV2ConnectorArrayOutput struct{ *pulumi.OutputState }

func (RecaptchaV2ConnectorArrayOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*RecaptchaV2Connector)(nil)).Elem()
}

func (o RecaptchaV2ConnectorArrayOutput) ToRecaptchaV2ConnectorArrayOutput() RecaptchaV2ConnectorArrayOutput {
	return o
}

func (o RecaptchaV2ConnectorArrayOutput) ToRecaptchaV2ConnectorArrayOutputWithContext(ctx context.Context) RecaptchaV2ConnectorArrayOutput {
	return o
}

func (o RecaptchaV2ConnectorArrayOutput) Index(i pulumi.IntInput) RecaptchaV2ConnectorOutput {
	return pulumi.All(o, i).ApplyT(func(vs []interface{}) *RecaptchaV2Connector {
		return vs[0].([]*RecaptchaV2Connector)[vs[1].(int)]
	}).(RecaptchaV2ConnectorOutput)
}

type RecaptchaV2ConnectorMapOutput struct{ *pulumi.OutputState }

func (RecaptchaV2ConnectorMapOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*RecaptchaV2Connector)(nil)).Elem()
}

func (o RecaptchaV2ConnectorMapOutput) ToRecaptchaV2ConnectorMapOutput() RecaptchaV2ConnectorMapOutput {
	return o
}

func (o RecaptchaV2ConnectorMapOutput) ToRecaptchaV2ConnectorMapOutputWithContext(ctx context.Context) RecaptchaV2ConnectorMapOutput {
	return o
}

func (o RecaptchaV2ConnectorMapOutput) MapIndex(k pulumi.StringInput) RecaptchaV2ConnectorOutput {
	return pulumi.All(o, k).ApplyT(func(vs []interface{}) *RecaptchaV2Connector {
		return vs[0].(map[string]*RecaptchaV2Connector)[vs[1].(string)]
	}).(RecaptchaV2ConnectorOutput)
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*RecaptchaV2ConnectorInput)(nil)).Elem(), &RecaptchaV2Connector{})
	pulumi.RegisterInputType(reflect.TypeOf((*RecaptchaV2ConnectorArrayInput)(nil)).Elem(), RecaptchaV2ConnectorArray{})
	pulumi.RegisterInputType(reflect.TypeOf((*RecaptchaV2ConnectorMapInput)(nil)).Elem(), RecaptchaV2ConnectorMap{})
	pulumi.RegisterOutputType(RecaptchaV2ConnectorOutput{})
	pulumi.RegisterOutputType(RecaptchaV2ConnectorArrayOutput{})
	pulumi.RegisterOutputType(RecaptchaV2ConnectorMapOutput{})
}
