name: master
on:
  workflow_dispatch: {}
  push:
    branches:
      - main
    paths-ignore:
      - "**.md"
    tags-ignore:
      - v*
      - sdk/*
      - "**"

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  NODE_AUTH_TOKEN: ${{ secrets.CI_NPM_REGISTRY }}
  NPM_TOKEN: ${{ secrets.CI_NPM_REGISTRY }}
  NUGET_PUBLISH_KEY: ${{ secrets.NUGET_ORG_KEY }}
  PULUMI_GO_DEP_ROOT: ${{ github.workspace }}/..
  PULUMI_LOCAL_NUGET: ${{ github.workspace }}/nuget
  PYPI_PASSWORD: ${{ secrets.PYPI_TOKEN }}
  PYPI_USERNAME: __token__
  TF_APPEND_USER_AGENT: pulumi
jobs:
  prerequisites:
    uses: ./.github/workflows/prerequisites.yml
    secrets: inherit
    with:
      default_branch: ${{ github.event.repository.default_branch }}
      is_pr: ${{ github.event_name == 'pull_request' }}
      is_automated: ${{ github.actor == 'dependabot[bot]' || github.actor == 'descope[bot]' }}

  build_provider:
    uses: ./.github/workflows/build_provider.yml
    needs: prerequisites
    secrets: inherit
    with:
      version: ${{ needs.prerequisites.outputs.version }}

  build_sdk:
    name: build_sdk
    needs: prerequisites
    uses: ./.github/workflows/build_sdk.yml
    secrets: inherit
    with:
      version: ${{ needs.prerequisites.outputs.version }}

  lint:
    name: lint
    uses: ./.github/workflows/lint.yml
    secrets: inherit
  license_check:
    name: License Check
    uses: ./.github/workflows/license.yml
    secrets: inherit

  publish:
    name: publish
    needs:
      - prerequisites
      - build_provider
      - test
      - license_check
    uses: ./.github/workflows/publish.yml
    secrets: inherit
    with:
      version: ${{ needs.prerequisites.outputs.version }}
      isPrerelease: true
      skipGoSdk: true

  test:
    name: test
    needs:
      - prerequisites
      - build_sdk
    permissions:
      contents: read
      id-token: write
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        language:
          - nodejs
          - python
          - dotnet
          - go
    env:
      PROVIDER_VERSION: ${{ needs.prerequisites.outputs.version }}
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
      - name: Setup tools
        uses: ./.github/actions/setup-tools
        with:
          tools: pulumictl, pulumicli, go, node, dotnet, python
      - name: Download bin
        uses: ./.github/actions/download-bin
      - run: dotnet nuget add source ${{ github.workspace }}/nuget
      - name: Download SDK
        uses: ./.github/actions/download-sdk
        with:
          language: ${{ matrix.language }}
      - name: Update path
        run: echo "${{ github.workspace }}/bin" >> "$GITHUB_PATH"
      - name: Install Python deps
        run: |-
          pip3 install virtualenv==20.0.23
          pip3 install pipenv
      - name: Install dependencies
        run: make install_${{ matrix.language}}_sdk
      - name: Install gotestfmt
        uses: GoTestTools/gotestfmt-action@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          version: v2.5.0
      - name: Run tests
        env:
          DESCOPE_PROJECT_ID: ${{ secrets.DESCOPE_PROJECT_ID }}
          DESCOPE_MANAGEMENT_KEY: ${{ secrets.DESCOPE_MANAGEMENT_KEY }}
        working-directory: examples
        run: |
          go test -v -json -count=1 -cover -timeout 2h \
          -tags=${{matrix.language }} -parallel 4 . 2>&1 | tee /tmp/gotest.log | gotestfmt
