name: pull-request
on:
  pull_request_target: {}

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  NODE_AUTH_TOKEN: ${{ secrets.CI_NPM_REGISTRY }}
  NPM_TOKEN: ${{ secrets.CI_NPM_REGISTRY }}
  NUGET_PUBLISH_KEY: ${{ secrets.NUGET_ORG_KEY }}
  PULUMI_GO_DEP_ROOT: ${{ github.workspace }}/..
  PULUMI_LOCAL_NUGET: ${{ github.workspace }}/nuget
  PYPI_PASSWORD: ${{ secrets.PYPI_TOKEN }}
  PYPI_USERNAME: __token__
  TF_APPEND_USER_AGENT: pulumi
jobs:
  comment-on-pr:
    if: github.event.pull_request.head.repo.full_name != github.repository
    name: comment-on-pr
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
      - name: Comment PR
        uses: thollander/actions-comment-pull-request@v3
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          message: >
            PR is now waiting for a maintainer to run the acceptance tests.

            **Note for the maintainer:** To run the acceptance tests, please comment */run-acceptance-tests* on the PR
