name: Upgrade provider
on:
  issues:
    types:
      - opened
  workflow_dispatch: {}

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
jobs:
  upgrade_provider:
    if: ${{ (github.event.issue.user.login == 'descope-release-bot' && contains(github.event.issue.title, 'Upgrade terraform-provider-')) || github.event_name == 'workflow_dispatch' }}
    name: upgrade-provider
    runs-on: ubuntu-latest
    steps:
      - name: Get token
        id: get_token
        uses: tibdex/github-app-token@v2
        with:
          private_key: ${{ secrets.RELEASE_APP_PEM }}
          app_id: ${{ secrets.RELEASE_APP_ID }}

      - name: Call upgrade provider action
        uses: pulumi/pulumi-upgrade-provider-action@v0.0.14
        env:
          GH_TOKEN: ${{ steps.get_token.outputs.token }}
        with:
          kind: all
