// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

/**
 * Manages a Fingerprint connector and its configuration in a Descope project. Prevent fraud by adding device intelligence with the Fingerprint connector.
 */
export class FingerprintConnector extends pulumi.CustomResource {
    /**
     * Get an existing FingerprintConnector resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: FingerprintConnectorState, opts?: pulumi.CustomResourceOptions): FingerprintConnector {
        return new FingerprintConnector(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'descope:index/fingerprintConnector:FingerprintConnector';

    /**
     * Returns true if the given object is an instance of FingerprintConnector.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is FingerprintConnector {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === FingerprintConnector.__pulumiType;
    }

    /**
     * The Cloudflare integration Endpoint URL.
     */
    declare public readonly cloudflareEndpointUrl: pulumi.Output<string>;
    /**
     * The Cloudflare integration Script URL.
     */
    declare public readonly cloudflareScriptUrl: pulumi.Output<string>;
    /**
     * A description of what your connector is used for.
     */
    declare public readonly description: pulumi.Output<string>;
    /**
     * Whether the connector is disabled. This can be used to temporarily stop a connector from executing without fully deleting it.
     */
    declare public readonly disabled: pulumi.Output<boolean>;
    /**
     * A custom name for your connector.
     */
    declare public readonly name: pulumi.Output<string>;
    /**
     * The ID of the Descope project that the connector belongs to. Changing this value will require the resource to be deleted and recreated.
     */
    declare public readonly projectId: pulumi.Output<string>;
    /**
     * The Fingerprint public API key.
     */
    declare public readonly publicApiKey: pulumi.Output<string>;
    /**
     * The Fingerprint region your workspace belongs to: `us` (default), `eu`, or `ap`. A workspace is bound to one region and cannot be moved; using the wrong one returns 403 on every request. Find it in your Fingerprint dashboard.
     */
    declare public readonly region: pulumi.Output<string>;
    /**
     * The Fingerprint secret API key.
     */
    declare public readonly secretApiKey: pulumi.Output<string>;
    /**
     * Enable to configure the relevant Cloudflare integration parameters if Cloudflare integration is set in your Fingerprint account.
     */
    declare public readonly useCloudflareIntegration: pulumi.Output<boolean>;

    /**
     * Create a FingerprintConnector resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: FingerprintConnectorArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: FingerprintConnectorArgs | FingerprintConnectorState, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as FingerprintConnectorState | undefined;
            resourceInputs["cloudflareEndpointUrl"] = state?.cloudflareEndpointUrl;
            resourceInputs["cloudflareScriptUrl"] = state?.cloudflareScriptUrl;
            resourceInputs["description"] = state?.description;
            resourceInputs["disabled"] = state?.disabled;
            resourceInputs["name"] = state?.name;
            resourceInputs["projectId"] = state?.projectId;
            resourceInputs["publicApiKey"] = state?.publicApiKey;
            resourceInputs["region"] = state?.region;
            resourceInputs["secretApiKey"] = state?.secretApiKey;
            resourceInputs["useCloudflareIntegration"] = state?.useCloudflareIntegration;
        } else {
            const args = argsOrState as FingerprintConnectorArgs | undefined;
            if (args?.projectId === undefined && !opts.urn) {
                throw new Error("Missing required property 'projectId'");
            }
            if (args?.publicApiKey === undefined && !opts.urn) {
                throw new Error("Missing required property 'publicApiKey'");
            }
            if (args?.secretApiKey === undefined && !opts.urn) {
                throw new Error("Missing required property 'secretApiKey'");
            }
            resourceInputs["cloudflareEndpointUrl"] = args?.cloudflareEndpointUrl;
            resourceInputs["cloudflareScriptUrl"] = args?.cloudflareScriptUrl;
            resourceInputs["description"] = args?.description;
            resourceInputs["disabled"] = args?.disabled;
            resourceInputs["name"] = args?.name;
            resourceInputs["projectId"] = args?.projectId;
            resourceInputs["publicApiKey"] = args?.publicApiKey;
            resourceInputs["region"] = args?.region;
            resourceInputs["secretApiKey"] = args?.secretApiKey ? pulumi.secret(args.secretApiKey) : undefined;
            resourceInputs["useCloudflareIntegration"] = args?.useCloudflareIntegration;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        const secretOpts = { additionalSecretOutputs: ["secretApiKey"] };
        opts = pulumi.mergeOptions(opts, secretOpts);
        super(FingerprintConnector.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * Input properties used for looking up and filtering FingerprintConnector resources.
 */
export interface FingerprintConnectorState {
    /**
     * The Cloudflare integration Endpoint URL.
     */
    cloudflareEndpointUrl?: pulumi.Input<string | undefined>;
    /**
     * The Cloudflare integration Script URL.
     */
    cloudflareScriptUrl?: pulumi.Input<string | undefined>;
    /**
     * A description of what your connector is used for.
     */
    description?: pulumi.Input<string | undefined>;
    /**
     * Whether the connector is disabled. This can be used to temporarily stop a connector from executing without fully deleting it.
     */
    disabled?: pulumi.Input<boolean | undefined>;
    /**
     * A custom name for your connector.
     */
    name?: pulumi.Input<string | undefined>;
    /**
     * The ID of the Descope project that the connector belongs to. Changing this value will require the resource to be deleted and recreated.
     */
    projectId?: pulumi.Input<string | undefined>;
    /**
     * The Fingerprint public API key.
     */
    publicApiKey?: pulumi.Input<string | undefined>;
    /**
     * The Fingerprint region your workspace belongs to: `us` (default), `eu`, or `ap`. A workspace is bound to one region and cannot be moved; using the wrong one returns 403 on every request. Find it in your Fingerprint dashboard.
     */
    region?: pulumi.Input<string | undefined>;
    /**
     * The Fingerprint secret API key.
     */
    secretApiKey?: pulumi.Input<string | undefined>;
    /**
     * Enable to configure the relevant Cloudflare integration parameters if Cloudflare integration is set in your Fingerprint account.
     */
    useCloudflareIntegration?: pulumi.Input<boolean | undefined>;
}

/**
 * The set of arguments for constructing a FingerprintConnector resource.
 */
export interface FingerprintConnectorArgs {
    /**
     * The Cloudflare integration Endpoint URL.
     */
    cloudflareEndpointUrl?: pulumi.Input<string | undefined>;
    /**
     * The Cloudflare integration Script URL.
     */
    cloudflareScriptUrl?: pulumi.Input<string | undefined>;
    /**
     * A description of what your connector is used for.
     */
    description?: pulumi.Input<string | undefined>;
    /**
     * Whether the connector is disabled. This can be used to temporarily stop a connector from executing without fully deleting it.
     */
    disabled?: pulumi.Input<boolean | undefined>;
    /**
     * A custom name for your connector.
     */
    name?: pulumi.Input<string | undefined>;
    /**
     * The ID of the Descope project that the connector belongs to. Changing this value will require the resource to be deleted and recreated.
     */
    projectId: pulumi.Input<string>;
    /**
     * The Fingerprint public API key.
     */
    publicApiKey: pulumi.Input<string>;
    /**
     * The Fingerprint region your workspace belongs to: `us` (default), `eu`, or `ap`. A workspace is bound to one region and cannot be moved; using the wrong one returns 403 on every request. Find it in your Fingerprint dashboard.
     */
    region?: pulumi.Input<string | undefined>;
    /**
     * The Fingerprint secret API key.
     */
    secretApiKey: pulumi.Input<string>;
    /**
     * Enable to configure the relevant Cloudflare integration parameters if Cloudflare integration is set in your Fingerprint account.
     */
    useCloudflareIntegration?: pulumi.Input<boolean | undefined>;
}
