// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

/**
 * Manages the project-level passkey (WebAuthn) authentication settings. This is a singleton resource, and its id is always the project ID.
 */
export class PasskeySettings extends pulumi.CustomResource {
    /**
     * Get an existing PasskeySettings resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: PasskeySettingsState, opts?: pulumi.CustomResourceOptions): PasskeySettings {
        return new PasskeySettings(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'descope:index/passkeySettings:PasskeySettings';

    /**
     * Returns true if the given object is an instance of PasskeySettings.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is PasskeySettings {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === PasskeySettings.__pulumiType;
    }

    /**
     * A list of SHA-256 APK key hash fingerprints (colon-separated hex, e.g. `AB:CD:EF:...`) that are allowed as passkey origins for Android apps. When set, only Android apps with a matching fingerprint will be permitted to use passkey authentication.
     */
    declare public readonly androidFingerprints: pulumi.Output<string[]>;
    /**
     * Setting this to `true` will disallow using passkey authentication directly via API and SDK calls. Note that this does not affect authentication flows that are configured to use passkeys.
     */
    declare public readonly disabled: pulumi.Output<boolean>;
    /**
     * The human-friendly name shown to users when they create or use a passkey. Some password managers display this name, while others display the top level domain instead. When left empty, the project name is used.
     */
    declare public readonly displayName: pulumi.Output<string>;
    /**
     * The ID of the project that these settings belong to. Changing this value will require the resource to be deleted and recreated.
     */
    declare public readonly projectId: pulumi.Output<string>;
    /**
     * Passkeys will be usable in the following domain and all its subdomains.
     */
    declare public readonly topLevelDomain: pulumi.Output<string>;

    /**
     * Create a PasskeySettings resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: PasskeySettingsArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: PasskeySettingsArgs | PasskeySettingsState, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as PasskeySettingsState | undefined;
            resourceInputs["androidFingerprints"] = state?.androidFingerprints;
            resourceInputs["disabled"] = state?.disabled;
            resourceInputs["displayName"] = state?.displayName;
            resourceInputs["projectId"] = state?.projectId;
            resourceInputs["topLevelDomain"] = state?.topLevelDomain;
        } else {
            const args = argsOrState as PasskeySettingsArgs | undefined;
            if (args?.projectId === undefined && !opts.urn) {
                throw new Error("Missing required property 'projectId'");
            }
            resourceInputs["androidFingerprints"] = args?.androidFingerprints;
            resourceInputs["disabled"] = args?.disabled;
            resourceInputs["displayName"] = args?.displayName;
            resourceInputs["projectId"] = args?.projectId;
            resourceInputs["topLevelDomain"] = args?.topLevelDomain;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(PasskeySettings.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * Input properties used for looking up and filtering PasskeySettings resources.
 */
export interface PasskeySettingsState {
    /**
     * A list of SHA-256 APK key hash fingerprints (colon-separated hex, e.g. `AB:CD:EF:...`) that are allowed as passkey origins for Android apps. When set, only Android apps with a matching fingerprint will be permitted to use passkey authentication.
     */
    androidFingerprints?: pulumi.Input<pulumi.Input<string>[] | undefined>;
    /**
     * Setting this to `true` will disallow using passkey authentication directly via API and SDK calls. Note that this does not affect authentication flows that are configured to use passkeys.
     */
    disabled?: pulumi.Input<boolean | undefined>;
    /**
     * The human-friendly name shown to users when they create or use a passkey. Some password managers display this name, while others display the top level domain instead. When left empty, the project name is used.
     */
    displayName?: pulumi.Input<string | undefined>;
    /**
     * The ID of the project that these settings belong to. Changing this value will require the resource to be deleted and recreated.
     */
    projectId?: pulumi.Input<string | undefined>;
    /**
     * Passkeys will be usable in the following domain and all its subdomains.
     */
    topLevelDomain?: pulumi.Input<string | undefined>;
}

/**
 * The set of arguments for constructing a PasskeySettings resource.
 */
export interface PasskeySettingsArgs {
    /**
     * A list of SHA-256 APK key hash fingerprints (colon-separated hex, e.g. `AB:CD:EF:...`) that are allowed as passkey origins for Android apps. When set, only Android apps with a matching fingerprint will be permitted to use passkey authentication.
     */
    androidFingerprints?: pulumi.Input<pulumi.Input<string>[] | undefined>;
    /**
     * Setting this to `true` will disallow using passkey authentication directly via API and SDK calls. Note that this does not affect authentication flows that are configured to use passkeys.
     */
    disabled?: pulumi.Input<boolean | undefined>;
    /**
     * The human-friendly name shown to users when they create or use a passkey. Some password managers display this name, while others display the top level domain instead. When left empty, the project name is used.
     */
    displayName?: pulumi.Input<string | undefined>;
    /**
     * The ID of the project that these settings belong to. Changing this value will require the resource to be deleted and recreated.
     */
    projectId: pulumi.Input<string>;
    /**
     * Passkeys will be usable in the following domain and all its subdomains.
     */
    topLevelDomain?: pulumi.Input<string | undefined>;
}
