// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

/**
 * Manages a single SAML federated application where Descope acts as the identity provider.
 */
export class SamlApp extends pulumi.CustomResource {
    /**
     * Get an existing SamlApp resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: SamlAppState, opts?: pulumi.CustomResourceOptions): SamlApp {
        return new SamlApp(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'descope:index/samlApp:SamlApp';

    /**
     * Returns true if the given object is an instance of SamlApp.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is SamlApp {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === SamlApp.__pulumiType;
    }

    /**
     * A list of allowed ACS callback URLS. This configuration is used when the default ACS URL value is unreachable. Supports wildcards.
     */
    declare public readonly acsAllowedCallbackUrls: pulumi.Output<string[]>;
    /**
     * A list of attribute mappings from Descope user attributes to SAML assertion attributes.
     */
    declare public readonly attributeMappings: pulumi.Output<outputs.SamlAppAttributeMapping[]>;
    /**
     * The default relay state. When using IdP-initiated authentication, this value may be used as a URL to a resource in the Service Provider.
     */
    declare public readonly defaultRelayState: pulumi.Output<string>;
    /**
     * The signature algorithm used to sign SAML responses. Choose one of `""` (default, SHA-1) or `"sha256"` (SHA-256). Only applies to IdP-initiated flows — SP-initiated flows use the algorithm specified in the SP's SAML request.
     */
    declare public readonly defaultSignatureAlgorithm: pulumi.Output<string>;
    /**
     * Protects the application from being accidentally destroyed or replaced. Destroying or replacing a federated application breaks the service provider's configured integration, so these applications are protected by default. To allow the resource to be destroyed or replaced, for example in ephemeral test environments, set this attribute to `false` and apply the change first.
     */
    declare public readonly deletionProtection: pulumi.Output<boolean | undefined>;
    /**
     * A description for the SAML application.
     */
    declare public readonly description: pulumi.Output<string>;
    /**
     * Whether the application should be enabled or disabled.
     */
    declare public readonly disabled: pulumi.Output<boolean>;
    /**
     * Connection details are retrieved dynamically from the SP's metadata URL. Exactly one of `dynamicConfiguration` and `manualConfiguration` must be set.
     */
    declare public readonly dynamicConfiguration: pulumi.Output<outputs.SamlAppDynamicConfiguration>;
    /**
     * This configuration overrides the default behavior of the SSO application and forces the user to authenticate via the Descope flow, regardless of the SP's request.
     */
    declare public readonly forceAuthentication: pulumi.Output<boolean>;
    /**
     * The Flow Hosting URL. When left empty the project's default login page URL is used, and the computed value is reflected in this attribute. Read more about using this parameter with custom domain [here](https://docs.descope.com/sso-integrations/applications/saml-apps).
     */
    declare public readonly loginPageUrl: pulumi.Output<string>;
    /**
     * A logo for the SAML application. Should be a hosted image URL.
     */
    declare public readonly logo: pulumi.Output<string>;
    /**
     * Connection details are provided manually. Exactly one of `dynamicConfiguration` and `manualConfiguration` must be set.
     */
    declare public readonly manualConfiguration: pulumi.Output<outputs.SamlAppManualConfiguration>;
    /**
     * A name for the SAML application.
     */
    declare public readonly name: pulumi.Output<string>;
    /**
     * The ID of the project that this application belongs to. Changing this value will require the resource to be deleted and recreated.
     */
    declare public readonly projectId: pulumi.Output<string>;
    /**
     * An optional identifier for the application. When omitted, an identifier is generated by the server. Can only be set when the application is created, and changing it will require the resource to be deleted and recreated.
     */
    declare public readonly samlAppId: pulumi.Output<string>;
    /**
     * The subject name id format. Choose one of "", "urn:oasis:names:tc:SAML:1.1:nameid-format:unspecified", "urn:oasis:names:tc:SAML:1.1:nameid-format:emailAddress", "urn:oasis:names:tc:SAML:2.0:nameid-format:persistent", "urn:oasis:names:tc:SAML:2.0:nameid-format:transient". Read more about this configuration [here](https://docs.descope.com/sso-integrations/applications/saml-apps).
     */
    declare public readonly subjectNameIdFormat: pulumi.Output<string>;
    /**
     * The subject name id type. Choose one of "", "email", "phone". Read more about this configuration [here](https://docs.descope.com/sso-integrations/applications/saml-apps).
     */
    declare public readonly subjectNameIdType: pulumi.Output<string>;

    /**
     * Create a SamlApp resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: SamlAppArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: SamlAppArgs | SamlAppState, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as SamlAppState | undefined;
            resourceInputs["acsAllowedCallbackUrls"] = state?.acsAllowedCallbackUrls;
            resourceInputs["attributeMappings"] = state?.attributeMappings;
            resourceInputs["defaultRelayState"] = state?.defaultRelayState;
            resourceInputs["defaultSignatureAlgorithm"] = state?.defaultSignatureAlgorithm;
            resourceInputs["deletionProtection"] = state?.deletionProtection;
            resourceInputs["description"] = state?.description;
            resourceInputs["disabled"] = state?.disabled;
            resourceInputs["dynamicConfiguration"] = state?.dynamicConfiguration;
            resourceInputs["forceAuthentication"] = state?.forceAuthentication;
            resourceInputs["loginPageUrl"] = state?.loginPageUrl;
            resourceInputs["logo"] = state?.logo;
            resourceInputs["manualConfiguration"] = state?.manualConfiguration;
            resourceInputs["name"] = state?.name;
            resourceInputs["projectId"] = state?.projectId;
            resourceInputs["samlAppId"] = state?.samlAppId;
            resourceInputs["subjectNameIdFormat"] = state?.subjectNameIdFormat;
            resourceInputs["subjectNameIdType"] = state?.subjectNameIdType;
        } else {
            const args = argsOrState as SamlAppArgs | undefined;
            if (args?.projectId === undefined && !opts.urn) {
                throw new Error("Missing required property 'projectId'");
            }
            resourceInputs["acsAllowedCallbackUrls"] = args?.acsAllowedCallbackUrls;
            resourceInputs["attributeMappings"] = args?.attributeMappings;
            resourceInputs["defaultRelayState"] = args?.defaultRelayState;
            resourceInputs["defaultSignatureAlgorithm"] = args?.defaultSignatureAlgorithm;
            resourceInputs["deletionProtection"] = args?.deletionProtection;
            resourceInputs["description"] = args?.description;
            resourceInputs["disabled"] = args?.disabled;
            resourceInputs["dynamicConfiguration"] = args?.dynamicConfiguration;
            resourceInputs["forceAuthentication"] = args?.forceAuthentication;
            resourceInputs["loginPageUrl"] = args?.loginPageUrl;
            resourceInputs["logo"] = args?.logo;
            resourceInputs["manualConfiguration"] = args?.manualConfiguration;
            resourceInputs["name"] = args?.name;
            resourceInputs["projectId"] = args?.projectId;
            resourceInputs["samlAppId"] = args?.samlAppId;
            resourceInputs["subjectNameIdFormat"] = args?.subjectNameIdFormat;
            resourceInputs["subjectNameIdType"] = args?.subjectNameIdType;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(SamlApp.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * Input properties used for looking up and filtering SamlApp resources.
 */
export interface SamlAppState {
    /**
     * A list of allowed ACS callback URLS. This configuration is used when the default ACS URL value is unreachable. Supports wildcards.
     */
    acsAllowedCallbackUrls?: pulumi.Input<pulumi.Input<string>[] | undefined>;
    /**
     * A list of attribute mappings from Descope user attributes to SAML assertion attributes.
     */
    attributeMappings?: pulumi.Input<pulumi.Input<inputs.SamlAppAttributeMapping>[] | undefined>;
    /**
     * The default relay state. When using IdP-initiated authentication, this value may be used as a URL to a resource in the Service Provider.
     */
    defaultRelayState?: pulumi.Input<string | undefined>;
    /**
     * The signature algorithm used to sign SAML responses. Choose one of `""` (default, SHA-1) or `"sha256"` (SHA-256). Only applies to IdP-initiated flows — SP-initiated flows use the algorithm specified in the SP's SAML request.
     */
    defaultSignatureAlgorithm?: pulumi.Input<string | undefined>;
    /**
     * Protects the application from being accidentally destroyed or replaced. Destroying or replacing a federated application breaks the service provider's configured integration, so these applications are protected by default. To allow the resource to be destroyed or replaced, for example in ephemeral test environments, set this attribute to `false` and apply the change first.
     */
    deletionProtection?: pulumi.Input<boolean | undefined>;
    /**
     * A description for the SAML application.
     */
    description?: pulumi.Input<string | undefined>;
    /**
     * Whether the application should be enabled or disabled.
     */
    disabled?: pulumi.Input<boolean | undefined>;
    /**
     * Connection details are retrieved dynamically from the SP's metadata URL. Exactly one of `dynamicConfiguration` and `manualConfiguration` must be set.
     */
    dynamicConfiguration?: pulumi.Input<inputs.SamlAppDynamicConfiguration | undefined>;
    /**
     * This configuration overrides the default behavior of the SSO application and forces the user to authenticate via the Descope flow, regardless of the SP's request.
     */
    forceAuthentication?: pulumi.Input<boolean | undefined>;
    /**
     * The Flow Hosting URL. When left empty the project's default login page URL is used, and the computed value is reflected in this attribute. Read more about using this parameter with custom domain [here](https://docs.descope.com/sso-integrations/applications/saml-apps).
     */
    loginPageUrl?: pulumi.Input<string | undefined>;
    /**
     * A logo for the SAML application. Should be a hosted image URL.
     */
    logo?: pulumi.Input<string | undefined>;
    /**
     * Connection details are provided manually. Exactly one of `dynamicConfiguration` and `manualConfiguration` must be set.
     */
    manualConfiguration?: pulumi.Input<inputs.SamlAppManualConfiguration | undefined>;
    /**
     * A name for the SAML application.
     */
    name?: pulumi.Input<string | undefined>;
    /**
     * The ID of the project that this application belongs to. Changing this value will require the resource to be deleted and recreated.
     */
    projectId?: pulumi.Input<string | undefined>;
    /**
     * An optional identifier for the application. When omitted, an identifier is generated by the server. Can only be set when the application is created, and changing it will require the resource to be deleted and recreated.
     */
    samlAppId?: pulumi.Input<string | undefined>;
    /**
     * The subject name id format. Choose one of "", "urn:oasis:names:tc:SAML:1.1:nameid-format:unspecified", "urn:oasis:names:tc:SAML:1.1:nameid-format:emailAddress", "urn:oasis:names:tc:SAML:2.0:nameid-format:persistent", "urn:oasis:names:tc:SAML:2.0:nameid-format:transient". Read more about this configuration [here](https://docs.descope.com/sso-integrations/applications/saml-apps).
     */
    subjectNameIdFormat?: pulumi.Input<string | undefined>;
    /**
     * The subject name id type. Choose one of "", "email", "phone". Read more about this configuration [here](https://docs.descope.com/sso-integrations/applications/saml-apps).
     */
    subjectNameIdType?: pulumi.Input<string | undefined>;
}

/**
 * The set of arguments for constructing a SamlApp resource.
 */
export interface SamlAppArgs {
    /**
     * A list of allowed ACS callback URLS. This configuration is used when the default ACS URL value is unreachable. Supports wildcards.
     */
    acsAllowedCallbackUrls?: pulumi.Input<pulumi.Input<string>[] | undefined>;
    /**
     * A list of attribute mappings from Descope user attributes to SAML assertion attributes.
     */
    attributeMappings?: pulumi.Input<pulumi.Input<inputs.SamlAppAttributeMapping>[] | undefined>;
    /**
     * The default relay state. When using IdP-initiated authentication, this value may be used as a URL to a resource in the Service Provider.
     */
    defaultRelayState?: pulumi.Input<string | undefined>;
    /**
     * The signature algorithm used to sign SAML responses. Choose one of `""` (default, SHA-1) or `"sha256"` (SHA-256). Only applies to IdP-initiated flows — SP-initiated flows use the algorithm specified in the SP's SAML request.
     */
    defaultSignatureAlgorithm?: pulumi.Input<string | undefined>;
    /**
     * Protects the application from being accidentally destroyed or replaced. Destroying or replacing a federated application breaks the service provider's configured integration, so these applications are protected by default. To allow the resource to be destroyed or replaced, for example in ephemeral test environments, set this attribute to `false` and apply the change first.
     */
    deletionProtection?: pulumi.Input<boolean | undefined>;
    /**
     * A description for the SAML application.
     */
    description?: pulumi.Input<string | undefined>;
    /**
     * Whether the application should be enabled or disabled.
     */
    disabled?: pulumi.Input<boolean | undefined>;
    /**
     * Connection details are retrieved dynamically from the SP's metadata URL. Exactly one of `dynamicConfiguration` and `manualConfiguration` must be set.
     */
    dynamicConfiguration?: pulumi.Input<inputs.SamlAppDynamicConfiguration | undefined>;
    /**
     * This configuration overrides the default behavior of the SSO application and forces the user to authenticate via the Descope flow, regardless of the SP's request.
     */
    forceAuthentication?: pulumi.Input<boolean | undefined>;
    /**
     * The Flow Hosting URL. When left empty the project's default login page URL is used, and the computed value is reflected in this attribute. Read more about using this parameter with custom domain [here](https://docs.descope.com/sso-integrations/applications/saml-apps).
     */
    loginPageUrl?: pulumi.Input<string | undefined>;
    /**
     * A logo for the SAML application. Should be a hosted image URL.
     */
    logo?: pulumi.Input<string | undefined>;
    /**
     * Connection details are provided manually. Exactly one of `dynamicConfiguration` and `manualConfiguration` must be set.
     */
    manualConfiguration?: pulumi.Input<inputs.SamlAppManualConfiguration | undefined>;
    /**
     * A name for the SAML application.
     */
    name?: pulumi.Input<string | undefined>;
    /**
     * The ID of the project that this application belongs to. Changing this value will require the resource to be deleted and recreated.
     */
    projectId: pulumi.Input<string>;
    /**
     * An optional identifier for the application. When omitted, an identifier is generated by the server. Can only be set when the application is created, and changing it will require the resource to be deleted and recreated.
     */
    samlAppId?: pulumi.Input<string | undefined>;
    /**
     * The subject name id format. Choose one of "", "urn:oasis:names:tc:SAML:1.1:nameid-format:unspecified", "urn:oasis:names:tc:SAML:1.1:nameid-format:emailAddress", "urn:oasis:names:tc:SAML:2.0:nameid-format:persistent", "urn:oasis:names:tc:SAML:2.0:nameid-format:transient". Read more about this configuration [here](https://docs.descope.com/sso-integrations/applications/saml-apps).
     */
    subjectNameIdFormat?: pulumi.Input<string | undefined>;
    /**
     * The subject name id type. Choose one of "", "email", "phone". Read more about this configuration [here](https://docs.descope.com/sso-integrations/applications/saml-apps).
     */
    subjectNameIdType?: pulumi.Input<string | undefined>;
}
