# coding=utf-8
# *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import copy
import warnings
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
from . import _utilities

__all__ = [
    'GetDataResult',
    'AwaitableGetDataResult',
    'get_data',
    'get_data_output',
]

@pulumi.output_type
class GetDataResult:
    """
    A collection of values returned by getData.
    """
    def __init__(__self__, id=None, value=None):
        if id and not isinstance(id, str):
            raise TypeError("Expected argument 'id' to be a str")
        pulumi.set(__self__, "id", id)
        if value and not isinstance(value, str):
            raise TypeError("Expected argument 'value' to be a str")
        pulumi.set(__self__, "value", value)

    @property
    @pulumi.getter
    def id(self) -> str:
        """
        The provider-assigned unique ID for this managed resource.
        """
        return pulumi.get(self, "id")

    @property
    @pulumi.getter
    def value(self) -> str:
        return pulumi.get(self, "value")


class AwaitableGetDataResult(GetDataResult):
    # pylint: disable=using-constant-test
    def __await__(self):
        if False:
            yield self
        return GetDataResult(
            id=self.id,
            value=self.value)


def get_data(opts: Optional[pulumi.InvokeOptions] = None) -> AwaitableGetDataResult:
    """
    Use this data source to access information about an existing resource.
    """
    __args__ = dict()
    opts = pulumi.InvokeOptions.merge(_utilities.get_invoke_opts_defaults(), opts)
    __ret__ = pulumi.runtime.invoke('descope:index/getData:getData', __args__, opts=opts, typ=GetDataResult).value

    return AwaitableGetDataResult(
        id=pulumi.get(__ret__, 'id'),
        value=pulumi.get(__ret__, 'value'))


@_utilities.lift_output_func(get_data)
def get_data_output(opts: Optional[pulumi.InvokeOptions] = None) -> pulumi.Output[GetDataResult]:
    """
    Use this data source to access information about an existing resource.
    """
    ...
